---
name: pas-windows
metadata_version: '2.10' # When a 2.11 Ops Manager appears, this value should be updated to be equal to the product version
provides_product_versions:
- name: pas-windows
  version: $( version )
product_version: $( version )
minimum_version_for_upgrade: 2.11.0
requires_product_versions:
- name: cf
  version: "~> 2.12.0"
label: $( variable "label" )
description: "Gives developers the ability to push apps to compute instances powered by the .NET Framework and the Windows® Operating System"
icon_image: $( icon )
rank: 88
serial: false

kiln_metadata:
  metadata_git_sha: $( variable "metadata-git-sha" )

stemcell_criteria: $( stemcell )

releases:
- $( release "diego" )
- $( release "event-log" )
- $( release "garden-runc" )
- $( release "hwc-offline-buildpack" )
- $( release "loggregator-agent" )
- $( release "metrics-discovery" )
- $( release "winc" )
- $( release "windows-utilities" )
- $( release "smoke-tests" )
- $( release "envoy-nginx" )

form_types:
- $( form "vm_options" )
- $( form "application_containers" )
- $( form "system_logging" )
- $( form "smoke_tests_windows" )
- $( form "advanced_features" )

job_types:
- $( instance_group "windows_diego_cell" )

property_blueprints:
- $( property "app_log_rate_limiting" )
- $( property "bbs_client_cert" )
- $( property "bosh_ssh_enabled" )
- $( property "forwarder_agent_metrics_tls" )
- $( property "route_integrity" )
- $( property "kms" )
- $( property "loggregator_client_cert" )
- $( property "loggregator_agent_tls_cert" )
- $( property "loggregator_agent_metrics_tls" )
- $( property "prom_scraper_scrape_tls" )
- $( property "prom_scraper_metrics_tls" )
- $( property "metrics_agent_metrics_tls" )
- $( property "metrics_discovery_metrics_tls" )
- $( property "rep_server_cert" )
- $( property "rep_server_cert_v2" )
- $( property "smoke_tests_windows" )
- $( property "syslog_agent_metrics_tls" )
- $( property "system_logging" )
- $( property "system_metrics_tls_scraper_cert" )
- $( property "windows_admin_password" )
- $( property "scheduler_binding_cache_tls" )


post_deploy_errands:
  - name: install-hwc-buildpack
    colocated: true
    run_default: true
    instances:
      - windows_diego_cell/first
    label: Install HWC Buildpack Errand
    description: Install the HWC buildpack to your installation
  - name: smoke_tests_windows
    colocated: true
    run_default: false
    instances:
      - windows_diego_cell/first
    label: Smoke Test Errand
    description: Runs Smoke Tests against your installation

install_time_verifiers: []

variables:
- name: diego-instance-identity-intermediate-ca-2-7
  type: certificate
  options:
    common_name: 'Diego Instance Identity Intermediate CA'
    is_ca: true
    duration: 730
    ca: /cf/diego-instance-identity-root-ca-2-6
    key_usage:
    - key_cert_sign

- name: /services/tls_leaf
  options:
    ca: /services/tls_ca
    common_name: services-tls-leaf
    alternative_names:
      - services-tls-leaf
  type: certificate
  update_mode: converge

