---
form:
  name: application_dev_controls
  label: Application Developer Controls
  description: |
    Configure restrictions and default settings for applications pushed to
    Elastic Runtime.

  property_inputs:
    - reference: .cloud_controller.max_file_size
      label: Maximum File Upload Size (MB)
      description: |
        Maximum size of an application upload droplet.

    - reference: .cloud_controller.default_app_memory
      label: Default App Memory (MB)
      description: |
        Memory allocated to a newly-pushed app when no value is specified at `cf
        push`.

    - reference: .cloud_controller.default_quota_memory_limit_mb
      label: Default App Memory Quota per Org (MB)
      description: |
        Default memory limit for all apps in an org. This default only applies
        for the first installation of Elastic Runtime. After initial
        installation, use the CLI to manage quotas.

    - reference: .cloud_controller.max_disk_quota_app
      label: Maximum Disk Quota per App (MB)
      description: |
        Maximum disk allocated per app. In the event of a system upgrade or
        outage that causes a rolling deploy, larger apps may not successfully
        re-deploy if there is insufficient disk capacity.

    - reference: .cloud_controller.default_disk_quota_app
      label: Default Disk Quota per App (MB)
      description: |
        Default disk allocated per app. In the event of a system upgrade or
        outage that causes a rolling deploy, larger apps may not re-deploy
        successfully if there is insufficient disk capacity.

    - reference: .cloud_controller.default_quota_max_number_services
      label: Default Service Instances Quota per Org
      description: |
        Default maximum number of service instances in an org. This default
        only applies for the first installation of Elastic Runtime, otherwise
        use the CLI to manage quotas
