---
form:
  name: diego_config
  label: Diego Config
  description: Diego Config
  property_inputs:
  - reference: .diego_cell.executor_memory_capacity
    label: Cell Memory Capacity (MB)
  - reference: .diego_cell.executor_disk_capacity
    label: Cell Disk Capacity (MB)
  - reference: .diego_cell.garden_network_pool
    label: Applications Subnet (Only change this if you need to avoid address collision with a third-party service on the same subnet.)
    description: Enter a CIDR subnet mask specifying the range of available IP addresses to be assigned to your app containers. This must be different from the network used by the system VMs.
  - reference: .diego_cell.garden_network_mtu
    label: Applications Network Maximum Transmission Unit (MTU) (in bytes)
    description: The default 1454 bytes is fine for most cases, but you might need less, such as for networks that use GRE tunnels.
  - reference: .diego_cell.insecure_docker_registry_list
    label: Private Docker Insecure Registry Whitelist
    description: If you use private Docker image registries that are secured with self-signed certificates, enter them here as a comma-delimited list. List each registry as either an IP:Port tuple or a Hostname:Port tuple.
    placeholder: "10.10.10.10:8888,example.com:8888"
