---
form:
  name: mysql_config
  label: Internal MySQL
  description:  Only configure this section if you selected Internal Databases - MySQL or Internal Databases - MySQL and Postgres in the previous Databases section.
  markdown: |
    ## A proxy tier routes MySQL connections from internal components to healthy cluster nodes. Configure DNS and/or your own load balancer to point to multiple proxy instances for increased availability. TCP healthchecks can be configured against port 1936.
    ## The automated backups functionality works with any S3-compatible file store that can receive your backup files.
  property_inputs:
    - reference: .mysql_proxy.static_ips
      label: MySQL Proxy IPs
      description: "Enter the IP address(es) for the MySQL proxy instances configured on your external load balancer."
    - reference: .mysql_monitor.poll_frequency
      label: Replication canary time period
      description: "How frequently the canary checks for replication failure, in seconds. Lower numbers will cause the canary to run more frequently, adding load to the database."
    - reference: .mysql_monitor.write_read_delay
      label: Replication canary read delay
      description: "How long the canary waits to verify data is replicating across each MySQL node, in seconds. Clusters under heavily load will experience some small replication lag as writesets are committed across the nodes."
    - reference: .mysql_monitor.recipient_email
      label: E-mail address (required)
      description: "The MySQL service will send alerts when the cluster experiences a replication issue or a node is not allowed to auto-rejoin the cluster."
      placeholder: "Fill in your desired email address"
    - reference: .properties.mysql_backups
      label: Automated Backups Configuration
      selector_property_inputs:
      - reference: .properties.mysql_backups.disable
        label: Disable automated backups of MySQL
        description: Disable automated backups of MySQL
      - reference: .properties.mysql_backups.s3
        label: Enable automated backups from MySQL to an S3 bucket or other S3-compatible file store
        description: Enable automated backups from MySQL to an S3 bucket or other S3-compatible file store
        property_inputs:
        - reference: .properties.mysql_backups.s3.endpoint_url
          label: S3 Endpoint URL
          description: Specify the endpoint that matches the region the bucket is hosted in. Defaults to https://s3.amazonaws.com for us-east-1 if no url is provided.
        - reference: .properties.mysql_backups.s3.bucket_name
          label: S3 Bucket Name
          description: Do not include 's3://' prefix, trailing '/', or underscores. The bucket is created automatically if it does not already exist.
          placeholder: "my-bucket"
        - reference: .properties.mysql_backups.s3.bucket_path
          label: Bucket Path
          description: Specify a folder within the bucket to hold the MySQL backups. Do not include a trailing slash.
          placeholder: "my-backups-folder/elastic-runtime"
        - reference: .properties.mysql_backups.s3.access_key_id
          label: AWS Access Key ID
        - reference: .properties.mysql_backups.s3.secret_access_key
          label: AWS Secret Access Key
        - reference: .properties.mysql_backups.s3.cron_schedule
          label: Cron Schedule
          description: Schedule MySQL backups as a cron expression (see http://godoc.org/github.com/robfig/cron). Schedule uses the machine local time zone.
          placeholder: "@every 15m"
        - reference: .properties.mysql_backups.s3.backup_all_masters
          label: Backup All Nodes
          description: Each node is a duplicate master. This option makes unique backups from each master, rather than from a single instance.
      - reference: .properties.mysql_backups.scp
        label: Enable automated backups from MySQL to a remote host via SCP
        description: Enable automated backups from MySQL to a remote host via SCP
        property_inputs:
        - reference: .properties.mysql_backups.scp.server
          label: Hostname
        - reference: .properties.mysql_backups.scp.port
          label: Port
          description: SCP uses the SSH protocol, so provide the TCP port that your server uses for the SSH protocol.
        - reference: .properties.mysql_backups.scp.user
          label: Username
        - reference: .properties.mysql_backups.scp.key
          label: Private key
          description: Do not password protect
        - reference: .properties.mysql_backups.scp.destination
          label: Destination directory
        - reference: .properties.mysql_backups.scp.cron_schedule
          label: Cron Schedule
          description: Schedule MySQL backups as a cron expression (see http://godoc.org/github.com/robfig/cron). Schedule uses the machine local time zone.
        - reference: .properties.mysql_backups.scp.backup_all_masters
          label: Backup All Nodes
          description: Each node is a duplicate master. This option makes unique backups from each master, rather than from a single instance.
    - reference: .properties.mysql_activity_logging
      label: Server Activity Logging
      selector_property_inputs:
        - reference: .properties.mysql_activity_logging.disable
          label: Disable server activity logging
          description: Disable server activity logging
        - reference: .properties.mysql_activity_logging.enable
          label: Enable server activity logging
          description: Enable server activity logging
          property_inputs:
            - reference: .properties.mysql_activity_logging.enable.audit_logging_events
              label: Event types
              description: "The MySQL service will keep a record of server activity. The default setting tracks who connected to the system and what queries were processed. For more information, see: https://mariadb.com/kb/en/mariadb/about-the-mariadb-audit-plugin/"
