---
resources:
  - name: p-runtime
    type: git
    source:
      uri: git@github.com:pivotal-cf/p-runtime.git
      branch: {{branch_name}}
      private_key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIJKAIBAAKCAgEA1b1PjU8Z9eyVxVquclBsaZW7irH12wSqGp6KuXqtXKyE6P70
        NVLgxcY+xKE1Qs3qlEo0Bw4qJP2O8RI05VDDLf5m5z3VsnjXm+U9pw84xsqpTduX
        yS6W+/XVRvwFkqxAyGJz3/uEjLOjmyW26ZGROPCdr5q1QnNYeGcDIros17CBn9FR
        giVxvjRL2p4p3vFz6v2JjhlVyLvath4GpZDgcIdM9Hm0Biyu9iSo4wCNVpkuPRfD
        LBeNaW+rs47UnrmcwfqA/+BUx1qAiQwgCipPP1UN6i8hlib98rs/AN6AK4tJhJFA
        oRSgH4b+jGlEhY/wXk7hoTINaFAzyJEuGHBVUzUP6dcZr+vt3iZf/tpdu7hRWTDb
        qZ/XpRTp0TEAOymSrNu2HVcTd4YDR0g42PfTRhu8TLwEgN/TjanoRZwEndu2cKC+
        gOyk/YZp4pDf7fHnH59BRAfllO1nOJPsN5oJJag4rPkj7sDQ14p3T9ZT4yzy6gVv
        VEQdPyYCZ4iIYnpVFjIcdUgbjZxc6/TzkR7+ktbDL/wlaeM3I+CuqjZIARp0sW0M
        ve4Je/rbtqGvRZ+0wAnFA0tYQ90YzAl2kDv0vdE2FO1NkuQwhFSEBOLMeZluihxX
        thkCLCmkYz0pjHS0tGrhyGdsJhvJYV5guvy/T1njYa96fqfrFr6pckFNpD0CAwEA
        AQKCAgBt3K7FPYFkjMS2+lNsYrY210Xclnh+qTkeEZvQlqQBXJO8hz/TINR0E+Az
        hYEw41LOAg4YCknTVZlhhDA4JnkMbRVLitcKs15vvTchZYuTcpvvbw3n1NC6lbOY
        lvXuXCe4WBKjcE7DW5qeppYMHEx+7f6/QlAk5dD1ok1UTkm6W/lkwlyY/tImKA9N
        QbrX41fn04Yeyhrz4MscjPZxp7QVYxZFG0FTYyhTUKiWdbQwbO/9avdg9II1Tbb9
        xk63f0R52F7yJsas6XHj/52AXBr7vKY4Vx12ZnhliaVqtvM+bovNXjPQGB/t1J+G
        YJ1d4Yx1jSoghu+pTIAxeZ4t5Z+VAk/WrDRKX4UdGA5clfosUGgcttBAitmVUafP
        yuVsYWbdQfEVWl3rkUvQMgqa17PQcqoNAINv35EMc7NW+ESbTrVQotncyeSbLZkl
        2bTmc3cgkAcyexZgjScD4PFVJumzlehZlZUcQZusBMxTD3xk+EOYHbHNI3yXAvDL
        jMkdFKdsQZT/xecGR2g/NzRb6gju1Gl8yGXucn8NPQMsO07n1DFYGj+UAMSKdyFZ
        KxeNwkM/5WHFIs9XAjW+SVeYjrYKLKn5HzUjluf/rvadV2Z3aue/F8qpfOoH4mYv
        izWpylOLFr2wFx1z53lBEp9Qni6954AWge2BIbPss4BWVrawQQKCAQEA+itZcH2V
        T+MosA9NrtHNAYyiptSswXgkuggn1YlVhU640mNh9mDsbXN6G17jffqKqx0+wzyO
        +UNOK5zIj/6HgNHZZCkmhCAJ0odMiSiBEZJx8vaTmpTZnfaUjMgWdJm+xoNb0epI
        80uP0O6nARPWzX8bx9ulR3EdHtpmpnhPHFpi8k5cTXKfl7VDizypb5kwAEFJ55wl
        h9XCnK4av9B0F4Bd+Er1TTdO5A/bC8L7HogWKYQhWYoPFKDwjQRDG+MYP1bprGJn
        tUHOMYNXtIJ6b1u9hCm835fr65V6WFq8V8r6GWsjd8zfzTUUgfwmSIwEOS3OK6NS
        Na3imkg6k8HXmQKCAQEA2riZu5iqHytOcscmUqnfZ2kB/wIVVLpr8sIoZuZzDHYu
        fIPoHPXM3moQ0/H7aqCR7WM/j/6VROXZiA3pVDkhIvCiLcaOQSxZBNlF7IT6XOBM
        SHM4t0xq+JCQ/7MTwP4OxmFvv+0bEwbun53ZJxY3eQdABu+5OLIxkKoyLV6oEATQ
        4Ul1iQ4YHd3K61YfjevFUYb7PQV7zORK6Dnxbt+7ju4XkwlDewv/62dvNkjBpwcq
        fJwuIjn8K2Teq3F7NPaZxReHeSs6K10hDkTIIP3AWdIJE1crN7dlXusZ0xd1HY5y
        JnlnesY1DH/mFbyLXDeUOAZgBR/wdgflpIQpYffIRQKCAQBXIMvoosRi62GbV+kd
        TtKQjJOFeSKlyxs3c2m0ND2FzTIPjC9tKLqPMB3B9J1UnfK3v9rBEpFU/Pz3sYYk
        qGg3FF8bRD223JWvLhIY3vN81D09emVT/C2Cl4OLOJChkX5hExTimi9IFPQEt2mQ
        tYElVvSs+bGpnRqgST5hEhuza0N00pfRHW+53Zalor38MSUHobWEpdxoX6mE+ho0
        3fvgx4Ny22BtwSqHwYHvqbveGVVmpi8bSTsRWzAMXQSmbMRgIvwFXsxx03ZlxjHA
        m4Tazd/GbObsFLRE+2194jQge3/5ZFgY/FCh3q/CybfnomRCKdLZXete6K24QBmu
        pl9ZAoIBAQCnPSWXcqkKAjQOwUYFSQygZoN3OGGVEqI90cXQwH7R1X/AB6AwnKXU
        nudVGB70rehGym+sq635K4MEbBawJqq2q6ZmN/9HyCAc/AFiU1+YKo1JjIieZ1kX
        zHqCeawuElS7zX8EEslz6AYHmEuVfoBWE3wakaxftKj/g5Owa0M4VGZfDKtJa7R3
        CcMB5S1leBS9POfYBdxek2TPYpa//2TLajQuYpPtfwRlPAamTEV+cJVFCKqh0xKF
        H7C/CJt7qN90+4PD25Cz3ZbL8T3RNBWi2F3GIw3RoXJqfHuXk8UiH2wbDRNZpjqj
        3xvQHQW2Mm0r1XwQDxbvOSSXgdKerTa9AoIBAFlFzTMZ//v7F948Iz6DXJCjnQc8
        QS2WhFpK0IvCqTQOP6sF5+1WXC+h/0enu/gAPnVcHtZXIFmQdewxhhPcOAdH2BZh
        2NsDfcYJVx4Wtw9C9jikZQQYx505ZkYubo3GBgMRwHNGjBs16IdvsdX5AgxmSArT
        dXgfTDbXcRy62CIscE9V2fxABna7Vvik+/xt0KMvL8M/nzdBVc0bcbZm1KC+/Ycz
        pUEDWOX9vSlDhKleUJz6YFJiDE6JJ9yh8gwumDqrkPyAIRwHZeKYovrPpBQD7Seg
        jVZlEocQRYfQd6Sz8V+7xdz0Q47ix7QkOeiKNOsy5ESzLdqfNDZ/RPC2nF8=
        -----END RSA PRIVATE KEY-----

  - name: version
    type: semver
    source:
      access_key_id: AKIAJEAGY2FWB7DEGFXQ
      secret_access_key: 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
      bucket: ert-concourse-products
      region_name: us-west-1
      key: ert-1.6/version
      initial_version: 1.6.0-build.0

  - name: ert-product
    type: s3
    source:
      access_key_id: AKIAJEAGY2FWB7DEGFXQ
      secret_access_key: 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
      bucket: ert-concourse-products
      region_name: us-west-1
      private: true
      versioned_file: {{branch_name}}/ert.pivotal

  - name: environment
    type: pool
    source:
      uri: git@github.com:pivotal-cf-experimental/releng-env-resource-pool
      branch: master
      pool: {{iaas_type}}
      private_key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEowIBAAKCAQEAusDLytuEM/eX5vkwEFlTTKhnpDpUrKtxIOqcfGwg2gyH29jm
        RGIYLAIYGqfsAXP1pbd/EMSE3CgzQUcwRiNTNRZTAXC3QXioz52xhziI7NrSu71P
        LuwMuj7YtqjFdsFt57ho5O8iGXCmcwHdLvN4ADByRn4p4aMg59IK5aG8B+Btn0gz
        dJBTz8Px1LkdVpSitZPrZdpjDoYymSABfQ/oTvMSTffiiOC634EFCkJmr9Uc1M2C
        mX2LwtM/ZDVnpmY/hWjI3dNhEolvVl1TAQzfokoszJiFMSKPRJhF5SctdnBmzgDC
        GOuxdU1Jtrhj22CxvzRGoVFI1BrxNcDzg3fBBwIDAQABAoIBAG6cvNgVNvOUxbr/
        gxFb5vOzl1d1WSvAi8wESdWEMd0UqO91Q8XjGBAQ2XgIV8fwh+G0kqU60LqZcOpM
        IPKZ/7Gk3FsxCMnVjp8R9tFxkeBAJ6sdEKZpF4zEppVh1ztkjBVAa5iVbuwEhgH+
        a6RgfoYWK8lG9sV3WokUJnImXnmG1vAq55B1/M7FuboHKO/1raE7w3rnydqpGOlm
        rdTTR9VghuJSI+zcPy90k/tWxqQW5fohjmvdFp3Tjlu68Gz9wYgBzlBfOsE0Oo64
        ssMw0j2wAdbz6E3/g4w0k5j7c3UFECVyqfciY1u3CbXNAZz+UXvF6mgV6hGFsLha
        55T1SFECgYEA8ed76C56IIGAVz9n+QltdRFijZyZXDrrmp4m5wTrjBabG+0quZ5e
        CwYhr5J86G/HQiM/dVMlX8xUW7dLkJanLaeBaG+VA8VWvijcRRMG4CaRIeYquLCW
        kJSW9fgcH+0zr2GxKoxA81dDSgSmu0rz+JXVxBZrzRAEesCTxwwuwV8CgYEAxaKd
        osZDsqheY78/wDox3x8OVdkPgYtV7ckGXVA6YiNbFIS815Dtxun5RBjYC5AuLslu
        ml+B/N5B+ezdGPCd1Xo+aoAG4SWbqRRQ4YhbXjfCW5+ve9vHAPb0Lsnq6YzmjRRa
        n26QmLxlkXk9xs8eIH+yG4qEtOpwheqNDzzT2VkCgYAMAsheMOCTeJqcumM5NESh
        CWnxShM7Rxmnpa6czdu8KussqcvzR2+38Gf/xbA6AkLMf9+IvcYfSY/utd0korZO
        SADe5JtrgoLaEkFNlLJEsuWF313DqdDwANC2CcmrtCVa0ejwCeK3sl9+71gv+HrA
        nv/sKojTt7XhOmqb+Xjg1QKBgFDNwtupakZidm0b5YnHgVpzTR4maCOT/2cAGN0Q
        Dz7Oq8+A0eDk/YKlaOfBrJtVsLwqWVE+mVv0107C3Eb1IeMFXv2WKLnm8XS4vLTp
        Vkn4TDu/1zSxz/SCA6YZojUpCZ5G4yJqRy5bYL+QrYRabDvnWb/O66E4dRcbpd7E
        BO3JAoGBAKjGoOR90tzEtLrEvAYQ7C4hBaAEr5Q9qVTY8YX3Buu7IjOXnp+hPjM2
        NsvohmptLBEY+xFa+uM7I7yzlp3NeLNeM37UyCQiEjuyoTotN1hjRLiWUWi6KrYS
        1SYykNNYKIkR5x7VO2kGNs68zwiBCxllIqCKQZJeeJvctQVewYLs
        -----END RSA PRIVATE KEY-----

  - name: ops-manager-stable
    type: s3
    source:
      access_key_id: AKIAJEAGY2FWB7DEGFXQ
      secret_access_key: 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
      bucket: ert-concourse-products
      region_name: us-west-1
      private: true
      versioned_file: ops_manager_images/{{iaas_type}}/stable/ops_man_image

jobs:
  - name: claim-environment
    plan:
      - get: p-runtime
      - put: environment
        params:
          acquire: true
      - task: update-krafa
        file: p-runtime/ci/jobs/update-krafa.yml
        config:
          params:
            CLAIM_REASON: {{branch_name}}
            KRAFA_BASE_URL: http://krafa.cfapps.io
            KRAFA_USERNAME: releng
            KRAFA_PASSWORD: bet90onions


  - name: destroy-environment
    plan:
      - get: p-runtime
        trigger: true
        passed: [claim-environment]
      - get: environment
        trigger: true
        passed: [claim-environment]
      - task: destroy
        tags: [{{iaas_type}}]
        file: p-runtime/ci/jobs/destroy-environment.yml

  - name: deploy-ops-manager
    plan:
      - get: p-runtime
        trigger: true
        passed: [destroy-environment]
      - get: environment
        trigger: true
        passed: [destroy-environment]
      - aggregate:
        - get: ops-manager
          resource: ops-manager-stable
        - task: prepare
          tags: [{{iaas_type}}]
          file: p-runtime/ci/jobs/prepare-environment.yml
      - task: deploy
        tags: [{{iaas_type}}]
        file: p-runtime/ci/jobs/deploy-opsman.yml

  - name: configure-microbosh
    plan:
      - get: p-runtime
        trigger: true
        passed: [deploy-ops-manager]
      - get: environment
        trigger: true
        passed: [deploy-ops-manager]
      - task: configure
        tags: [{{iaas_type}}]
        file: p-runtime/ci/jobs/configure-microbosh.yml
        config:
          params:
            OPSMAN_VERSION: {{om_version}}

  - name: deploy-microbosh
    plan:
      - get: p-runtime
        trigger: true
        passed: [configure-microbosh]
      - get: environment
        trigger: true
        passed: [configure-microbosh]
      - task: deploy
        tags: [{{iaas_type}}]
        file: p-runtime/ci/jobs/deploy-microbosh.yml
        config:
          params:
            OPSMAN_VERSION: {{om_version}}
        ensure:
          task: get-install-log
          tags: [{{iaas_type}}]
          file: p-runtime/ci/jobs/get-install-log.yml
          config:
            params:
              OPSMAN_VERSION: {{om_version}}

  - name: build-runtime
    plan:
      - get: version
        params:
          bump: patch
          pre: build
      - put: version
        params:
          file: version/number
      - get: p-runtime
        trigger: true
        passed: [claim-environment]
      - task: build-product
        file: p-runtime/ci/jobs/build-pivotal.yml
      - put: ert-product
        params:
          from: build-product/ert.pivotal

  - name: upload-pivotal
    plan:
      - aggregate:
        - get: p-runtime
          trigger: true
          passed: [build-runtime, deploy-microbosh]
        - get: environment
          trigger: true
          passed: [deploy-microbosh]
        - get: ert-product
          trigger: true
          passed: [build-runtime]
      - task: upload-pivotal
        tags: [{{iaas_type}}]
        file: p-runtime/ci/jobs/upload-pivotal.yml
        config:
          params:
            OPSMAN_VERSION: {{om_version}}


  - name: configure-ert
    plan:
      - get: p-runtime
        trigger: true
        passed: [upload-pivotal]
      - get: environment
        trigger: true
        passed: [upload-pivotal]
      - task: configure-ert
        tags: [{{iaas_type}}]
        file: p-runtime/ci/jobs/configure-ert.yml
        config:
          params:
            ERT_VERSION: {{ert_version}}
            OPSMAN_VERSION: {{om_version}}

  - name: deploy-ert
    plan:
      - get: p-runtime
        trigger: true
        passed: [configure-ert]
      - get: environment
        trigger: true
        passed: [configure-ert]
      - task: deploy-ert
        tags: [{{iaas_type}}]
        file: p-runtime/ci/jobs/deploy-ert.yml
        config:
          params:
            OPSMAN_VERSION: {{om_version}}
        ensure:
          task: get-install-log
          tags: [{{iaas_type}}]
          file: p-runtime/ci/jobs/get-install-log.yml
          config:
            params:
              OPSMAN_VERSION: {{om_version}}

  - name: run-cats
    plan:
      - get: p-runtime
        trigger: true
        passed: [deploy-ert]
      - get: environment
        trigger: true
        passed: [deploy-ert]
      - task: run-cats
        tags: [{{iaas_type}}]
        file: p-runtime/ci/jobs/run-cats.yml
        config:
          params:
            OPSMAN_VERSION: {{om_version}}

  - name: destroy-environment-final
    plan:
     - get: p-runtime
       passed: [run-cats]
     - get: environment
       passed: [run-cats]
     - task: destroy
       tags: [{{iaas_type}}]
       file: p-runtime/ci/jobs/destroy-environment.yml

  - name: release-environment
    plan:
      - get: p-runtime
        trigger: true
        passed: [destroy-environment-final]
      - get: environment
        trigger: true
        passed: [destroy-environment-final]
      - put: environment
        params:
          release: environment

groups:
  - name: {{branch_name}}
    jobs:
    - claim-environment
    - destroy-environment
    - deploy-ops-manager
    - configure-microbosh
    - deploy-microbosh
    - build-runtime
    - upload-pivotal
    - configure-ert
    - deploy-ert
    - run-cats
    - destroy-environment-final
    - release-environment
