jobs:
  - name: claim-environment-vsphere-upgrade
    plan:
        - get: p-runtime
          trigger: true
          passed: [kickoff]
        - put: environment-vsphere
          resource: environment-vsphere
          params:
            acquire: true

  - name: destroy-environment-vsphere-upgrade
    plan:
      - get: p-runtime
        trigger: true
        passed: [claim-environment-vsphere-upgrade]
      - get: environment
        resource: environment-vsphere
        trigger: true
        passed: [claim-environment-vsphere-upgrade]
      - task: destroy
        tags: [vsphere]
        file: p-runtime/ci/jobs/destroy-environment.yml

  - name: deploy-ops-manager-initial-vsphere-upgrade
    plan:
      - get: p-runtime
        trigger: true
        passed: [destroy-environment-vsphere-upgrade]
      - get: environment
        resource: environment-vsphere
        trigger: true
        passed: [destroy-environment-vsphere-upgrade]
      - aggregate:
        - get: ops-manager
          resource: initial-ops-manager-vsphere
        - task: prepare
          tags: [vsphere]
          file: p-runtime/ci/jobs/prepare-environment.yml
      - task: deploy
        tags: [vsphere]
        file: p-runtime/ci/jobs/deploy-opsman.yml

  - name: configure-microbosh-initial-vsphere-upgrade
    plan:
      - get: p-runtime
        trigger: true
        passed: [deploy-ops-manager-initial-vsphere-upgrade]
      - get: environment
        resource: environment-vsphere
        trigger: true
        passed: [deploy-ops-manager-initial-vsphere-upgrade]
      - task: configure
        tags: [vsphere]
        file: p-runtime/ci/jobs/configure-microbosh.yml
        config:
          params:
            OPSMAN_VERSION: &om_initial_version 1.4

  - name: deploy-microbosh-initial-vsphere-upgrade
    plan:
      - get: p-runtime
        trigger: true
        passed: [configure-microbosh-initial-vsphere-upgrade]
      - get: environment
        resource: environment-vsphere
        trigger: true
        passed: [configure-microbosh-initial-vsphere-upgrade]
      - task: deploy
        tags: [vsphere]
        file: p-runtime/ci/jobs/deploy-microbosh.yml
        config:
          params:
            OPSMAN_VERSION: *om_initial_version

  - name: upload-pivotal-initial-vsphere-upgrade
    plan:
      - get: p-runtime
        trigger: true
        passed: [deploy-microbosh-initial-vsphere-upgrade]
      - get: environment
        resource: environment-vsphere
        trigger: true
        passed: [deploy-microbosh-initial-vsphere-upgrade]
      - get: ert-product
        resource: initial-ert-product
        trigger: true
      - task: upload
        tags: [vsphere]
        file: p-runtime/ci/jobs/upload-pivotal.yml
        config:
          params:
            OPSMAN_VERSION: *om_initial_version

  - name: configure-ert-initial-vsphere-upgrade
    plan:
      - get: p-runtime
        trigger: true
        passed: [upload-pivotal-initial-vsphere-upgrade]
      - get: environment
        resource: environment-vsphere
        trigger: true
        passed: [upload-pivotal-initial-vsphere-upgrade]
      - task: configure-ert
        tags: [vsphere]
        file: p-runtime/ci/jobs/configure-ert.yml
        config:
          params:
            ERT_VERSION: 1.4
            OPSMAN_VERSION: *om_initial_version

  - name: deploy-ert-initial-vsphere-upgrade
    plan:
      - get: p-runtime
        trigger: true
        passed: [configure-ert-initial-vsphere-upgrade]
      - get: environment
        resource: environment-vsphere
        trigger: true
        passed: [configure-ert-initial-vsphere-upgrade]
      - task: deploy-ert
        tags: [vsphere]
        file: p-runtime/ci/jobs/deploy-ert.yml
        config:
          params:
            OPSMAN_VERSION: *om_initial_version

  - name: export-installation-vsphere-upgrade
    plan:
      - get: p-runtime
        trigger: true
        passed: [deploy-ert-initial-vsphere-upgrade]
      - get: environment
        resource: environment-vsphere
        trigger: true
        passed: [deploy-ert-initial-vsphere-upgrade]
      - task: export-installation
        tags: [vsphere]
        file: p-runtime/ci/jobs/export-installation.yml
        config:
          params:
            OPSMAN_VERSION: *om_initial_version
      - put: exported-installation-vsphere
        params:
          from: p-runtime/installation.zip

  - name: destroy-opsman-vsphere-upgrade
    plan:
      - get: p-runtime
        trigger: true
        passed: [export-installation-vsphere-upgrade]
      - get: environment
        resource: environment-vsphere
        trigger: true
        passed: [export-installation-vsphere-upgrade]
      - task: destroy-opsman-vsphere-upgrade
        tags: [vsphere]
        file: p-runtime/ci/jobs/destroy-opsman.yml

  - name: deploy-opsman-vsphere-upgrade
    plan:
      - aggregate:
        - get: p-runtime
          trigger: true
          passed: [destroy-opsman-vsphere-upgrade]
        - get: environment
          resource: environment-vsphere
          trigger: true
          passed: [destroy-opsman-vsphere-upgrade]
        - get: ops-manager
          resource: ops-manager-stable-vsphere
      - task: deploy
        tags: [vsphere]
        file: p-runtime/ci/jobs/deploy-opsman.yml

  - name: import-installation-vsphere-upgrade
    plan:
      - get: p-runtime
        trigger: true
        passed: [export-installation-vsphere-upgrade,deploy-opsman-vsphere-upgrade]
      - get: environment
        resource: environment-vsphere
        trigger: true
        passed: [export-installation-vsphere-upgrade,deploy-opsman-vsphere-upgrade]
      - get: exported-installation
        resource: exported-installation-vsphere
        trigger: true
        passed: [export-installation-vsphere-upgrade]
      - task: import-installation
        tags: [vsphere]
        file: p-runtime/ci/jobs/import-installation.yml
        config:
          params:
            OPSMAN_VERSION: &om_version 1.5

  - name: upgrade-pivotal-vsphere-upgrade
    plan:
      - aggregate:
        - get: p-runtime
          trigger: true
          passed: [import-installation-vsphere-upgrade]
        - get: environment
          resource: environment-vsphere
          trigger: true
          passed: [import-installation-vsphere-upgrade]
        - get: ert-product
          trigger: true
          passed: [build-runtime]
      - task: upgrade-pivotal-vsphere
        tags: [vsphere]
        file: p-runtime/ci/jobs/upgrade-pivotal.yml
        config:
          params:
            OPSMAN_VERSION: *om_version

  - name: configure-ert-vsphere-upgrade
    plan:
      - get: p-runtime
        trigger: true
        passed: [upgrade-pivotal-vsphere-upgrade]
      - get: environment
        resource: environment-vsphere
        trigger: true
        passed: [upgrade-pivotal-vsphere-upgrade]
      - task: configure-ert-vsphere
        tags: [vsphere]
        file: p-runtime/ci/jobs/configure-ert.yml
        config:
          params:
            ERT_VERSION: 1.5
            OPSMAN_VERSION: *om_version

  - name: deploy-ert-vsphere-upgrade
    plan:
      - get: p-runtime
        trigger: true
        passed: [configure-ert-vsphere-upgrade]
      - get: environment
        resource: environment-vsphere
        trigger: true
        passed: [configure-ert-vsphere-upgrade]
      - task: deploy-ert
        tags: [vsphere]
        file: p-runtime/ci/jobs/deploy-ert.yml
        config:
          params:
            OPSMAN_VERSION: *om_version

  - name: run-cats-vsphere-upgrade
    plan:
      - get: p-runtime
        trigger: true
        passed: [deploy-ert-vsphere-upgrade]
      - get: environment
        resource: environment-vsphere
        trigger: true
        passed: [deploy-ert-vsphere-upgrade]
      - task: run-cats
        tags: [vsphere]
        file: p-runtime/ci/jobs/run-cats.yml

  - name: release-environment-vsphere-upgrade
    plan:
      - get: p-runtime
        passed: [run-cats-vsphere-upgrade]
      - get: environment
        resource: environment-vsphere
        passed: [run-cats-vsphere-upgrade]
      - put: environment-vsphere
        params:
          release: environment-vsphere
