jobs:
  - name: claim-environment-internetless
    plan:
      - get: p-runtime
        trigger: true
        passed: [kickoff]
      - put: environment
        resource: environment-internetless
        params:
          acquire: true

  - name: destroy-environment-internetless
    plan:
      - get: p-runtime
        trigger: true
        passed: [claim-environment-internetless]
      - get: environment
        resource: environment-internetless
        trigger: true
        passed: [claim-environment-internetless]
      - task: destroy
        tags: [vsphere]
        file: p-runtime/ci/jobs/destroy-environment.yml

  - name: deploy-ops-manager-internetless
    plan:
      - get: p-runtime
        trigger: true
        passed: [destroy-environment-internetless]
      - get: environment
        resource: environment-internetless
        trigger: true
        passed: [destroy-environment-internetless]
      - aggregate:
        - get: ops-manager
          resource: ops-manager-stable-vsphere
        - task: prepare
          tags: [vsphere]
          file: p-runtime/ci/jobs/prepare-environment.yml
      - task: deploy
        tags: [vsphere]
        file: p-runtime/ci/jobs/deploy-opsman.yml
  - name: configure-microbosh-internetless
    plan:
      - get: p-runtime
        trigger: true
        passed: [deploy-ops-manager-internetless]
      - get: environment
        resource: environment-internetless
        trigger: true
        passed: [deploy-ops-manager-internetless]
      - task: configure
        tags: [vsphere]
        file: p-runtime/ci/jobs/configure-microbosh.yml
        config:
          params:
            OPSMAN_VERSION: &om_version 1.5
  - name: deploy-microbosh-internetless
    plan:
      - get: p-runtime
        trigger: true
        passed: [configure-microbosh-internetless]
      - get: environment
        resource: environment-internetless
        trigger: true
        passed: [configure-microbosh-internetless]
      - task: deploy
        tags: [vsphere]
        file: p-runtime/ci/jobs/deploy-microbosh.yml
        config:
          params:
            OPSMAN_VERSION: *om_version

  - name: upload-pivotal-internetless
    plan:
      - aggregate:
        - get: p-runtime
          trigger: true
          passed: [build-runtime, deploy-microbosh-internetless]
        - get: environment
          resource: environment-internetless
          trigger: true
          passed: [deploy-microbosh-internetless]
        - get: ert-product
          trigger: true
          passed: [build-runtime]
      - task: upload-pivotal
        tags: [vsphere]
        file: p-runtime/ci/jobs/upload-pivotal.yml
        config:
          params:
            OPSMAN_VERSION: *om_version

  - name: configure-ert-internetless
    plan:
      - get: p-runtime
        trigger: true
        passed: [upload-pivotal-internetless]
      - get: environment
        resource: environment-internetless
        trigger: true
        passed: [upload-pivotal-internetless]
      - task: configure-ert
        tags: [vsphere]
        file: p-runtime/ci/jobs/configure-ert.yml
        config:
          params:
            ERT_VERSION: 1.5
            OPSMAN_VERSION: *om_version

  - name: import-stemcell-internetless
    plan:
      - get: p-runtime
        trigger: true
        passed: [configure-ert-internetless]
      - get: environment
        resource: environment-internetless
        trigger: true
        passed: [configure-ert-internetless]
      - get: stemcell
        resource: stemcell-1.5.1-vsphere
      - task: import-stemcell
        tags: [vsphere]
        file: p-runtime/ci/jobs/import-stemcell.yml
        config:
          params:
            OPSMAN_VERSION: *om_version
            PRODUCT_NAME: cf

  - name: deploy-ert-internetless
    plan:
      - get: p-runtime
        trigger: true
        passed: [import-stemcell-internetless]
      - get: environment
        resource: environment-internetless
        trigger: true
        passed: [import-stemcell-internetless]
      - task: deploy-ert
        tags: [vsphere]
        file: p-runtime/ci/jobs/deploy-ert.yml
        config:
          params:
            OPSMAN_VERSION: *om_version

  - name: run-cats-internetless
    plan:
      - get: p-runtime
        trigger: true
        passed: [deploy-ert-internetless]
      - get: environment
        resource: environment-internetless
        trigger: true
        passed: [deploy-ert-internetless]
      - task: run-cats
        tags: [vsphere]
        file: p-runtime/ci/jobs/run-cats.yml
        config:
          params:
            OPSMAN_VERSION: *om_version

  - name: release-environment-internetless
    plan:
      - get: p-runtime
        passed: [run-cats-internetless]
      - get: environment
        resource: environment-internetless
        passed: [run-cats-internetless]
      - put: environment-internetless
        params:
          release: environment
