Metrics/LineLength:
  Max: 130
  Exclude:
  - Gemfile

Style/Documentation:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 22

Metrics/ClassLength:
  CountComments: false  # count full line comments?
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 15
