---
name: cf
metadata_version: '2.0'
provides_product_versions:
- name: cf
  version: $( version )
product_version: $( version )
minimum_version_for_upgrade: 2.0.0
label: $( variable "label" )
description:
  Gives developers the ability to push apps on a dynamically-configured software stack
icon_image: $( icon )
rank: 90
serial: false

stemcell_criteria: $( stemcell )

releases:
- $( release "backup-and-restore-sdk" )
- $( release "binary-offline-buildpack" )
- $( release "bosh-dns-aliases" )
- $( release "bosh-system-metrics-forwarder" )
- $( release "capi" )
- $( release "cf-autoscaling" )
- $( release "cf-backup-and-restore" )
- $( release "cf-mysql" )
- $( release "cf-networking" )
- $( release "cf-smoke-tests" )
- $( release "cf-syslog-drain" )
- $( release "cflinuxfs2" )
- $( release "consul" )
- $( release "credhub" )
- $( release "diego" )
- $( release "dotnet-core-offline-buildpack" )
- $( release "garden-runc" )
- $( release "go-offline-buildpack" )
- $( release "grootfs" )
- $( release "haproxy" )
- $( release "java-offline-buildpack" )
- $( release "loggregator" )
- $( release "mysql-backup" )
- $( release "mysql-monitoring" )
- $( release "nats" )
- $( release "nfs-volume" )
- $( release "nodejs-offline-buildpack" )
- $( release "notifications" )
- $( release "notifications-ui" )
- $( release "php-offline-buildpack" )
- $( release "pivotal-account" )
- $( release "push-apps-manager-release" )
- $( release "push-usage-service-release" )
- $( release "python-offline-buildpack" )
- $( release "routing" )
- $( release "ruby-offline-buildpack" )
- $( release "service-backup" )
- $( release "staticfile-offline-buildpack" )
- $( release "statsd-injector" )
- $( release "syslog-migration" )
- $( release "uaa" )

form_types:
- $( form "domains" )
- $( form "networking" )
- $( form "app_containers" )
- $( form "application_dev_controls" )
- $( form "application_security_groups" )
- $( form "sso" )
- $( form "uaa" )
- $( form "credhub" )
- $( form "system_database" )
- $( form "mysql_config" )
- $( form "system_blobstore" )
- $( form "system_logging" )
- $( form "generic_white_label_config" )
- $( form "apps_manager_config" )
- $( form "smtp_config" )
- $( form "cloud_controller" )
- $( form "smoke_tests" )
- $( form "experimental_features" )

job_types:
- $( instance_group "database" ) # SRT only
- $( instance_group "blobstore" ) # SRT only
- $( instance_group "control" ) # SRT only
- $( instance_group "compute" ) # SRT only
- $( instance_group "consul_server" ) # ERT only
- $( instance_group "nats" ) # ERT only
- $( instance_group "nfs_server" ) # ERT only
- $( instance_group "mysql_proxy" ) # ERT only
- $( instance_group "mysql" ) # ERT only
- $( instance_group "backup-prepare" ) # ERT & SRT
- $( instance_group "diego_database" ) # ERT only
- $( instance_group "uaa" ) # ERT only
- $( instance_group "cloud_controller" ) # ERT only
- $( instance_group "ha_proxy" ) # ERT & SRT
- $( instance_group "router" ) # ERT & SRT
- $( instance_group "mysql_monitor" ) # ERT & SRT
- $( instance_group "clock_global" ) # ERT only
- $( instance_group "cloud_controller_worker" ) # ERT only
- $( instance_group "diego_brain" ) # ERT only
- $( instance_group "diego_cell" ) # ERT only
- $( instance_group "loggregator_trafficcontroller" ) # ERT only
- $( instance_group "syslog_adapter" ) # ERT only
- $( instance_group "syslog_scheduler" ) # ERT only
- $( instance_group "doppler" ) # ERT only
- $( instance_group "tcp_router" ) # ERT & SRT
- $( instance_group "credhub" ) # ERT only
- $( instance_group "push-apps-manager" ) # ERT & SRT

property_blueprints:
- $( property "cc_api_rate_limit" )
- $( property "cloud_controller_client_cert" )
- $( property "cloud_controller_mutual_cert" )
- $( property "consul_agent_cert" )
- $( property "consul_server_cert" )
- $( property "credhub_key_encryption_passwords" )
- $( property "credhub_tls" )
- $( property "secure_service_instance_credentials" )
- $( property "credhub_database_name" )
- $( property "credhub_database" )
- $( property "auctioneer_client_cert" )
- $( property "auctioneer_server_cert" )
- $( property "bbs_client_cert" )
- $( property "bbs_server_cert" )
- $( property "loggregator_client_cert" )
- $( property "rep_client_cert" )
- $( property "rep_server_cert" )
- $( property "tps_client_cert" )
- $( property "nfs_volume_driver" )
- $( property "push_apps_manager_company_name" )
- $( property "push_apps_manager_accent_color" )
- $( property "push_apps_manager_global_wrapper_bg_color" )
- $( property "push_apps_manager_global_wrapper_text_color" )
- $( property "push_apps_manager_global_wrapper_header_content" )
- $( property "push_apps_manager_global_wrapper_footer_content" )
- $( property "push_apps_manager_logo" )
- $( property "push_apps_manager_square_logo" )
- $( property "push_apps_manager_favicon" )
- $( property "push_apps_manager_footer_text" )
- $( property "push_apps_manager_footer_links" )
- $( property "push_apps_manager_nav_links" )
- $( property "push_apps_manager_product_name" )
- $( property "push_apps_manager_marketplace_name" )
- $( property "push_apps_manager_enable_invitations" )
- $( property "push_apps_manager_display_plan_prices" )
- $( property "push_apps_manager_currency_lookup" )
- $( property "garden_disk_cleanup" )
- $( property "enable_grootfs" )
- $( property "garden_image_plugin" )
- $( property "garden_image_plugin_empty" )
- $( property "garden_image_plugin_extra_args" )
- $( property "garden_image_plugin_empty_args" )
- $( property "rep_preloaded_rootfses_garden" )
- $( property "rep_preloaded_rootfses_grootfs" )
- $( property "logger_endpoint_port" )
- $( property "syslog_host" )
- $( property "syslog_port" )
- $( property "syslog_rule" )
- $( property "syslog_protocol" )
- $( property "system_logging" )
- $( property "syslog_tls" )
- $( property "networking_poe_ssl_certs" )
- $( property "routing_custom_ca_certificates" )
- $( property "routing_disable_http" )
- $( property "routing_minimum_tls_version" )
- $( property "routing_tls_termination" )
- $( property "router_client_cert_validation" )
- $( property "gorouter_ssl_ciphers" )
- $( property "haproxy_client_certificate" )
- $( property "haproxy_forward_tls" )
- $( property "haproxy_max_buffer_size" )
- $( property "haproxy_ssl_ciphers" )
- $( property "tcp_routing" )
- $( property "router_backend_max_conn" )
- $( property "route_services" )
- $( property "network_policy_server_cert" )
- $( property "network_policy_agent_cert" )
- $( property "container_networking" )
- $( property "container_networking_interface_plugin" )
- $( property "cf_networking_enable_space_developer_self_service" )
- $( property "security_acknowledgement" )
- $( property "cf_dial_timeout_in_seconds" )
- $( property "smoke_tests" )
- $( property "smtp_from" )
- $( property "smtp_address" )
- $( property "smtp_port" )
- $( property "smtp_credentials" )
- $( property "smtp_enable_starttls_auto" )
- $( property "smtp_auth_mechanism" )
- $( property "smtp_crammd5_secret" )
- $( property "system_blobstore" )
- $( property "account_database_name" )
- $( property "app_usage_service_database_name" )
- $( property "autoscale_database_name" )
- $( property "ccdb_database_name" )
- $( property "diego_database_name" )
- $( property "locket_database_name" )
- $( property "networkpolicyserver_database_name" )
- $( property "notifications_database_name" )
- $( property "routing_database_name" )
- $( property "silk_database_name" )
- $( property "nfsvolume_database_name" )
- $( property "system_db_link" )
- $( property "system_database" )
- $( property "mysql_backups" )
- $( property "mysql_activity_logging" )
- $( property "tile_name" )
- $( property "uaa" )
- $( property "saml_signature_algorithm" )
- $( property "uaa_database_name" )
- $( property "uaa_database" )

runtime_configs:
- $( runtime_config "bosh-dns-aliases" )
- $( runtime_config "silk-cni" )

variables:
- name: /cf/diego-instance-identity-root-ca
  type: certificate
  options:
    common_name: 'Diego Instance Identity Root CA'
    is_ca: true
    duration: 1095

- name: /cf/diego-instance-identity-intermediate-ca
  type: certificate
  options:
    common_name: 'Diego Instance Identity Intermediate CA'
    is_ca: true
    duration: 730
    ca: /cf/diego-instance-identity-root-ca
    key_usage:
    - key_cert_sign

- name: app-usage-db-credentials
  type: user
  options:
    username: app_usage

- name: autoscale-db-credentials
  type: user

- name: backup-prepare-backup-encryption-key
  type: password

- name: cc-db-credentials
  type: user

- name: cloud-controller-bulk-api-credentials
  type: user
  options:
    username: bulk_api

- name: cloud-controller-internal-api-user-credentials
  type: user

- name: cloud-controller-staging-upload-credentials
  type: user
  options:
    username: staging_upload_user

- name: consul-encryption-key
  type: password

- name: credhub-db-credentials
  type: user

- name: deploy-autoscaling-broker-credentials
  type: user

- name: deploy-autoscaling-encryption-key
  type: password

- name: deploy-notifications-encryption-key
  type: password

- name: diego-db-bbs-encryption-passphrase
  type: password

- name: diego-db-credentials
  type: user

- name: locket-db-credentials
  type: user

- name: mysql-admin-credentials
  type: user
  options:
    username: root

- name: mysql-backup-server-db-credentials
  type: user

- name: mysql-bootstrap-db-credentials
  type: user

- name: mysql-cluster-health-credentials
  type: user
  options:
    username: cluster-health-logger

- name: mysql-diag-agent-db-credentials
  type: user

- name: mysql-galera-sidecar-credentials
  type: user
  options:
    username: galera-healthcheck

- name: mysql-metrics-db-credentials
  type: user

- name: mysql-monitor-db-credentials
  type: user

- name: mysql-proxy-dashboard-credentials
  type: user
  options:
    username: admin

- name: nats-credentials
  type: user
  options:
    username: nats

- name: network-policy-server-db-credentials
  type: user

- name: nfs-broker-push-db-credentials
  type: user

- name: nfs-server-blobstore-secret
  type: password

- name: nfs-volume-db-credentials
  type: user

- name: notifications-db-credentials
  type: user

- name: pivotal-account-db-credentials
  type: user

- name: push-pivotal-account-encryption-key
  type: password

- name: push-usage-service-secret-token
  type: password

- name: router-route-services-secret
  type: password

- name: router-status-credentials
  type: user
  options:
    username: router_status

- name: routing-db-credentials
  type: user

- name: silk-db-credentials
  type: user

- name: uaa-db-credentials
  type: user

- name: webdav-blobstore-credentials
  type: user
  options:
    username: blobstore

post_deploy_errands:
  - name: smoke_tests
    colocated: true
    run_default: true
    instances:
      - $( variable "errand_instance_group" )
    label: Smoke Test Errand
    description: Runs Smoke Tests against your Application Service installation
  - name: push-usage-service
    colocated: true
    run_default: true
    instances:
      - $( variable "errand_instance_group" )
    label: Usage Service Errand
    description: Pushes the Pivotal Usage Service application to your Application Service installation. Pivotal Apps Manager depends on this application.
  - name: push-apps-manager
    colocated: true
    run_default: true
    instances:
      - $( variable "errand_instance_group" )
    label: Apps Manager Errand
    description: Pushes the Pivotal Apps Manager application to your Application Service installation
  - name: deploy-notifications
    colocated: true
    run_default: true
    instances:
      - $( variable "errand_instance_group" )
    label: Notifications Errand
    description: |
      Pushes the Pivotal Notifications application to your Application Service installation
  - name: deploy-notifications-ui
    colocated: true
    run_default: true
    instances:
      - $( variable "errand_instance_group" )
    label: Notifications UI Errand
    description: Pushes the Notifications UI component to your Application Service installation
  - name: push-pivotal-account
    colocated: true
    run_default: true
    instances:
      - $( variable "errand_instance_group" )
    label: Pivotal Account Errand
    description: Pushes the Pivotal Account application to your Application Service installation
  - name: deploy-autoscaling
    colocated: true
    run_default: true
    instances:
      - $( variable "errand_instance_group" )
    label: Autoscaling Errand
    description: Pushes the Pivotal App Autoscaling application to your Application Service installation
  - name: register-broker
    colocated: true
    run_default: true
    instances:
      - $( variable "errand_instance_group" )
    label: Autoscaling Registration Errand
    description: Registers the Autoscaling Service Broker
  - name: nfsbrokerpush
    colocated: true
    run_default: true
    instances:
      - $( variable "errand_instance_group" )
    label: NFS Broker Errand
    description: Pushes the NFS Broker application to your Application Service installation

install_time_verifiers:
- name: Verifiers::WildcardDomainVerifier
  ignorable: true
  properties:
    domain: .cloud_controller.system_domain
- name: Verifiers::WildcardDomainVerifier
  ignorable: true
  properties:
    domain: .cloud_controller.apps_domain
- name: Verifiers::SsoUrlVerifier
  properties:
    url: .properties.uaa.saml.sso_url
- name: Verifiers::BlobstoreVerifier
  ignorable: true
  properties:
    endpoint: .properties.system_blobstore.external.endpoint
    access_key_id: .properties.system_blobstore.external.access_key
    secret_access_key: .properties.system_blobstore.external.secret_key
    bucket_name: .properties.system_blobstore.external.buildpacks_bucket
    region: .properties.system_blobstore.external.region
    signature_version: .properties.system_blobstore.external.signature_version
- name: Verifiers::BlobstoreVerifier
  ignorable: true
  properties:
    endpoint: .properties.system_blobstore.external.endpoint
    access_key_id: .properties.system_blobstore.external.access_key
    secret_access_key: .properties.system_blobstore.external.secret_key
    bucket_name: .properties.system_blobstore.external.droplets_bucket
    region: .properties.system_blobstore.external.region
    signature_version: .properties.system_blobstore.external.signature_version
- name: Verifiers::BlobstoreVerifier
  ignorable: true
  properties:
    endpoint: .properties.system_blobstore.external.endpoint
    access_key_id: .properties.system_blobstore.external.access_key
    secret_access_key: .properties.system_blobstore.external.secret_key
    bucket_name: .properties.system_blobstore.external.packages_bucket
    region: .properties.system_blobstore.external.region
    signature_version: .properties.system_blobstore.external.signature_version
- name: Verifiers::BlobstoreVerifier
  ignorable: true
  properties:
    endpoint: .properties.system_blobstore.external.endpoint
    access_key_id: .properties.system_blobstore.external.access_key
    secret_access_key: .properties.system_blobstore.external.secret_key
    bucket_name: .properties.system_blobstore.external.resources_bucket
    region: .properties.system_blobstore.external.region
    signature_version: .properties.system_blobstore.external.signature_version
- name: Verifiers::MysqlDatabaseVerifier
  ignorable: true
  properties:
    host: .properties.system_database.external.host
    port: .properties.system_database.external.port
    username: .properties.system_database.external.account_username
    password: .properties.system_database.external.account_password
    database: .properties.account_database_name
- name: Verifiers::MysqlDatabaseVerifier
  ignorable: true
  properties:
    host: .properties.system_database.external.host
    port: .properties.system_database.external.port
    username: .properties.system_database.external.app_usage_service_username
    password: .properties.system_database.external.app_usage_service_password
    database: .properties.app_usage_service_database_name
- name: Verifiers::MysqlDatabaseVerifier
  ignorable: true
  properties:
    host: .properties.system_database.external.host
    port: .properties.system_database.external.port
    username: .properties.system_database.external.autoscale_username
    password: .properties.system_database.external.autoscale_password
    database: .properties.autoscale_database_name
- name: Verifiers::MysqlDatabaseVerifier
  ignorable: true
  properties:
    host: .properties.system_database.external.host
    port: .properties.system_database.external.port
    username: .properties.system_database.external.ccdb_username
    password: .properties.system_database.external.ccdb_password
    database: .properties.ccdb_database_name
- name: Verifiers::MysqlDatabaseVerifier
  ignorable: true
  properties:
    host: .properties.system_database.external.host
    port: .properties.system_database.external.port
    username: .properties.system_database.external.diego_username
    password: .properties.system_database.external.diego_password
    database: .properties.diego_database_name
- name: Verifiers::MysqlDatabaseVerifier
  ignorable: true
  properties:
    host: .properties.system_database.external.host
    port: .properties.system_database.external.port
    username: .properties.system_database.external.locket_username
    password: .properties.system_database.external.locket_password
    database: .properties.locket_database_name
- name: Verifiers::MysqlDatabaseVerifier
  ignorable: true
  properties:
    host: .properties.system_database.external.host
    port: .properties.system_database.external.port
    username: .properties.system_database.external.networkpolicyserver_username
    password: .properties.system_database.external.networkpolicyserver_password
    database: .properties.networkpolicyserver_database_name
- name: Verifiers::MysqlDatabaseVerifier
  ignorable: true
  properties:
    host: .properties.system_database.external.host
    port: .properties.system_database.external.port
    username: .properties.system_database.external.nfsvolume_username
    password: .properties.system_database.external.nfsvolume_password
    database: .properties.nfsvolume_database_name
- name: Verifiers::MysqlDatabaseVerifier
  ignorable: true
  properties:
    host: .properties.system_database.external.host
    port: .properties.system_database.external.port
    username: .properties.system_database.external.notifications_username
    password: .properties.system_database.external.notifications_password
    database: .properties.notifications_database_name
- name: Verifiers::MysqlDatabaseVerifier
  ignorable: true
  properties:
    host: .properties.system_database.external.host
    port: .properties.system_database.external.port
    username: .properties.system_database.external.routing_username
    password: .properties.system_database.external.routing_password
    database: .properties.routing_database_name
- name: Verifiers::MysqlDatabaseVerifier
  ignorable: true
  properties:
    host: .properties.system_database.external.host
    port: .properties.system_database.external.port
    username: .properties.system_database.external.silk_username
    password: .properties.system_database.external.silk_password
    database: .properties.silk_database_name
- name: Verifiers::MysqlDatabaseVerifier
  ignorable: true
  properties:
    host: .properties.uaa_database.external.host
    port: .properties.uaa_database.external.port
    username: .properties.uaa_database.external.uaa_username
    password: .properties.uaa_database.external.uaa_password
    database: .properties.uaa_database_name
