---
name: pas-windows
metadata_version: '2.2'
provides_product_versions:
- name: pas-windows
  version: $( version )
product_version: $( version )
minimum_version_for_upgrade: 2.1.0
requires_product_versions:
- name: cf
  version: "~> 2.2.0"
label: "Pivotal Application Service for Windows"
description: "Gives developers the ability to push apps to compute instances powered by the .NET Framework and the Windows® Operating System"
icon_image: $( icon )
rank: 88
serial: false

kiln_metadata:
  metadata_git_sha: $( variable "metadata-git-sha" )

stemcell_criteria: $( stemcell )

releases:
- $( release "consul" )
- $( release "diego" )
- $( release "event_log" )
- $( release "garden-runc" )
- $( release "hwc-offline-buildpack" )
- $( release "loggregator" )
- $( release "winc" )
- $( release "windows-utilities" )

form_types:
- $( form "vm_options" )
- $( form "application_containers" )
- $( form "system_logging" )

job_types:
- $( instance_group "windows_diego_cell" )

property_blueprints:
- $( property "bbs_client_cert" )
- $( property "bosh_ssh_enabled" )
- $( property "kms" )
- $( property "loggregator_client_cert" )
- $( property "metron_tls_cert" )
- $( property "rdp_enabled" )
- $( property "rep_server_cert" )
- $( property "rep_server_cert_v2" )
- $( property "system_logging" )
- $( property "windows_admin_password" )

post_deploy_errands:
  - name: install-hwc-buildpack
    colocated: true
    run_default: true
    instances:
      - windows_diego_cell/first
    label: Install HWC Buildpack Errand
    description: Install the HWC buildpack to your Elastic Runtime for Windows installation

install_time_verifiers: []
