---
name: p-isolation-segment
metadata_version: '2.5' # When a 2.6 Ops Manager appears, this value should be updated to be equal to the product version
provides_product_versions:
- name: p-isolation-segment
  version: $( version )
product_version: $( version )
minimum_version_for_upgrade: 2.5.0
requires_product_versions:
- name: cf
  version: "~> 2.6.0"
label: $( variable "label" )
description: "Gives developers the ability to push apps to a dedicated set of compute instances."
icon_image: $( icon )
rank: 89
serial: false

kiln_metadata:
  metadata_git_sha: $( variable "metadata-git-sha" )

stemcell_criteria: $( stemcell )

releases:
- $( release "bpm" )
- $( release "cf-networking" )
- $( release "cflinuxfs3" )
- $( release "diego" )
- $( release "garden-runc" )
- $( release "haproxy" )
- $( release "loggregator" )
- $( release "loggregator-agent" )
- $( release "mapfs" )
- $( release "nfs-volume" )
- $( release "routing" )
- $( release "silk" )
- $( release "smb-volume" )
- $( release "syslog" )

form_types:
- $( form "networking" )
- $( form "application_containers" )
- $( form "system_logging" )
- $( form "advanced_features" )

job_types:
- $( instance_group "isolated_ha_proxy" )
- $( instance_group "isolated_router" )
- $( instance_group "isolated_diego_cell" )

property_blueprints:
- $( property "bbs_client_cert" )
- $( property "cf_networking_search_domains" )
- $( property "container_networking" )
- $( property "enable_silk_policy_enforcement" )
- $( property "enable_smb_volume_driver" )
- $( property "garden_disk_cleanup" )
- $( property "gorouter_ssl_ciphers" )
- $( property "haproxy_client_cert_validation" )
- $( property "haproxy_client_certificate" )
- $( property "haproxy_forward_tls" )
- $( property "haproxy_hsts_support" )
- $( property "haproxy_max_buffer_size" )
- $( property "haproxy_ssl_ciphers" )
- $( property "loggregator_client_cert" )
- $( property "loggregator_agent_tls_cert" )
- $( property "networking_poe_ssl_certs" )
- $( property "networking_point_of_entry" )
- $( property "nfs_volume_driver" )
- $( property "rep_server_cert" )
- $( property "rep_server_cert_v2" )
- $( property "route_integrity" )
- $( property "router_backend_max_conn" )
- $( property "router_client_cert_validation" )
- $( property "router_enable_proxy" )
- $( property "router_headers_remove_if_specified" )
- $( property "router_keepalive_connections" )
- $( property "routing_backends_client_cert_with_san" )
- $( property "routing_custom_ca_certificates" )
- $( property "routing_disable_http" )
- $( property "routing_log_client_ips" )
- $( property "routing_minimum_tls_version" )
- $( property "routing_table_sharding_mode" )
- $( property "routing_tls_termination" )
- $( property "service_discovery_client_tls" )
- $( property "skip_cert_verify" )
- $( property "system_logging" )

variables:
- name: router-route-services-secret
  type: password

- name: diego-instance-identity-intermediate-ca-2018
  type: certificate
  options:
    common_name: 'Diego Instance Identity Intermediate CA'
    is_ca: true
    duration: 730
    ca: /cf/diego-instance-identity-root-ca
    key_usage:
    - key_cert_sign

post_deploy_errands: []

install_time_verifiers: []
