---
name: pas-windows
metadata_version: '2.4'
provides_product_versions:
- name: pas-windows
  version: $( version )
product_version: $( version )
minimum_version_for_upgrade: 2.2.0
requires_product_versions:
- name: cf
  version: "~> 2.6.0"
label: $( variable "label" )
description: "Gives developers the ability to push apps to compute instances powered by the .NET Framework and the Windows® Operating System"
icon_image: $( icon )
rank: 88
serial: false

kiln_metadata:
  metadata_git_sha: $( variable "metadata-git-sha" )

stemcell_criteria: $( stemcell )

releases:
- $( release "diego" )
- $( release "event-log" )
- $( release "garden-runc" )
- $( release "hwc-offline-buildpack" )
- $( release "loggregator" )
- $( release "loggregator-agent" )
- $( release "winc" )
- $( release "windows-utilities" )
- $( release "cf-windows-smoke-tests" )

form_types:
- $( form "vm_options" )
- $( form "application_containers" )
- $( form "system_logging" )
- $( form "smoke_tests_windows" )
- $( form "advanced_features" )

job_types:
- $( instance_group "windows_diego_cell" )

property_blueprints:
- $( property "bbs_client_cert" )
- $( property "bosh_ssh_enabled" )
- $( property "enable_cf_metric_name" )
- $( property "kms" )
- $( property "loggregator_client_cert" )
- $( property "loggregator_agent_tls_cert" )
- $( property "rdp_enabled" )
- $( property "rep_server_cert" )
- $( property "rep_server_cert_v2" )
- $( property "smoke_tests_windows" )
- $( property "system_logging" )
- $( property "windows_admin_password" )

post_deploy_errands:
  - name: install-hwc-buildpack
    colocated: true
    run_default: true
    instances:
      - windows_diego_cell/first
    label: Install HWC Buildpack Errand
    description: Install the HWC buildpack to your Elastic Runtime for Windows installation
  - name: smoke_tests_windows
    colocated: true
    run_default: false
    instances:
      - windows_diego_cell/first
    label: Smoke Test Errand
    description: Runs Smoke Tests against your Application Service installation

install_time_verifiers: []

variables:
- name: diego-instance-identity-intermediate-ca-2018
  type: certificate
  options:
    common_name: 'Diego Instance Identity Intermediate CA'
    is_ca: true
    duration: 730
    ca: /cf/diego-instance-identity-root-ca
    key_usage:
    - key_cert_sign
