---
name: pas-windows
metadata_version: '2.1'
provides_product_versions:
- name: pas-windows
  version: "0.0.0.0$PRERELEASE_VERSION$"
product_version: "0.0.0.0$PRERELEASE_VERSION$"
minimum_version_for_upgrade: 2.0.0
requires_product_versions:
- name: cf
  version: "~> 2.1.0"
label: "Pivotal Application Service for Windows"
description: "Gives developers the ability to push apps to compute instances powered by the .NET Framework and the Windows® Operating System"
icon_image: $( icon )
rank: 88
serial: false
post_deploy_errands:
  - name: install-hwc-buildpack
    colocated: true
    run_default: true
    instances:
      - windows_diego_cell/first
    label: Install HWC Buildpack Errand
    description: Install the HWC buildpack to your Elastic Runtime for Windows installation
