---
name: p-isolation-segment
metadata_version: '2.1'
provides_product_versions:
- name: p-isolation-segment
  version: "0.0.0.0$PRERELEASE_VERSION$"
product_version: "0.0.0.0$PRERELEASE_VERSION$"
minimum_version_for_upgrade: 2.0.0
requires_product_versions:
- name: cf
  version: "~> 2.1.0"
label: PCF Isolation Segment
description: "Gives developers the ability to push apps to a dedicated set of compute instances."
icon_image: $( icon )
rank: 89
serial: false
