---
name: p-isolation-segment
metadata_version: '2.9' # When a 2.10 Ops Manager appears, this value should be updated to be equal to the product version
provides_product_versions:
- name: p-isolation-segment
  version: $( version )
product_version: $( version )
minimum_version_for_upgrade: 2.9.0
requires_product_versions:
- name: cf
  version: "~> 2.10.0"
label: $( variable "label" )
description: "Gives developers the ability to push apps to a dedicated set of compute instances."
icon_image: $( icon )
rank: 89
serial: false

kiln_metadata:
  metadata_git_sha: $( variable "metadata-git-sha" )

stemcell_criteria: $( stemcell )

releases:
- $( release "bpm" )
- $( release "cf-networking" )
- $( release "cflinuxfs3" )
- $( release "diego" )
- $( release "garden-runc" )
- $( release "haproxy" )
- $( release "loggregator-agent" )
- $( release "metrics-discovery" )
- $( release "mapfs" )
- $( release "nfs-volume" )
- $( release "routing" )
- $( release "silk" )
- $( release "smb-volume" )
- $( release "smoke-tests" )
- $( release "syslog" )

form_types:
- $( form "networking" )
- $( form "application_containers" )
- $( form "system_logging" )
- $( form "advanced_features" )
- $( form "segment_isolation" )
- $( form "smoke_tests_isolation" )

job_types:
- $( instance_group "isolated_ha_proxy" )
- $( instance_group "isolated_router" )
- $( instance_group "isolated_diego_cell" )

property_blueprints:
- $( property "app_graceful_shutdown_period_in_seconds" )
- $( property "app_log_rate_limiting" )
- $( property "bbs_client_cert" )
- $( property "cf_networking_search_domains" )
- $( property "container_networking" )
- $( property "enable_silk_policy_enforcement" )
- $( property "enable_smb_volume_driver" )
- $( property "forwarder_agent_metrics_tls" )
- $( property "garden_disk_cleanup" )
- $( property "enable_garden_containerd_mode" )
- $( property "gorouter_ssl_ciphers" )
- $( property "haproxy_client_cert_validation" )
- $( property "haproxy_client_certificate" )
- $( property "haproxy_forward_tls" )
- $( property "haproxy_hsts_support" )
- $( property "haproxy_max_buffer_size" )
- $( property "haproxy_ssl_ciphers" )
- $( property "isolation_segment_domain" )
- $( property "loggr_udp_forwarder_tls" )
- $( property "loggregator_agent_metrics_tls" )
- $( property "loggregator_client_cert" )
- $( property "loggregator_agent_tls_cert" )
- $( property "metrics_agent_metrics_tls" )
- $( property "metrics_discovery_metrics_tls" )
- $( property "networking_poe_ssl_certs" )
- $( property "networking_point_of_entry" )
- $( property "nfs_volume_driver" )
- $( property "prom_scraper_scrape_tls" )
- $( property "prom_scraper_metrics_tls" )
- $( property "rep_server_cert" )
- $( property "rep_server_cert_v2" )
- $( property "route_integrity" )
- $( property "route_services_internal_lookup" )
- $( property "router_backend_max_conn" )
- $( property "router_client_cert_validation" )
- $( property "router_enable_proxy" )
- $( property "router_balancing_algorithm" )
- $( property "router_headers_remove_if_specified" )
- $( property "router_sticky_session_cookie_names" )
- $( property "router_keepalive_connections" )
- $( property "routing_backends_client_cert_with_san" )
- $( property "routing_custom_ca_certificates" )
- $( property "routing_disable_http" )
- $( property "routing_log_client_ips" )
- $( property "routing_minimum_tls_version" )
- $( property "routing_table_sharding_mode" )
- $( property "routing_tls_termination" )
- $( property "service_discovery_client_tls" )
- $( property "skip_cert_verify" )
- $( property "smoke_tests_isolation" )
- $( property "syslog_agent_metrics_tls" )
- $( property "system_metrics_tls_scraper_cert" )
- $( property "system_logging" )
- $( property "scheduler_binding_cache_tls" )
- $( property "compute_isolation" )

variables:
- name: router-route-services-secret
  type: password

- name: diego-instance-identity-intermediate-ca-2-7
  type: certificate
  options:
    common_name: 'Diego Instance Identity Intermediate CA'
    is_ca: true
    duration: 730
    ca: /cf/diego-instance-identity-root-ca-2-6
    key_usage:
    - key_cert_sign

post_deploy_errands:
  - name: smoke_tests_isolation
    colocated: true
    run_default: true
    instances:
      - isolated_diego_cell/first
    label: Smoke Test Errand
    description: Runs Smoke Tests against your Pivotal Isolation Segment installation

install_time_verifiers: []
