---
name: p-isolation-segment
metadata_version: '2.2'
provides_product_versions:
- name: p-isolation-segment
  version: $( version )
product_version: $( version )
minimum_version_for_upgrade: 2.2.0
requires_product_versions:
- name: cf
  version: "~> 2.4.0"
label: PCF Isolation Segment
description: "Gives developers the ability to push apps to a dedicated set of compute instances."
icon_image: $( icon )
rank: 89
serial: false

kiln_metadata:
  metadata_git_sha: $( variable "metadata-git-sha" )

stemcell_criteria: $( stemcell )

releases:
- $( release "bpm" )
- $( release "cf-networking" )
- $( release "cflinuxfs2" )
- $( release "cflinuxfs3" )
- $( release "consul" )
- $( release "diego" )
- $( release "garden-runc" )
- $( release "haproxy" )
- $( release "loggregator" )
- $( release "mapfs" )
- $( release "nfs-volume" )
- $( release "routing" )
- $( release "silk" )
- $( release "syslog" )

form_types:
- $( form "networking" )
- $( form "application_containers" )
- $( form "system_logging" )
- $( form "advanced_features" )

job_types:
- $( instance_group "isolated_ha_proxy" )
- $( instance_group "isolated_router" )
- $( instance_group "isolated_diego_cell" )

property_blueprints:
- $( property "bbs_client_cert" )
- $( property "cf_networking_search_domains" )
- $( property "container_networking" )
- $( property "garden_disk_cleanup" )
- $( property "garden_persistent_image_list_grootfs" )
- $( property "gorouter_ssl_ciphers" )
- $( property "haproxy_client_cert_validation" )
- $( property "haproxy_client_certificate" )
- $( property "haproxy_forward_tls" )
- $( property "haproxy_hsts_support" )
- $( property "haproxy_max_buffer_size" )
- $( property "haproxy_ssl_ciphers" )
- $( property "loggregator_client_cert" )
- $( property "metron_tls_cert" )
- $( property "networking_poe_ssl_certs" )
- $( property "networking_point_of_entry" )
- $( property "nfs_volume_driver" )
- $( property "rep_preloaded_rootfses_grootfs" )
- $( property "rep_proxy_enabled" )
- $( property "rep_server_cert" )
- $( property "rep_server_cert_v2" )
- $( property "router_backend_max_conn" )
- $( property "router_client_cert_validation" )
- $( property "router_enable_proxy" )
- $( property "router_keepalive_connections" )
- $( property "routing_backends_client_cert" )
- $( property "routing_custom_ca_certificates" )
- $( property "routing_disable_http" )
- $( property "routing_log_client_ips" )
- $( property "routing_minimum_tls_version" )
- $( property "routing_table_sharding_mode" )
- $( property "routing_tls_termination" )
- $( property "service_discovery_client_tls" )
- $( property "skip_cert_verify" )
- $( property "system_logging" )

variables:
- name: router-route-services-secret
  type: password

post_deploy_errands: []

install_time_verifiers: []
