- task: create-external-dbs
  tags: [aws]
  file: p-runtime/ci/jobs/create-aws-dbs.yml
- task: configure-external-dbs
  tags: [aws]
  file: p-runtime/ci/jobs/configure-external-dbs.yml
  config:
    params:
      ERT_VERSION: 1.6
      OPSMAN_VERSION: 1.6
- task: configure-external-file-storage
  tags: [aws]
  file: p-runtime/ci/jobs/configure-external-file-storage.yml
  config:
    params:
      ERT_VERSION: 1.6
      OPSMAN_VERSION: 1.6
- task: configure-experimental-features
  tags: [aws]
  file: p-runtime/ci/jobs/configure-experimental-features.yml
  config:
    params:
      ERT_VERSION: 1.6
      OPSMAN_VERSION: 1.6
