jobs:
  - name: claim-environment-{{pipeline_name}}
    plan:
      - get: p-runtime
        resource: p-runtime-prime
        trigger: true
        passed: [kickoff]
      - put: environment
        resource: environment-{{environment_pool}}
        params:
          acquire: true
      - task: update-krafa
        file: p-runtime/ci/jobs/update-krafa.yml
        config:
          params:
            CLAIM_REASON: ert-1.6-{{pipeline_name}}
            KRAFA_BASE_URL: http://krafa.cfapps.io
            KRAFA_USERNAME: releng
            KRAFA_PASSWORD: bet90onions

  - name: destroy-environment-{{pipeline_name}}
    plan:
      - get: p-runtime
        resource: p-runtime-prime
        trigger: true
        passed: [claim-environment-{{pipeline_name}}]
      - get: environment
        resource: environment-{{environment_pool}}
        trigger: true
        passed: [claim-environment-{{pipeline_name}}]
      - task: destroy
        tags: [{{iaas_type}}]
        file: p-runtime/ci/jobs/destroy-environment.yml

  - name: deploy-ops-manager-{{pipeline_name}}
    plan:
      - get: p-runtime
        resource: p-runtime-prime
        trigger: true
        passed: [destroy-environment-{{pipeline_name}}]
      - get: environment
        resource: environment-{{environment_pool}}
        trigger: true
        passed: [destroy-environment-{{pipeline_name}}]
      - aggregate:
        - get: ops-manager
          resource: ops-manager-stable-{{iaas_type}}
        - task: prepare
          tags: [{{iaas_type}}]
          file: p-runtime/ci/jobs/prepare-environment.yml
      - task: deploy
        tags: [{{iaas_type}}]
        file: p-runtime/ci/jobs/deploy-opsman.yml

  - name: configure-microbosh-{{pipeline_name}}
    plan:
      - get: p-runtime
        resource: p-runtime-prime
        trigger: true
        passed: [deploy-ops-manager-{{pipeline_name}}]
      - get: environment
        resource: environment-{{environment_pool}}
        trigger: true
        passed: [deploy-ops-manager-{{pipeline_name}}]
      - task: configure
        tags: [{{iaas_type}}]
        file: p-runtime/ci/jobs/configure-microbosh.yml
        config:
          params:
            OPSMAN_VERSION: &om_version 1.6

  - name: deploy-microbosh-{{pipeline_name}}
    plan:
      - get: p-runtime
        resource: p-runtime-prime
        trigger: true
        passed: [configure-microbosh-{{pipeline_name}}]
      - get: environment
        resource: environment-{{environment_pool}}
        trigger: true
        passed: [configure-microbosh-{{pipeline_name}}]
      - task: deploy
        tags: [{{iaas_type}}]
        file: p-runtime/ci/jobs/deploy-microbosh.yml
        config:
          params:
            OPSMAN_VERSION: *om_version
        ensure:
          task: get-install-log
          tags: [{{iaas_type}}]
          file: p-runtime/ci/jobs/get-install-log.yml
          config:
            params:
              OPSMAN_VERSION: *om_version

  - name: upload-pivotal-{{pipeline_name}}
    plan:
      - aggregate:
        - get: p-runtime
          resource: p-runtime-prime
          trigger: true
          passed: [build-runtime, deploy-microbosh-{{pipeline_name}}]
        - get: environment
          resource: environment-{{environment_pool}}
          trigger: true
          passed: [deploy-microbosh-{{pipeline_name}}]
        - get: ert-product
          trigger: true
          passed: [build-runtime]
      - task: upload-pivotal
        tags: [{{iaas_type}}]
        file: p-runtime/ci/jobs/upload-pivotal.yml
        config:
          params:
            OPSMAN_VERSION: *om_version

  - name: configure-ert-{{pipeline_name}}
    plan:
      - get: p-runtime
        resource: p-runtime-prime
        trigger: true
        passed: [upload-pivotal-{{pipeline_name}}]
      - get: environment
        resource: environment-{{environment_pool}}
        trigger: true
        passed: [upload-pivotal-{{pipeline_name}}]
      - task: configure-ert
        tags: [{{iaas_type}}]
        file: p-runtime/ci/jobs/configure-ert.yml
        config:
          params:
            ERT_VERSION: 1.6
            OPSMAN_VERSION: *om_version

  - name: deploy-ert-{{pipeline_name}}
    plan:
      - get: p-runtime
        resource: p-runtime-prime
        trigger: true
        passed: [configure-ert-{{pipeline_name}}]
      - get: environment
        resource: environment-{{environment_pool}}
        trigger: true
        passed: [configure-ert-{{pipeline_name}}]
      - task: deploy-ert
        tags: [{{iaas_type}}]
        file: p-runtime/ci/jobs/deploy-ert.yml
        config:
          params:
            OPSMAN_VERSION: *om_version
        ensure:
          task: get-install-log
          tags: [{{iaas_type}}]
          file: p-runtime/ci/jobs/get-install-log.yml
          config:
            params:
              OPSMAN_VERSION: *om_version

  - name: run-cats-{{pipeline_name}}
    plan:
      - get: p-runtime
        resource: p-runtime-prime
        trigger: true
        passed: [deploy-ert-{{pipeline_name}}]
      - get: environment
        resource: environment-{{environment_pool}}
        trigger: true
        passed: [deploy-ert-{{pipeline_name}}]
      - task: run-cats
        tags: [{{iaas_type}}]
        file: p-runtime/ci/jobs/run-cats.yml
        config:
          params:
            OPSMAN_VERSION: *om_version
        on_failure:
          put: cats-logs
          params:
            from: p-runtime/acceptance-tests*.tgz

  - name: destroy-environment-final-{{pipeline_name}}
    plan:
      - get: p-runtime
        resource: p-runtime-prime
        passed: [run-cats-{{pipeline_name}}]
      - get: environment
        resource: environment-{{environment_pool}}
        passed: [run-cats-{{pipeline_name}}]
      - task: destroy
        tags: [{{iaas_type}}]
        file: p-runtime/ci/jobs/destroy-environment.yml

  - name: release-environment-{{pipeline_name}}
    plan:
      - get: p-runtime
        resource: p-runtime-prime
        trigger: true
        passed: [destroy-environment-final-{{pipeline_name}}]
      - get: environment
        trigger: true
        resource: environment-{{environment_pool}}
        passed: [destroy-environment-final-{{pipeline_name}}]
      - put: environment-{{environment_pool}}
        params:
          release: environment
