resources:
  - name: p-runtime-prime
    type: git
    source:
      uri: git@github.com:pivotal-cf/p-runtime.git
      branch: master
      private_key: &p-runtime-read-write-deploy-key |
        -----BEGIN RSA PRIVATE KEY-----
        MIIJKAIBAAKCAgEAw7+kiK2XOykuncn0AWuoxJZYv6T5yfvemEezhNIueKDVLa94
        6CnDnIcjzvKa3PGHngF9KsN5fyWO1ly23zlWc9WOF4Lr52Tx8u/IwaPPPcZafu0K
        TaLycDaUXqq/+6l3x/WTwW73zkJIEIzPNahFqECAKd5cZqjFf+eSF2Ad1u75j44l
        O6P1o5I+mZQo+jfZM/efVeWPgvrUlB2H9YWZdlHnuUQKBk9SlEtP0vBkMZYYmpHl
        gtKAYE7zKy5wX3pROlGtzCAX629I6jb490FmBz7Z0XW0BEQNk6AMHoMHfB3EbO/5
        sA/Bbcd2PCCUZ8uNdWmwjO+SR0W6caVSbBVHXUXeLx+HBs0RrpKRRjh14qVCM03G
        9XdJ0wVYxjKN4s+MjYdbwNoEHkPiskSsuItuM2aWGf28tHh3PgijQhhFWdAc252q
        ymaN3yiMJHPqo6DEYEwC7bjO0H6/O3xzIkFsFTJmYg5aPjl1CXPJmGmGzyxiNHLz
        x3ehR4gmlrU/Jgl/IWGa+inJUHlBDrJ/huQ8fT0SLvSf/DPljtDnoPuIUPQwnBMR
        IekD0gTKJaZ82a7BK2xO8Moke+8i7xBzFVQ2NP55GaJ5gqpUIzmMlTPdnPe6pb0Q
        64U4GpCges8+uEDfMJABOuLV0NKWaHD09BSgsNM+if1NGX3MBFuyNRcnNOMCAwEA
        AQKCAgEAhGmitwIWBuL4savm7v8QjsrVBe5nOgaysHfwK6yx2s+Q5PKJ6yI1PDD+
        PANIVqTbhDqlnMPV7/hMAx18Zsu2e2y+TZE2WrSiJh+lwbc5fSQsGyfljFbpgJar
        Ds6aR3Z/nDe212ZlIpUbgnZ9xGIrnIDlMW1FO/x2fOr8m+tcxAOrtTwGW62xgBBx
        YBolDf2xY8Hheo1q4sMiAX9odOEGyk7lXSF1VodZ6Q541MvgOtq5kfWXN0OFq6A8
        Rb2ILk3jnHucATTEeXIx9J1zFG6cwdH2LgZc23XdaTsed5VS/tZ0BOzgDgTaZ5RB
        mrK/MOc0rXPtBakZXjUAxdd7RbmvJ2vJBD98PSMJpW3nN2orpRjGzo2ZlqtbxL56
        vDrUweSycFyNtHF7u6jsoTTGgmFTlv+O0CyYXSWX/AhpaGMXf6zd80N7DwkFg5oO
        qBa7vwrMACzyy9JP13+Z6fSOAH7dJSNY1YO4HLGEuGrGxpDM17gVPOriVKOHIFst
        Qs/ZbK/AAk9odltQWvAYpIpXhPMPwPKhy7bFVwFhVn8Vj253QhHJGkutWlGrYmjX
        rbIqmN+Lhnk0RKC3ahpI+ciWjEZTUiNZvzzwu6avgis/kNFb84qvb+uX7JpP/02z
        IWox8p7vqLF+o+ogcIerbiThCCGE8H/HzY+gDTQtKMUD+BizgoECggEBAP40ybQ+
        n2Uck/akAcPtMgJN4PuNmoOrI0kuOnR5tXdqJYS5+OAeasU8vDkpm7cn3OrrwHfD
        PjEv1No8UlLFAvieG+aciB8rFX7jhEeoBYcTbHdZikjuxSvJDsc7YRKCzpmcWkNs
        d3PG2Y8w4Zx0qeP4rl3+j79zD+zr2jqauPvKWPryFtklISSGha0mrHRn2R9LeXtL
        3jD6U82NYDoEyi7u9NTD4JDXvMNL4NNyLVK2ui8aL73VNpSt5ALh72m8zs1lpJEz
        NhVPck7C1CMQNJZ269btPhn3hct0hmkt+xiBGeDk4WkLbSbjWUppL7KJlAVKPfB9
        X6GgIXccbtAsh5MCggEBAMUhQPeCuVE8UFDIq/9cah1UmYgE/VQEx+3ghdflrQA+
        MAaGDql9lwKzTLmtEHMKw9vt5B4NLZOLIEfBgD/U0T0A3JRw2gMUpGJjEFqep5RB
        zweHxpebPyMX74GAKYOOutkzB+2XFevOynh6N2R8DIoBmR1BKwcWDpH7EMJE6S2C
        O0Xd9T2dnKc9G2bMjrSLX25N+57hbFh5N6NmvBQNVCH6dqPGdt6AvQS7dw2Gdp7F
        FtPcgeoT2G80daSs0KePdJzgiIwLAIW1e0ostR5PfjFXWER5au3BRrvfP/gY7yM5
        /OZGDqHjLoVDjXN38V07whHWvxVlDXmerhm1CxtTT3ECggEALOW35kzVLC+S9pHa
        +fbPyVZl8Sf+bVjxn4A5tM62PUQTIlESYsscgn+KovH1XbD9tMQ0tzJVrqxLBMx4
        ocPIFY8fUGi/JfofDs0yVNGZQFUu6Bl5cg4x5tzY7llPeMx/nuPdkWD77Afn7wFs
        J4z3YJtQeKt4ShERc//oCEfBej8v3gqZ/HoxU1krDPzyopCg6YUUDLHGqZHc8UYS
        A81KxGVR+q4p4Isp/LhPGillVeGOGrmeSwH4ZOQdjGDJPzyoreBQ45BO8g6ZGs4Q
        V60KDLUuTESUnlN4XwnSn4sOeTJ8Fpt2MG5jNeYbpCfV08u2yARn0izikhJNNtNf
        wwbKXwKCAQAAmgFgv/1gyhZUqMgdl2KbhE6To7BCOWGC0FSYPBMzFP2Ah5gz3DZB
        w9pQFr8eGsJOQYOYs+GXuaz3ixehGj0pOn9x1IZVzBJUWokKPcG1Kh4/n6Jzg/3F
        VaVdd86ooB7h2s4DY5qlhZQImhbhL5+6LBcTh8dh1idlOqbqcNtlUChuJidBcOGx
        gPY8chNdaa943rQN4BI8kuIglYetZ/0BvYnvJgPm2e25vfi3CdoC0gcnzlx3Imhe
        roJNZlmcqUtpzyWbh80Qm2Us7MYAua1g6StTyisRXq2glSXU0/6m1N54tW4GAHN7
        5KDh4VPTPQNymn0qy4wm+tz9JxhJlQ+BAoIBAHiPZc438kw/l7xe6SLuSLkgG1mR
        2oVOMAE6RmabWEovly2Xgnz/U/d5azu9EdKvXHFRS9qFJP86Z96C53+iNYdmaZsV
        7uYhoO0143I9BKTWF4/4NtgzIbyhs1pSVjIZgF6l1dx4+L+3X3cSELsjtoIqM9Ry
        cbSs0P8Z2SiTUqTPoR5BPBx8xdDQ4nYg2SjOTmEjbcC0c03E0biSquOIFJ8512dU
        QYDfEKmVcJDiWYl990zepKZ36bnRkidmcYhRE/cv5lGurYy6HjdgnvjUr88gLRvL
        a29B3Ty3+naKIgLDErouAdRX/8x2NHpo0Vcqfix2AXbjogAe47g69kgw/04=
        -----END RSA PRIVATE KEY-----

  - name: version
    type: semver
    source:
      access_key_id: AKIAJEAGY2FWB7DEGFXQ
      secret_access_key: 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
      bucket: ert-concourse-products
      region_name: us-west-1
      key: ert-1.6/version
      initial_version: 1.6.0-build.0

  - name: environment-multi-az
    type: pool
    source:
      uri: git@github.com:pivotal-cf-experimental/releng-env-resource-pool
      branch: master
      pool: multi-az
      private_key: &env_private_key |
        -----BEGIN RSA PRIVATE KEY-----
        MIIJKQIBAAKCAgEA03pnH/e8lfNriECxroDeZkxY5uEgLhxpcGSFD4oczVP2FzMg
        4hOq9JM5jNqHW3ZL/s9aAq8nkPLnkq8E6IEjL3+dZJUTjlIAvcKl5VCThLMpAJx3
        UEg04q6vIEHKzZh6XKQtDWUxRH+TcGwqo5vKZ3WPUeZdd+7ZUzEzOl/+iz3Peobj
        eVcl+7maMUzlSymAjAQDhdRnZ30l61AuVH9ursCMY0OJwchCoxZFxn0n4qUaTzf0
        she9U4cNwExMWLwidHrhbFanKk1vXN7ZhECuL5rMnTuDy5++R2svAogK2wBmUr/S
        tMMekF6gxSQOSWGV7orhGa0iF3reXkeKUGgMfaXiW1S9BaWKaRfmF63jfH/iBLSQ
        CfWBVmgvMWGeQXm6sx020282Rgvcr5h2QUHx+HqDOOtEij6HPiKm0R9DygtpspX3
        RxES49k0S+Jy2vP21j9Qu92sqCbI7h0jCAadYmvN7+li6hBZNNup2TXMeyTjH08U
        Fa0jPlyM2cufJmt1iMSjXHk0utmO2v6o+GZ8S9GMKfMli2Fv/kWm2OlOs9wON+bw
        YX2XqBmF10UW0wGutu/E9TizhTVYvNOan45NYc/n+Ldh0bfXgchrWXc/Qwobp6DX
        h/WjQSkMfTGSX7obK0vo6+VWs1/249EwuXy/6rJo6lKDXmpkxUqHGpswZAcCAwEA
        AQKCAgAv9e+TWWzkmQsHIJzrVYCatK/o1J+mtXzYJ4PhzVHQ4zzJcCgB/bHku8ru
        fdT60i5UAJSKTUzs25nXM2gqjrb7G7cHS6PewAw4/P8ArbB3BObEo7ePdoC/9Bv1
        ddZXoEAH6JfrFMsCnOhEM9PLvRY/NnMlgNgrzfhtnJfgokqpK4B1akgGidQsbaBh
        k+3giO4FUxe1b0FwP/qsjkejlC725OYx0OxaDV/HetKiPFoiVY1M8ATHqwid++AL
        f4JFEY3C2udq2ZAZ0OvzpPqxurWGSFYlRo0STg0qR02nBlFn74RFOgnAQwwYc82E
        SDQRQldtfQOl/hTgPFZYDWN57s79+jc61bFDrm1+q2m8Yp708wVzxHmL15QnFjfQ
        X5LdS39PITF27nzjF2nZwoCNWe1iMUolPxH227Cxq9LtZRBrNKPG/eMVQd0EVc+U
        DtlcffIbJc19ByYHtFubMwWTmd2vdIYRIbuOKDxT/Q7oGfWSBtfceGCjHgQkQme6
        oM2Kvj7zifLeETHUhxDGH0X1eBKjnuyvCYqXls2/l2Ae4Sigp4S7r78tti/KRvwN
        1bhsVfuXGpjAjS+Y5laY1d6myAvr0qvYhDZ9+HWA0358bvLaq/Ru4LEUe9gTFgZX
        CG6uYI0EEAoj2ZyzAh/0JCeNGXV0X2ucQSzwAwDlI0K6Qz53gQKCAQEA92zsgWmN
        alL0NHfDuDl8TGAu5SGtgXq5c89l7NiKlT9rGXURkN9Hw1Ln1N+rkbI0IvojIfX2
        mr+gSxgQS/A71YioNaxZyfDW0Botd3oxWISjT03XS48VlJkSULK0V2TpWoRA/Q8C
        9jWaxazARr4uf2K5Jq5wj4VImjnASpvyFue7iWpJjZXfHI0683c8jUhkTtzZpJYh
        Dz4NJNXNEbPcz+ln7osBIw4RzYlgYubiJ2CMcbh2mOgECIFR7yhPZRoMv+w0qjqt
        IVDseDK5jtRRJwJ35Wlzv6+KmJATAropiIP/gVal6U2hNiaBgHwf6tDI30j5Il25
        /FsdYGumz6lqwQKCAQEA2s6Q7ijIPfPDwjLtCkrhUajREy9Q4GYx2XjYb7RSCjV6
        nC3IsKXRRZxyuSC9o8z7+yPm98YLIOKeF2nxGr1+3OZ48VE6dZ2lkvbYq6yy64tl
        Y13WoCbtfWAB2k7VLxYj1vVcUgYEjwekvap4oe66Y/vE3kwyV1AaVVlD5nV1eZui
        4RmfZemdfh3M5OdqsEJt7xZZI47uSM1dQhkonmDH/bzlhsWQfQdHmrYXH0JRXnLw
        DFas/gHuTrH8ojZCVdU9a8Iuzfmmt0t3NLWIwFmOIQ0dhjVotoCOCN/QOMVAWhPL
        D3skurIHCigv81KFrRqgJcQF+ymrY6ulHxuUwyBoxwKCAQB/dqu4V4o0tht8VB6N
        739rUTmXbOwXggO796JIi52JGayw5rBv87bilvk7nyah3i4hvr8OpcmvGv0W8oSi
        ulX4wXf2fp2a/OmNN48ot9hoA5ymJDG/iSzS6rCWxhlF1ISqzusz8uHRuPfM0hwT
        1bHaih9cIA14wm8OlKXNSd1Dk4n3Vrwhpo3UBaXS+yBEoICcaAXvVjAdzBe1XDdS
        4Vfl/BZAu3eQeZUOT7FKAiuLoZ94jlD6oLxDLWvqStfr+6mJzcOr1qKOQUQw/+C8
        BgDwmcLueo7YtzQtODuy8finjWi5VswODqH4ZYndiRRgQcLZ1JwT6jkAGmhd3deH
        r32BAoIBAQDHtNHDDaX2JY7+qMyBIGcWySZKhF0k8yF8hDfHfKWEe9s0wPTzheTD
        zE9JeQCdiHJUfihI7ZEqqqvwYtmUtnAb3p90YdchkomU4YhQ6IdFRS18zCEge2c3
        j3Ehd+JL38FGaRuiIav3f9p04irIYcPtjdXZr2IjHxFp5Nd8eKiIHe1D1scNlXQR
        r9Fa+3z88ySzm4owUjxaZlZABgZ0x5DBnq8/mwKNmx9XrerctQLfWbiPCm1KSSjg
        2sLiqvNQtBgjSlC93qazlUVv7mCqbxKyR+4ymHzCVgNNRjoeFqrtjDNCJfsYC3Ux
        aAyb4S3xGOQilA+Bdj7f8cH76oiUr/fxAoIBAQDZHN3cSZQdF5nc06w6ToD2AuJH
        csEryys4lrglW6CVr2gjnaCH4mwp2Ac4JLnTLu84gDYVZKATaJV/Rv2XNpnmXg9x
        nyAPNw+lv1I8I0kqiA/f8fjkjnptwTRGapacyVt4IN52fvB5xGohVwLp0omb1En9
        ivzguGbOdNX4szbFNv9t5xhw3bvvpR3fKStaYlWjIOD07w/ekU3G0fBSqnSNblFw
        J+R2R0z5fNX5AD8RfiVPLhmLTpbY5rwuujFiaHDs/nJvtgeSgQ9y9y9DyB99ZtPP
        OVKNK3IjWsq4oU3qLRZ8w9ZdA06jePzJ6x3ppx6H60u+sock2D8+eeMxjtmJ
        -----END RSA PRIVATE KEY-----

  - name: ops-manager-1.6.0-vsphere
    type: s3
    source:
      access_key_id: AKIAJEAGY2FWB7DEGFXQ
      secret_access_key: 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
      bucket: ert-concourse-products
      region_name: us-west-1
      private: true
      versioned_file: ops_manager_images/vsphere/1.6.0/ops_man_image

  - name: ert-product
    type: s3
    source:
      access_key_id: AKIAJEAGY2FWB7DEGFXQ
      secret_access_key: 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
      bucket: ert-concourse-products
      region_name: us-west-1
      private: true
      regexp: ert-1.6/untested/cf-(.*).pivotal

  - name: cats-logs
    type: s3
    source:
      access_key_id: AKIAJEAGY2FWB7DEGFXQ
      secret_access_key: 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
      bucket: ert-concourse-products
      region_name: us-west-1
      private: true
      versioned_file: cf-acceptance-tests-logs/cats-log.tgz

jobs:
  - name: kickoff
    plan:
      - get: p-runtime
        resource: p-runtime-prime

  - name: build-runtime
    plan:
      - get: version
        params:
          pre: build
      - put: version
        params:
          file: version/number
      - get: p-runtime
        resource: p-runtime-prime
        trigger: true
        passed: [kickoff]
      - task: build-product
        file: p-runtime/ci/jobs/build-pivotal.yml
      - aggregate:
        - put: ert-product
          params:
            from: build-product/cf-(.*).pivotal
            to: ert-1.6/untested/
        - put: p-runtime
          resource: p-runtime-prime
          params:
            repository: p-runtime
            tag: version/number
            tag_prefix: v

groups:
  - name: vsphere-clean
    jobs:
    - claim-environment-vsphere-clean
    - early-destroy-environment-vsphere-clean
    - early-release-environment-vsphere-clean
    - destroy-environment-vsphere-clean
    - deploy-ops-manager-vsphere-clean
    - configure-microbosh-vsphere-clean
    - deploy-microbosh-vsphere-clean
    - upload-pivotal-vsphere-clean
    - configure-ert-vsphere-clean
    - deploy-ert-vsphere-clean
    - run-cats-vsphere-clean
    - destroy-environment-final-vsphere-clean
    - release-environment-vsphere-clean
    - import-stemcell-vsphere-clean

  - name: vsphere-upgrade
    jobs:
    - claim-environment-vsphere-upgrade
    - early-destroy-environment-vsphere-upgrade
    - early-release-environment-vsphere-upgrade
    - destroy-environment-vsphere-upgrade
    - deploy-ops-manager-initial-vsphere-upgrade
    - configure-microbosh-initial-vsphere-upgrade
    - deploy-microbosh-initial-vsphere-upgrade
    - upload-pivotal-initial-vsphere-upgrade
    - configure-ert-initial-vsphere-upgrade
    - deploy-ert-initial-vsphere-upgrade
    - export-installation-vsphere-upgrade
    - destroy-opsman-vsphere-upgrade
    - deploy-opsman-vsphere-upgrade
    - import-installation-vsphere-upgrade
    - upgrade-pivotal-vsphere-upgrade
    - configure-ert-vsphere-upgrade
    - deploy-ert-vsphere-upgrade
    - run-cats-vsphere-upgrade
    - destroy-environment-final-vsphere-upgrade
    - release-environment-vsphere-upgrade
    - import-stemcell-vsphere-upgrade

  - name: common
    jobs:
      - kickoff
      - build-runtime
    resources:
      - ops-manager-1.6.0-vsphere
