jobs:
  - name: claim-environment-{{pipeline_name}}
    plan:
        - get: p-runtime
          trigger: true
          passed: [kickoff]
        - put: environment
          resource: environment-{{environment_pool}}
          params:
            acquire: true
        - task: update-krafa
          file: p-runtime/ci/jobs/update-krafa.yml
          config:
            params:
              CLAIM_REASON: {{pipeline_name}}
              KRAFA_BASE_URL: http://krafa.cfapps.io
              KRAFA_USERNAME: releng
              KRAFA_PASSWORD: bet90onions

  - name: destroy-environment-{{pipeline_name}}
    plan:
      - get: p-runtime
        trigger: true
        passed: [claim-environment-{{pipeline_name}}]
      - get: environment
        resource: environment-{{environment_pool}}
        trigger: true
        passed: [claim-environment-{{pipeline_name}}]
      - task: destroy
        tags: [{{iaas_type}}]
        file: p-runtime/ci/jobs/destroy-environment.yml

  - name: deploy-ops-manager-initial-{{pipeline_name}}
    plan:
      - get: p-runtime
        trigger: true
        passed: [destroy-environment-{{pipeline_name}}]
      - get: environment
        resource: environment-{{environment_pool}}
        trigger: true
        passed: [destroy-environment-{{pipeline_name}}]
      - aggregate:
        - get: ops-manager
          resource: initial-ops-manager-{{iaas_type}}
        - task: prepare
          tags: [{{iaas_type}}]
          file: p-runtime/ci/jobs/prepare-environment.yml
      - task: deploy
        tags: [{{iaas_type}}]
        file: p-runtime/ci/jobs/deploy-opsman.yml

  - name: configure-microbosh-initial-{{pipeline_name}}
    plan:
      - get: p-runtime
        trigger: true
        passed: [deploy-ops-manager-initial-{{pipeline_name}}]
      - get: environment
        resource: environment-{{environment_pool}}
        trigger: true
        passed: [deploy-ops-manager-initial-{{pipeline_name}}]
      - task: configure
        tags: [{{iaas_type}}]
        file: p-runtime/ci/jobs/configure-microbosh.yml
        config:
          params:
            OPSMAN_VERSION: &om_initial_version 1.5

  - name: deploy-microbosh-initial-{{pipeline_name}}
    plan:
      - get: p-runtime
        trigger: true
        passed: [configure-microbosh-initial-{{pipeline_name}}]
      - get: environment
        resource: environment-{{environment_pool}}
        trigger: true
        passed: [configure-microbosh-initial-{{pipeline_name}}]
      - task: deploy
        tags: [{{iaas_type}}]
        file: p-runtime/ci/jobs/deploy-microbosh.yml
        config:
          params:
            OPSMAN_VERSION: *om_initial_version
        ensure:
          task: get-install-log
          tags: [{{iaas_type}}]
          file: p-runtime/ci/jobs/get-install-log.yml
          config:
            params:
              OPSMAN_VERSION: *om_initial_version

  - name: upload-pivotal-initial-{{pipeline_name}}
    plan:
      - get: p-runtime
        trigger: true
        passed: [deploy-microbosh-initial-{{pipeline_name}}]
      - get: environment
        resource: environment-{{environment_pool}}
        trigger: true
        passed: [deploy-microbosh-initial-{{pipeline_name}}]
      - get: ert-product
        resource: initial-ert-product
        trigger: true
      - task: upload
        tags: [{{iaas_type}}]
        file: p-runtime/ci/jobs/upload-pivotal.yml
        config:
          params:
            OPSMAN_VERSION: *om_initial_version

  - name: configure-ert-initial-{{pipeline_name}}
    plan:
      - get: p-runtime
        trigger: true
        passed: [upload-pivotal-initial-{{pipeline_name}}]
      - get: environment
        resource: environment-{{environment_pool}}
        trigger: true
        passed: [upload-pivotal-initial-{{pipeline_name}}]
      - task: configure-ert
        tags: [{{iaas_type}}]
        file: p-runtime/ci/jobs/configure-ert.yml
        config:
          params:
            ERT_VERSION: 1.5
            OPSMAN_VERSION: *om_initial_version

  - name: deploy-ert-initial-{{pipeline_name}}
    plan:
      - get: p-runtime
        trigger: true
        passed: [configure-ert-initial-{{pipeline_name}}]
      - get: environment
        resource: environment-{{environment_pool}}
        trigger: true
        passed: [configure-ert-initial-{{pipeline_name}}]
      - task: deploy-ert
        tags: [{{iaas_type}}]
        file: p-runtime/ci/jobs/deploy-ert.yml
        config:
          params:
            OPSMAN_VERSION: *om_initial_version
        ensure:
          task: get-install-log
          tags: [{{iaas_type}}]
          file: p-runtime/ci/jobs/get-install-log.yml
          config:
            params:
              OPSMAN_VERSION: *om_initial_version

  - name: export-installation-{{pipeline_name}}
    plan:
      - get: p-runtime
        trigger: true
        passed: [deploy-ert-initial-{{pipeline_name}}]
      - get: environment
        resource: environment-{{environment_pool}}
        trigger: true
        passed: [deploy-ert-initial-{{pipeline_name}}]
      - task: export-installation
        tags: [{{iaas_type}}]
        file: p-runtime/ci/jobs/export-installation.yml
        config:
          params:
            OPSMAN_VERSION: *om_initial_version
      - put: exported-installation-{{iaas_type}}
        params:
          from: p-runtime/installation.zip

  - name: destroy-opsman-{{pipeline_name}}
    plan:
      - get: p-runtime
        trigger: true
        passed: [export-installation-{{pipeline_name}}]
      - get: environment
        resource: environment-{{environment_pool}}
        trigger: true
        passed: [export-installation-{{pipeline_name}}]
      - task: destroy-opsman-{{pipeline_name}}
        tags: [{{iaas_type}}]
        file: p-runtime/ci/jobs/destroy-opsman.yml

  - name: deploy-opsman-{{pipeline_name}}
    plan:
      - aggregate:
        - get: p-runtime
          trigger: true
          passed: [destroy-opsman-{{pipeline_name}}]
        - get: environment
          resource: environment-{{environment_pool}}
          trigger: true
          passed: [destroy-opsman-{{pipeline_name}}]
        - get: ops-manager
          resource: ops-manager-stable-{{iaas_type}}
      - task: deploy
        tags: [{{iaas_type}}]
        file: p-runtime/ci/jobs/deploy-opsman.yml

  - name: import-installation-{{pipeline_name}}
    plan:
      - get: p-runtime
        trigger: true
        passed: [export-installation-{{pipeline_name}},deploy-opsman-{{pipeline_name}}]
      - get: environment
        resource: environment-{{environment_pool}}
        trigger: true
        passed: [export-installation-{{pipeline_name}},deploy-opsman-{{pipeline_name}}]
      - get: exported-installation
        resource: exported-installation-{{iaas_type}}
        trigger: true
        passed: [export-installation-{{pipeline_name}}]
      - task: import-installation
        tags: [{{iaas_type}}]
        file: p-runtime/ci/jobs/import-installation.yml
        config:
          params:
            OPSMAN_VERSION: &om_version 1.5

  - name: upgrade-pivotal-{{pipeline_name}}
    plan:
      - aggregate:
        - get: p-runtime
          trigger: true
          passed: [build-runtime, import-installation-{{pipeline_name}}]
        - get: environment
          resource: environment-{{environment_pool}}
          trigger: true
          passed: [import-installation-{{pipeline_name}}]
        - get: ert-product
          trigger: true
          passed: [build-runtime]
      - task: upgrade-pivotal
        tags: [{{iaas_type}}]
        file: p-runtime/ci/jobs/upgrade-pivotal.yml
        config:
          params:
            OPSMAN_VERSION: *om_version

  - name: configure-ert-{{pipeline_name}}
    plan:
      - get: p-runtime
        trigger: true
        passed: [upgrade-pivotal-{{pipeline_name}}]
      - get: environment
        resource: environment-{{environment_pool}}
        trigger: true
        passed: [upgrade-pivotal-{{pipeline_name}}]
      - task: configure-ert
        tags: [{{iaas_type}}]
        file: p-runtime/ci/jobs/configure-ert.yml
        config:
          params:
            ERT_VERSION: 1.6
            OPSMAN_VERSION: *om_version

  - name: import-stemcell-{{pipeline_name}}
    plan:
      - get: p-runtime
        trigger: true
        passed: [configure-ert-{{pipeline_name}}]
      - get: environment
        resource: environment-{{environment_pool}}
        trigger: true
        passed: [configure-ert-{{pipeline_name}}]
      - get: stemcell
        resource: stemcell-1.5.1-{{iaas_type}}
      - task: import-stemcell
        tags: [{{iaas_type}}]
        file: p-runtime/ci/jobs/import-stemcell.yml
        config:
          params:
            OPSMAN_VERSION: *om_version
            PRODUCT_NAME: cf

  - name: deploy-ert-{{pipeline_name}}
    plan:
      - get: p-runtime
        trigger: true
        passed: [import-stemcell-{{pipeline_name}}]
      - get: environment
        resource: environment-{{environment_pool}}
        trigger: true
        passed: [import-stemcell-{{pipeline_name}}]
      - task: deploy-ert
        tags: [{{iaas_type}}]
        file: p-runtime/ci/jobs/deploy-ert.yml
        config:
          params:
            OPSMAN_VERSION: *om_version
        ensure:
          task: get-install-log
          tags: [{{iaas_type}}]
          file: p-runtime/ci/jobs/get-install-log.yml
          config:
            params:
              OPSMAN_VERSION: *om_version

  - name: run-cats-{{pipeline_name}}
    plan:
      - get: p-runtime
        trigger: true
        passed: [deploy-ert-{{pipeline_name}}]
      - get: environment
        resource: environment-{{environment_pool}}
        trigger: true
        passed: [deploy-ert-{{pipeline_name}}]
      - task: run-cats
        tags: [{{iaas_type}}]
        file: p-runtime/ci/jobs/run-cats.yml
        config:
          params:
            OPSMAN_VERSION: *om_version

  - name: destroy-environment-final-{{pipeline_name}}
    plan:
      - get: p-runtime
        passed: [run-cats-{{pipeline_name}}]
      - get: environment
        resource: environment-{{environment_pool}}
        passed: [run-cats-{{pipeline_name}}]
      - task: destroy
        tags: [{{iaas_type}}]
        file: p-runtime/ci/jobs/destroy-environment.yml

  - name: release-environment-{{pipeline_name}}
    plan:
      - get: p-runtime
        trigger: true
        passed: [destroy-environment-final-{{pipeline_name}}]
      - get: environment
        trigger: true
        resource: environment-{{environment_pool}}
        passed: [destroy-environment-final-{{pipeline_name}}]
      - put: environment-{{environment_pool}}
        params:
          release: environment
