---
jobs:
- database # SRT only
- blobstore # SRT only
- control # SRT only
- compute # SRT only
- consul_server # ERT only
- nats # ERT only
- nfs_server # ERT only
- mysql_proxy # ERT only
- mysql # ERT only
- backup_prepare # ERT & SRT
- diego_database # ERT only
- uaa # ERT only
- cloud_controller # ERT only
- ha_proxy # ERT & SRT
- router # ERT & SRT
- mysql_monitor # ERT & SRT
- clock_global # ERT only
- cloud_controller_worker # ERT only
- diego_brain # ERT only
- diego_cell # ERT only
- loggregator_trafficcontroller # ERT only
- syslog_adapter # ERT only
- syslog_scheduler # ERT only
- doppler # ERT only
- tcp_router # ERT & SRT
- credhub # ERT only
- bootstrap # ERT & SRT (errand)
- mysql_rejoin_unsafe # ERT & SRT (errand)
