---
platform: linux

image: docker:///pivotalcf/releng-ci

inputs:
  - name: p-runtime
  - name: environment

params:
  ERT_VERSION:
  OPSMAN_VERSION:

run:
  path: p-runtime/ci/scripts/configure-external-dbs
