---
- name: system_logging
  type: selector
  configurable: true
  default: disable
  option_templates:
  - name: enable
    select_value: enable
    named_manifests:
    - name: syslog
      manifest: |
        enabled: true
        address: (( .properties.system_logging.enable.syslog_host.value ))
        port: (( .properties.system_logging.enable.syslog_port.value ))
        protocol: (( .properties.system_logging.enable.syslog_protocol.value ))
    property_blueprints:
    - name: syslog_host
      type: network_address
      configurable: true
      optional: false
    - name: syslog_port
      type: port
      configurable: true
      optional: false
    - name: syslog_protocol
      type: dropdown_select
      configurable: true
      optional: false
      default: udp
      options:
        - name: tcp
          label: TCP protocol
        - name: udp
          label: UDP protocol
  - name: disable
    select_value: disable
    named_manifests:
    - name: syslog
      manifest: |
        enabled: false

- name: system_metrics_tls_scraper_cert
  type: rsa_cert_credentials
  configurable: false
  default:
    domains:
    - system-metrics
    
- name: system_metrics_enabled
  type: boolean
  configurable: true
  default: true

- name: scheduler_binding_cache_tls
  type: rsa_cert_credentials
  configurable: false
  default:
    domains:
    - binding-cache

- name: forwarder_agent_metrics_tls
  type: rsa_cert_credentials
  configurable: false
  default:
    domains:
    - forwarder-agent-metrics

- name: loggregator_agent_metrics_tls
  type: rsa_cert_credentials
  configurable: false
  default:
    domains:
    - loggregator-agent-metrics

- name: prom_scraper_scrape_tls
  type: rsa_cert_credentials
  configurable: false
  default:
    domains:
    - prom-scraper

- name: prom_scraper_metrics_tls
  type: rsa_cert_credentials
  configurable: false
  default:
    domains:
    - prom-scraper-metrics

- name: syslog_agent_metrics_tls
  type: rsa_cert_credentials
  configurable: false
  default:
    domains:
    - syslog-agent-metrics