---
- name: system_logging
  type: selector
  configurable: true
  default: disabled
  option_templates:
    - name: disabled
      select_value: disabled
      named_manifests:
        - name: syslog
          manifest: |
            migration:
              disabled: true
        - name: syslog_url
          manifest: ""
    - name: enabled
      select_value: enabled
      property_blueprints:
        - name: host
          type: network_address
          configurable: true
        - name: port
          type: port
          configurable: true
        - name: protocol
          type: dropdown_select
          configurable: true
          options:
            - name: tcp
              label: TCP protocol
            - name: relp
              label: RELP protocol
            - name: udp
              label: UDP protocol
        - name: tls_enabled
          type: boolean
          configurable: true
          optional: true
          default: false
        - name: tls_permitted_peer
          type: string
          configurable: true
          optional: true
        - name: tls_ca_cert
          type: ca_certificate
          configurable: true
          optional: true
        - name: use_tcp_for_file_forwarding_local_transport
          type: boolean
          configurable: true
          default: false
        - name: syslog_drop_debug
          type: boolean
          configurable: true
          default: true
        - name: syslog_rule
          type: text
          configurable: true
          optional: true

      named_manifests:
        - name: syslog
          manifest: |
            address: (( .properties.system_logging.enabled.host.value ))
            port: (( .properties.system_logging.enabled.port.value ))
            transport: (( .properties.system_logging.enabled.protocol.value ))
            tls_enabled: (( .properties.system_logging.enabled.tls_enabled.value ))
            ca_cert: (( .properties.system_logging.enabled.tls_ca_cert.value ))
            permitted_peer: (( .properties.system_logging.enabled.tls_permitted_peer.value ))
            use_tcp_for_file_forwarding_local_transport: (( .properties.system_logging.enabled.use_tcp_for_file_forwarding_local_transport.value ))
            custom_rule: |
              (( .properties.system_logging.enabled.syslog_rule.value ))
              if ($programname startswith "vcap.") then stop
              (( .properties.system_logging.enabled.syslog_drop_debug.value ? 'if ($msg contains "DEBUG") then stop' : "" ))
              (( ..cf.properties.container_networking_interface_plugin.silk.enable_log_traffic.value ? .properties.system_logging.selected_option.parsed_manifest(iptables_logging_enabled_part_1) : .properties.system_logging.selected_option.parsed_manifest(iptables_logging_disabled) ))
              (( ..cf.properties.container_networking_interface_plugin.silk.enable_log_traffic.value ? .properties.system_logging.selected_option.parsed_manifest(iptables_logging_enabled_part_2) : .properties.system_logging.selected_option.parsed_manifest(iptables_logging_disabled) ))
        - name: iptables_logging_enabled_part_1
          manifest: |
            if $programname == 'kernel' and ($msg contains "DENY_" or $msg contains "OK_") then -/var/log/kern.log
        - name: iptables_logging_enabled_part_2
          manifest: |
            "&stop"
        - name: iptables_logging_disabled
          manifest: |
            ""

- name: syslog_agent_enabled
  type: boolean
  configurable: true
  default: true

- name: system_metrics_tls_scraper_cert
  type: rsa_cert_credentials
  configurable: false
  default:
    domains:
      - system-metrics

- name: system_metrics_enabled
  type: boolean
  configurable: true
  default: true