name: apple
iaas_type: aws
vm_shepherd:
  env_config:
    stack_name: apple
    aws_access_key: AKIAJEAGY2FWB7DEGFXQ
    aws_secret_key: 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
    region: us-west-1
    json_file: config/ert_cloudformation.json
    parameters:
      01NATKeyPair: releng-dev-west
      05RdsUsername: pivotalcf
      06RdsPassword: pivotalcf
      07SSLCertificateARN: arn:aws:iam::491337929596:server-certificate/apple
    outputs:
      ssh_key_name: {{ssh_key_pair_name}}
      security_group: {{ops_manager_security_group_id}}
      public_subnet_id: {{public_subnet_id}}
      private_subnet_id: {{private_subnet_id}}
      s3_bucket_names:
        - {{ ops_manager_s3_bucket_name }}
        - {{ ert_s3_bucket_name }}
  vm_configs:
    - vm_name: Apple OpsManager
      vm_ip_address: 52.8.37.235

ops_manager:
  url: https://pcf.apple.cf-app.com/
  username: pivotalcf
  password: wilderror16
  ntp_servers: 0.amazon.pool.ntp.org
  availability_zones:
  - iaas_identifier: us-west-1b

  aws:
    aws_access_key: {{iam_aws_access_key_id}}
    aws_secret_key: {{iam_aws_secret_access_key}}
    vpc_id: {{vpc}}
    security_group: {{vms_security_group_name}}
    key_pair_name: {{ssh_key_pair_name}}
    region: {{region}}
    ssh_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEAhjHuhEToOnffT0anE3LAu9ijudz+P7yzVmXW7Ignn+RP56GpFswvBS+rdMoF
      9d13dzom/QdR76EMch16uz0V3SrFyphB2XdHQ34cvJMjlgVxXsNfVHA96rTIP5QVaaB5TRgXsKD8
      /3pJ0q/dWoLq0a4MQT48DI8HCTYT9XnVjYHYJGZHKEj+5ztr4T0CuOuIwmElJJAXu33ooEDJZPYK
      57z7zfy3RtSs0t40A/KJN12fY2ra25P4k7q2o47349Hz+aBsHK9YMAQhGGdPwNOe4yw8Qt1LuK1B
      hxSgt4IWLMXljtHBA8tfBCD12DFQIej+5zBMnjxa9ONML47yZpX6qQIDAQABAoIBAAstj5Oe9cUh
      BQ3icbpR/bHn+sNZoCgI/Ns+gmeTc9GCwBEoSyBmA6in7t08ksCHIRNiWasL+AxA2vuKbxW3oeGZ
      VX5prlqB8AK0N4qRqw4tB+N/3Kn4639obaG2IQ56WoBMeHSzBD/3nLya/5Ixg4PRvp2UpIXbSBfB
      VGpHKr2tq0O4NHGfvNL5OQeI7bXFcDvgiRMTcmY0T0OcU3s2cROnMTgCjMiHSUwZqgaWYKxNCo0v
      jP8CgAHKOj4nNOJwbVcXxmClQocQwnwkyWKuCNWQaPb2js8u9xdekLS6/B+LQYrBfGjR4uFAfWgp
      IS30h+Ws8qplM4ryafHAFBcA14ECgYEAvWtzb6yrwJ6DgANiubhXSlP25z5Mh5O1vFkgYTcJCy4f
      1/u5Rnkeg5ZNNwl/iSVqrv1VT0JdD/HYAhY8iWAJApyYX/xbKilzd33iQtKQjj4uDQAkWRm56FjE
      eKs27u3vppWMLs4d2AAUZSba8gNBmcvNp+WubK2gEZSNBynBz7ECgYEAtV0zLI75LvaCXfk9yPIs
      4xCiwKk6oXncpOVGn0F8D+Y+ywogU3GPPxJQ1HL/WEt0qFt7KIenCLHppOsLSkgSrBM2l5KJBbpA
      3kVwfFTZPubedXHr1usGX/cKO37fZTdE3gqHH2VzND1WZNy8rTpJ5Kbbwd+fzPnXSBqDl1ar0HkC
      gYBmJp9fV0BcpV+HVswUGizBAd0CQh+lcewtQedrZfGznNFBehglwEXLcu/7QV0NCiepbSdnkgN8
      CNGT9of5EdhqFyc5hG9pomcJxtKRdNrOSwwsqKnxfyU5/z0dUkBSw/Bc5wNtbmy7wvc8waKLp2Pm
      W/lxlTTmmQ/cyz7u4P8LUQKBgQCywG4cn7nnWJz7JBmKQW6OSaove1vHJUWb3EIz2qX9QbBoC836
      kDVgM5wpGEKlcpFDEg8bzj+KKVgf7G2PQ+PrZ3BqCco1M/KVYBlS4YnRHljppmOMys3YrbKPGyfx
      KX0d34B4KFRYi4/oD0uC7K1ByFdWCSMGMsTFUySZd5oV+QKBgBop5BJF1e0qw2virzT7ZRbrrsVP
      IBk3hbF/UJ7zaF/pGynZmyjW1zBkO29c7zJxaCqnPdOCGibyFNTfcXNPw3jJcEPzzNa3TtrQLP8Z
      cBzOTY3vQeGxRW5wjIqg98ST3GzN4C2Rd+PpSFS6OvG9CYqBVl1mdde00nyVbcXPNkRv
      -----END RSA PRIVATE KEY-----

  networks:
  - name: first-network
    identifier: {{ private_subnet_id }}
    subnet: 10.0.16.0/20
    reserved_ips: 10.0.16.2-10.0.16.4
    dns: 10.0.0.2
    gateway: 10.0.16.1

  elastic_runtime:
    name: cf
    system_domain: apple.cf-app.com
    apps_domain: apple.cf-app.com
    elb_name: apple-pcf-elb
    elb_dns_name: {{ ert_elb_dns_name }}
    ssh_elb_name: apple-pcf-ssh-elb
    ssh_elb_dns_name: {{ ert_ssh_elb_dns_name }}
    file_storage:
      endpoint: https://s3-us-west-1.amazonaws.com
      bucket: {{ ert_s3_buildpacks_bucket_name }}
      buildpacks_bucket: {{ ert_s3_buildpacks_bucket_name }}
      droplets_bucket: {{ ert_s3_droplets_bucket_name }}
      packages_bucket: {{ ert_s3_packages_bucket_name }}
      resources_bucket: {{ ert_s3_resources_bucket_name }}
      access_key: {{iam_aws_access_key_id}}
      secret_key: {{iam_aws_secret_access_key}}
    rds:
      host: {{rds_address}}
      port: {{rds_port}}
      username: {{rds_username}}
      password: {{rds_password}}
    smtp:
      from: identitystaging@mailinator.com
      address: smtp.sendgrid.net
      port: 587
      credentials:
        identity: PCFRelEng
        password: 4H-9Lh-wD{ZST28x{Q
      enable_starttls_auto: true
      smtp_auth_mechanism: plain
    ssl_certificate: |
      -----BEGIN CERTIFICATE-----
      MIID8DCCAtgCCQDpjAvEEB//5jANBgkqhkiG9w0BAQUFADCBuTELMAkGA1UEBhMC
      VVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBGcmFuY2lzY28x
      EDAOBgNVBAoTB1Bpdm90YWwxHDAaBgNVBAsTE1JlbGVhc2UgRW5naW5lZXJpbmcx
      GzAZBgNVBAMUEiouYXBwbGUuY2YtYXBwLmNvbTEwMC4GCSqGSIb3DQEJARYhY2Yt
      cmVsZWFzZS1lbmdpbmVlcmluZ0BwaXZvdGFsLmlvMB4XDTE1MDcxNjE3NTMwOFoX
      DTE2MDcxNTE3NTMwOFowgbkxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9y
      bmlhMRYwFAYDVQQHEw1TYW4gRnJhbmNpc2NvMRAwDgYDVQQKEwdQaXZvdGFsMRww
      GgYDVQQLExNSZWxlYXNlIEVuZ2luZWVyaW5nMRswGQYDVQQDFBIqLmFwcGxlLmNm
      LWFwcC5jb20xMDAuBgkqhkiG9w0BCQEWIWNmLXJlbGVhc2UtZW5naW5lZXJpbmdA
      cGl2b3RhbC5pbzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJkhWDxR
      uGWyfgxFB14ZrDKXJrl0Wu+nilkkEhtUX8fpyOxiJ/MpclIHubohVMu+EtZpjNoq
      UctMpZ927Q8/hRPbyb62OivydLuopzzWDL0NgNSNpzUu0VKVLNzVopBUSalld5gA
      JAGwcJffsGvtXhyhUUUYanBlJpXj/vaLhLJVKLmF0pbNBGLWHJgAsmD6L3Sfhte7
      n0Toah5Ionh71wT/4gDxjrd612AA5Zgicw0tpo5cbeZ8nGfrvIXgPbwfozINIooQ
      +/ObEoS3IInIz0MTS6b2+H1B7LG8lXsLRFLlpIznmHIbnms/1z0QnvSU76d24YT6
      tNOJ+a9zj5NzLYkCAwEAATANBgkqhkiG9w0BAQUFAAOCAQEAKkkJZ2dFtIHTgWSP
      xE5ozaIV1bAAARSoN+ifWMq8qEt8NnStmBjydBzmjgUtFwVfRBVmGtUgoeAhd0lO
      b/nrNOGlra+T/5XTPJhibYnEdqho/046hC7XhwMHC50gOUpPHuEGZD1RGd4xPuKb
      o5Km6k+6/V6XsoSyxyeAEo3DpU8OFccoSNaTtkYSmNNII0Pb/kJir/+O9PpQgTcy
      jCg+Uq6TKJA3BYx/mNcaY96o9h0/WyGwrwmid3FiCreB+GxJDQSdYCP0ULFDfNki
      4VcnQJjglDVm31e64iD60qHa/WDtaDY0yj8zBVFYSGL6syy/GFRfIJcI2vTfjGx8
      KxeNHw==
      -----END CERTIFICATE-----
    ssl_private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpAIBAAKCAQEAmSFYPFG4ZbJ+DEUHXhmsMpcmuXRa76eKWSQSG1Rfx+nI7GIn
      8ylyUge5uiFUy74S1mmM2ipRy0yln3btDz+FE9vJvrY6K/J0u6inPNYMvQ2A1I2n
      NS7RUpUs3NWikFRJqWV3mAAkAbBwl9+wa+1eHKFRRRhqcGUmleP+9ouEslUouYXS
      ls0EYtYcmACyYPovdJ+G17ufROhqHkiieHvXBP/iAPGOt3rXYADlmCJzDS2mjlxt
      5nycZ+u8heA9vB+jMg0iihD785sShLcgicjPQxNLpvb4fUHssbyVewtEUuWkjOeY
      chueaz/XPRCe9JTvp3bhhPq004n5r3OPk3MtiQIDAQABAoIBAQCVVyLBeQV4ERLD
      DpM335vDnwwCNAr3zRKtCvOpuajLxCHS/4tsp1A51hT5BMa5CT8/4qKepkUtGywv
      kAF0LIOxsVlY6EllUMkttzaaqzqzKbcqFJgs0uMMQjYFjUhEsB9C2JVBJWn4R8YX
      J+3b5BwzmdQzqbMsuElgR4IBmmGotMiBKNt07Zn44LDDgGLMi5Vt2TWEllQQVa1j
      eTbw8SCsOz2Omc7/yrq/BCWzjzhTKxEgEvtUUO3vbmQjTSoFQFcIjT0TgyMF7FDg
      1QXYxzzixqAy6/1nbkUJJ2lo7S+xHAoWHugj4pJN2CuNGQTK5sHvjKKEpDAtjrZX
      tngdPrttAoGBAMpcj0swQPhFS8Yw36fJJr8SGQqJFqxb/b4lonvonZj3Y6MVluGY
      asvnbyCHtz6ukTQwe9TxMp4aYMhkaxGRAEANLaZ3FXgaGnxKuuEpLBjlnfYAsN5j
      6llyAJXQ9Efh7HK/yJEkjeThPBKXThmxBIrxnsZpfw5U5iJRp0eWjOrrAoGBAMG4
      JYt9qVnDvQvZ33P8PeR6MbgzFp4Cqv0AltMaPl8htJMvFCTo98lUAVniCZhrwEHT
      X3n0ruX8M5JBAaNG5/PYOuhWxIUVQJYsgPsr7gquVfDjte7kVT8JEWbgSpiemmRP
      y3bpeU4M+o/14D+cmqXNtabgObk5fhuJBSdHEARbAoGAF4mypTVEqVwuFyyCJ1sP
      ZbQuM3qEp6G/nwlzn+QLyMolzcdqGG2JJpSR6X+/wcu+Wgq1rKwtjhRVY5nClnV+
      SPT/dVhup9ypbgGnQR9v4Kl8uSuVZxjKHoNTLBn1ABN4VFSYeMF+u7uzKBpvXC+p
      7ptyM3P78mfPqPhEc+BAHecCgYEAsRMkrqdFIBp+OdEEIr9Vy/2uaRO5/uGtbusU
      8w6wKMFkkI2eOkcCCPRS79hgsQT9jq4qPg5duTiZ43yshJWR/SGQZ0S5CnVsvlkb
      5Xw4cWb+g92CNkZdbetaDtHDHlMMCdmuwJmWGrRebS1xuHPsINcyzsFzwk49aeoL
      3eVlTLUCgYBuwK5I2vjhHaW0DxGn5dFQnuJpKlLcPCxLGzjyFzQMPRj4AXTRULRt
      jaqbfLSDvKfh66B0DcXDzJD0Z8gQjzQdb3rbKBi8w0bVJM3maVnG4woOxbTdZ66p
      I89yFS8cswJnVjiZ4AtrTHbh+9FXua0j4Bqgijvi0FPCfy2rvkQ3aQ==
      -----END RSA PRIVATE KEY-----
    trust_self_signed_certificates: true
