name: banana
iaas_type: aws
vm_shepherd:
  env_config:
    stack_name: banana
    aws_access_key: AKIAI43577ARGHXPWIMQ
    aws_secret_key: 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
    region: us-east-1
    json_file: config/ert_cloudformation.json
    parameters:
      01NATKeyPair: releng-dev
      05RdsUsername: pivotalcf
      06RdsPassword: pivotalcf
      07SSLCertificateARN: arn:aws:iam::491337929596:server-certificate/banana
    outputs:
      ssh_key_name: releng-dev
      ssh_key_name: {{ssh_key_pair_name}}
      security_group: {{ops_manager_security_group_id}}
      public_subnet_id: {{public_subnet_id}}
      private_subnet_id: {{private_subnet_id}}
      s3_bucket_name: {{ ops_manager_s3_bucket_name }}
  vm_configs:
    - vm_name: Banana OpsManager

ops_manager:
  url: https://54.86.46.89
  username: pivotalcf
  password: pivotalcf
  ntp_servers: 0.amazon.pool.ntp.org
  availability_zones:
  - iaas_identifier: us-east-1a

  aws:
    aws_access_key: {{iam_aws_access_key_id}}
    aws_secret_key: {{iam_aws_secret_access_key}}
    vpc_id: {{vpc}}
    security_group: {{vms_security_group_name}}
    key_pair_name: {{ssh_key_pair_name}}
    region: {{region}}
    ssh_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpAIBAAKCAQEAhU5ETA/Pt42waL2WDKLBfhIXlaQ3YHem3Tojn044bs3GpGBWeHESchL6Ndjv
      Q8ANoeEJ3/P9AsCZTkd3GP+c8JRUcdvg61wIipzP0ltK1KbVt1N0z/E29c+nTqwM4o4zBUQMT3vj
      oG0Yf6iIx+88OcYRx7wUuUGb1NBXkn/GqnadfMO2g//i8UOF1tcz/jXdxf7i192aGPxeC/5bl70h
      Gnk/PlsZjYrq/cDqX4uI3ZdWC2Dsp6pbHilx1umB8FNHUOzh7yvaF4380y3t5I4oPRlD/8hMz/5L
      1R5GsMYHibkLgq48mjVgTsN3tMJU1DZUf6eHx7dqay7hr35vZFER3wIDAQABAoIBADe9OSuAtP7w
      HOI+253e8/8N+5STfKA2h6wbIkf7Qfd6zWNv8Ngdl3PhYYPgeHMgu9KDMUjWUWW0OKYVlcP7JZkm
      vIR7RvnCmsOyu+ceSxTNybEFEWPdXXi84h0wLZcRlF3QTUFy8QPkegju5HqNGuahXk/g4d1whIMg
      tm1IRj6CDZchKLx3G+Ae+rISf7p+o1pEfEgwMfWcIapa3PD/fwMpfRBwrsWdV9wPn63pzJc7pPFW
      H6y8ZEc2ldsrQThk4f1r0UMUFbD9I0yolVQMDA73ZzvCstamh3E4gga9N4XiUOSoT7JGbXdobumJ
      JLOi3XOmcWJaBl9Ocff9Qpp2UBECgYEAxVL9n3pA3/k+zxh+t0MDWt5SP+gKDbqaXLJl5w7zCuTo
      OFCAKnDxHDSxcbTNarcC32QOjV0F8plkxaNgFP3W9KvPk5mRnfTXJE67GsaOTtj0lYhHpo90NqYe
      U5IH2eA6PHzpmHPdEemQBa5O+mQOFRgvt4iXJaDqfK7Iro3UXicCgYEArPH3ffG14/0LuNq3Mt+E
      CAx0m2tmAIxTfpgd7BXz8scvg0DyGa49/8MO7pPEHrhjaocefuprJph0BawfdIR90GBu/ussuGS3
      pYCcLDTT7ma8bomlOi4apmYNjKUZDijnVFycHxhNfZVg+bzCklMDm3vfPSh1W85JM//sUIosOYkC
      gYBC7cxSzG+2yF6yddd9J4C60I/LV1QZpgJ3kJcZ0StEtbHCcCOYwag2bfUF4VKPcLXLua9p6XR7
      /eV9V9XeKN9BLAmDQeJvVj2m9gFmqpRYUCRdl9TdvOipJJ1CsVRyZSi7nY7KA/qm+ba9BouJSGiy
      ZPrCYNULkVIXql0tP7QZnwKBgQCmSjZlhA8Xu80UnkC+ispiDs/kTP0UE9mIhO1ofqdEzh8yPjVL
      Wg3FKaHm5nAR9cupt2gsMmx6/OW6Ook4ONjcjozLUgd6+WTXnvULUHRi66fNRU54xbHcQ45NqMWR
      puTfafi3sV95HDPVjZkspuN2EkJRhOBrOMuMU0y/GExzuQKBgQCbvIkXm3K6ZUCuOSzEHnprRBBt
      /ntsCJQDSBXfrzPTgkBBiMVx3aaJZYnsvxb2+Vl3YYiv/HM/W+rJZsSsbffwAngHNbUfVdlwnayn
      wB5+GnTcHRiog2K6DGyOfn1MXiQg2IX7ZpehJFoucNQ5IG4lioVZSmKwea9d8LFqIajoVA==
      -----END RSA PRIVATE KEY-----

  networks:
  - name: first-network
    identifier: {{ private_subnet_id }}
    subnet: 10.0.16.0/20
    reserved_ips: 10.0.16.2-10.0.16.4
    dns: 10.0.0.2
    gateway: 10.0.16.1

  elastic_runtime:
    name: cf
    system_domain: banana.cf-app.com
    apps_domain: banana.cf-app.com
    elb_name: banana-pcf-elb
    elb_dns_name: {{ ert_elb_dns_name }}
    smtp:
      from: identitystaging@mailinator.com
      address: smtp.sendgrid.net
      port: 587
      credentials:
        identity: PCFRelEng
        password: 4H-9Lh-wD{ZST28x{Q
      enable_starttls_auto: true
      smtp_auth_mechanism: plain
    ssl_certificate: |
      -----BEGIN CERTIFICATE-----
      MIIDKjCCAhKgAwIBAgIUSmRqW5Dbjdhwhcn9NKffk91jY84wDQYJKoZIhvcNAQEF
      BQAwPTELMAkGA1UEBhMCVVMxEDAOBgNVBAoMB1Bpdm90YWwxHDAaBgNVBAMMEyou
      YmFuYW5hLmNmLWFwcC5jb20wHhcNMTUwNjA5MjIwNjExWhcNMTcwNjA4MjIwNjEx
      WjA9MQswCQYDVQQGEwJVUzEQMA4GA1UECgwHUGl2b3RhbDEcMBoGA1UEAwwTKi5i
      YW5hbmEuY2YtYXBwLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
      AKbFhFXB6S4JVQ2Xn6wHDxRf8R9HCEDQy0nnNI5nog5oH6FsA+Tc3AdShTyZiePd
      XJ94reO2f51yCLP1fU4JeYhX7Sffn7eYVrgpsf6ucUMRhUmaVcGSyolMEo/mB/lW
      ikvAC7Vvh/OnfeTCcXEaYSdQRHAJ/i+ooQOWIsYmPmWf6IEESrGp1QGX4/0P47Fm
      AORrO1k3iQXd7l28RzZ5FmrPXuKyVBV3s1oqtX0dqR8hyi5SUs8Pbtv9F1UCpdGq
      a0FQ0dtMEcxowJshoVvNVGAarZmXpw8eLPcf73Qn64qt40ExpMGLUMYaRxGVR+EW
      AcDOiCRFsEWaKfLejdULfWcCAwEAAaMiMCAwHgYDVR0RBBcwFYITKi5iYW5hbmEu
      Y2YtYXBwLmNvbTANBgkqhkiG9w0BAQUFAAOCAQEAEhsat3v4/Aw4+ZyisYXpc+YE
      XtXwAVje5OVXj9skLioHsP5rNhtKtZGP/3A5xbFMWYbsc4hM6+WH75jDmEohJQ0Q
      vNKAWtD6qVMCEGiV6Ujzq98A5F85lErB/lrSrTpuCSFPfB+qwjtTbMxSO+afxffE
      wXm7MppEOqq+GVE6IJZPsTeYhTCBBymNVi6TaRUCplpohuS6n7lG/MwIA/HdJWK6
      im9JeB57bPzrnZQrGcLGi37e+owauwhIN5brT5G1AVUpDGohmn6s6PLOxIbkOnLp
      4r9UdJubhNaas35wCaQrZNuJJzyrJ3s4ot0tAik1yjYGQInweyAA4JkmuLy/FQ==
      -----END CERTIFICATE-----
    ssl_private_key: |
    trust_self_signed_certificates: true
