name: banana
iaas_type: aws
vm_shepherd:
  env_config:
    stack_name: banana
    aws_access_key: AKIAI43577ARGHXPWIMQ
    aws_secret_key: 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
    region: us-east-1
    json_file: config/ert_cloudformation.json
    parameters:
      01NATKeyPair: releng-dev
      05RdsUsername: pivotalcf
      06RdsPassword: pivotalcf
      07SSLCertificateARN: arn:aws:iam::491337929596:server-certificate/banana
    outputs:
      ssh_key_name: releng-dev
      ssh_key_name: {{ssh_key_pair_name}}
      security_group: {{ops_manager_security_group_id}}
      public_subnet_id: {{public_subnet_id}}
      private_subnet_id: {{private_subnet_id}}
      s3_bucket_names:
        - {{ ops_manager_s3_bucket_name }}
        - {{ ert_s3_bucket_name }}
  vm_configs:
    - vm_name: Banana OpsManager
      vm_ip_address: 54.86.46.89

ops_manager:
  url: https://pcf.banana.cf-app.com
  username: pivotalcf
  password: pivotalcf
  ntp_servers: 0.amazon.pool.ntp.org
  availability_zones:
  - iaas_identifier: us-east-1a

  aws:
    aws_access_key: {{iam_aws_access_key_id}}
    aws_secret_key: {{iam_aws_secret_access_key}}
    vpc_id: {{vpc}}
    security_group: {{vms_security_group_name}}
    key_pair_name: {{ssh_key_pair_name}}
    region: {{region}}
    ssh_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpAIBAAKCAQEAhU5ETA/Pt42waL2WDKLBfhIXlaQ3YHem3Tojn044bs3GpGBWeHESchL6Ndjv
      Q8ANoeEJ3/P9AsCZTkd3GP+c8JRUcdvg61wIipzP0ltK1KbVt1N0z/E29c+nTqwM4o4zBUQMT3vj
      oG0Yf6iIx+88OcYRx7wUuUGb1NBXkn/GqnadfMO2g//i8UOF1tcz/jXdxf7i192aGPxeC/5bl70h
      Gnk/PlsZjYrq/cDqX4uI3ZdWC2Dsp6pbHilx1umB8FNHUOzh7yvaF4380y3t5I4oPRlD/8hMz/5L
      1R5GsMYHibkLgq48mjVgTsN3tMJU1DZUf6eHx7dqay7hr35vZFER3wIDAQABAoIBADe9OSuAtP7w
      HOI+253e8/8N+5STfKA2h6wbIkf7Qfd6zWNv8Ngdl3PhYYPgeHMgu9KDMUjWUWW0OKYVlcP7JZkm
      vIR7RvnCmsOyu+ceSxTNybEFEWPdXXi84h0wLZcRlF3QTUFy8QPkegju5HqNGuahXk/g4d1whIMg
      tm1IRj6CDZchKLx3G+Ae+rISf7p+o1pEfEgwMfWcIapa3PD/fwMpfRBwrsWdV9wPn63pzJc7pPFW
      H6y8ZEc2ldsrQThk4f1r0UMUFbD9I0yolVQMDA73ZzvCstamh3E4gga9N4XiUOSoT7JGbXdobumJ
      JLOi3XOmcWJaBl9Ocff9Qpp2UBECgYEAxVL9n3pA3/k+zxh+t0MDWt5SP+gKDbqaXLJl5w7zCuTo
      OFCAKnDxHDSxcbTNarcC32QOjV0F8plkxaNgFP3W9KvPk5mRnfTXJE67GsaOTtj0lYhHpo90NqYe
      U5IH2eA6PHzpmHPdEemQBa5O+mQOFRgvt4iXJaDqfK7Iro3UXicCgYEArPH3ffG14/0LuNq3Mt+E
      CAx0m2tmAIxTfpgd7BXz8scvg0DyGa49/8MO7pPEHrhjaocefuprJph0BawfdIR90GBu/ussuGS3
      pYCcLDTT7ma8bomlOi4apmYNjKUZDijnVFycHxhNfZVg+bzCklMDm3vfPSh1W85JM//sUIosOYkC
      gYBC7cxSzG+2yF6yddd9J4C60I/LV1QZpgJ3kJcZ0StEtbHCcCOYwag2bfUF4VKPcLXLua9p6XR7
      /eV9V9XeKN9BLAmDQeJvVj2m9gFmqpRYUCRdl9TdvOipJJ1CsVRyZSi7nY7KA/qm+ba9BouJSGiy
      ZPrCYNULkVIXql0tP7QZnwKBgQCmSjZlhA8Xu80UnkC+ispiDs/kTP0UE9mIhO1ofqdEzh8yPjVL
      Wg3FKaHm5nAR9cupt2gsMmx6/OW6Ook4ONjcjozLUgd6+WTXnvULUHRi66fNRU54xbHcQ45NqMWR
      puTfafi3sV95HDPVjZkspuN2EkJRhOBrOMuMU0y/GExzuQKBgQCbvIkXm3K6ZUCuOSzEHnprRBBt
      /ntsCJQDSBXfrzPTgkBBiMVx3aaJZYnsvxb2+Vl3YYiv/HM/W+rJZsSsbffwAngHNbUfVdlwnayn
      wB5+GnTcHRiog2K6DGyOfn1MXiQg2IX7ZpehJFoucNQ5IG4lioVZSmKwea9d8LFqIajoVA==
      -----END RSA PRIVATE KEY-----

  networks:
  - name: first-network
    identifier: {{ private_subnet_id }}
    subnet: 10.0.16.0/20
    reserved_ips: 10.0.16.2-10.0.16.4
    dns: 10.0.0.2
    gateway: 10.0.16.1

  elastic_runtime:
    name: cf
    system_domain: banana.cf-app.com
    apps_domain: banana.cf-app.com
    elb_name: banana-pcf-elb
    elb_dns_name: {{ ert_elb_dns_name }}
    file_storage:
      endpoint: https://s3.amazonaws.com
      bucket: {{ ert_s3_bucket_name }}
      access_key: {{iam_aws_access_key_id}}
      secret_key: {{iam_aws_secret_access_key}}
    rds:
      host: {{rds_address}}
      port: {{rds_port}}
      username: {{rds_username}}
      password: {{rds_password}}
    smtp:
      from: identitystaging@mailinator.com
      address: smtp.sendgrid.net
      port: 587
      credentials:
        identity: PCFRelEng
        password: 4H-9Lh-wD{ZST28x{Q
      enable_starttls_auto: true
      smtp_auth_mechanism: plain
    ssl_certificate: |
      -----BEGIN CERTIFICATE-----
      MIIDKzCCAhOgAwIBAgIVAN7yZiTcrnP4v0c9P5PLTQa3adj+MA0GCSqGSIb3DQEB
      BQUAMD0xCzAJBgNVBAYTAlVTMRAwDgYDVQQKDAdQaXZvdGFsMRwwGgYDVQQDDBMq
      LmJhbmFuYS5jZi1hcHAuY29tMB4XDTE1MDYxNDIzNDkxOVoXDTE3MDYxMzIzNDkx
      OVowPTELMAkGA1UEBhMCVVMxEDAOBgNVBAoMB1Bpdm90YWwxHDAaBgNVBAMMEyou
      YmFuYW5hLmNmLWFwcC5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
      AQCu/5wdoSpy9hS9+WbE7XC3CR0nxW/ERxC45kMHIXJftHq1UQHVxFITHyrsx6Ed
      ZKEyLxjrkfI4fhkytFDebeyp2E7lxp0d0xlMmYYCYPzHGi0RvCH61VkEOtB0asqO
      84Y38GBWdR0XTc7feGvaeQASs73jAHSkK+BSS2rbVU9vmxQBEOgs3YyHj8yLw8oU
      MFzBKvaPmitvP7wl63ZJplnDQQIZGTB8/nm2izUpMgvwkeLTJ9m+jZIHDwoNJ0O9
      q5/iQal6QMub2G9/mcJSbte6j4M5bp0j8+033cmoD44WHk6XRr9x199feutmG4Pg
      ZEHWiWyLOSzcCN3rRoQo5oTFAgMBAAGjIjAgMB4GA1UdEQQXMBWCEyouYmFuYW5h
      LmNmLWFwcC5jb20wDQYJKoZIhvcNAQEFBQADggEBAEmAToLEP15eq8jiDinGicCw
      2cTdQDzlo9BFU9DdzyrI+lrOkZmyk4T0lHqJZhjaaVNSMuuEpeZNUp+GYcAVHMG1
      BMxg35uZiFLhMYxqoeDofEKXt93o8D6qiRKzLGkWNR/52DjEb6tKo8lXeZkSiQ7O
      QLd11t+mmz4zwEaAYLlFq7jY4l3dMtLiC0xAgAbVlSh92gJtTaKKi7CaVvEIo3sd
      E1VuJ0RFh8lQAdVeIvxb9nLchidQSbYh7Wpzx7db8lrDHmGC7Ap+wBVHPUG7GSVM
      05NWvA50tD7SPcJxhvpXuvhbBMksA9aWXEeGLwxyj9tGggCbP7qiwMzGir7JWoc=
      -----END CERTIFICATE-----
    ssl_private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEArv+cHaEqcvYUvflmxO1wtwkdJ8VvxEcQuOZDByFyX7R6tVEB
      1cRSEx8q7MehHWShMi8Y65HyOH4ZMrRQ3m3sqdhO5cadHdMZTJmGAmD8xxotEbwh
      +tVZBDrQdGrKjvOGN/BgVnUdF03O33hr2nkAErO94wB0pCvgUktq21VPb5sUARDo
      LN2Mh4/Mi8PKFDBcwSr2j5orbz+8Jet2SaZZw0ECGRkwfP55tos1KTIL8JHi0yfZ
      vo2SBw8KDSdDvauf4kGpekDLm9hvf5nCUm7Xuo+DOW6dI/PtN93JqA+OFh5Ol0a/
      cdffX3rrZhuD4GRB1olsizks3Ajd60aEKOaExQIDAQABAoIBABDlrXVO8oJXMHmH
      c1zgcFm8D4yfi8Mv+XVhBmfR2vFSw+ZuA/dYFXSzNbnXLL9h0A7AbW+RkAnUYyp6
      LrTLeGaN9FBLdTBECdVTnZTtOHshE+j6eW123DmEVExpY1WaPgN4ulSeykhNwwPg
      5Mkbld44bMVWbezML8TCc3bqLdlgvxRwUmpwmle1DhRYeyz23G2XRXfrHZ8L+Hjt
      PGAd7PEJM/Kgm6Yahhcu13oiOBd0FlZoD8YdMEvM5rTbZa4+2YQbsMI90A3y76hi
      Ec+h0sIet9MRH+8SufJVmxdpgNTMBpnE5u27xnbVmmgVLtk+cHVFCGvKag5Poe39
      T4LSE6ECgYEA1yPHdliwN5SZt6SqB7Rr1UJncBcHcPvWUvRrqMkAJGm/bx+CQzoU
      k1sVjhezrAoYllk4f3LxdSJcXACZdvmuJEezmvWROYYYi1mDBZHeyY/2hJ4T+M2l
      np381j8MDt3pY7STMQnSwzcvtVpW8akLIKoiFa4A3OWohNwhhftzprcCgYEA0Dwj
      TSVJ8UFOhnGtW+Ic07G/12n8VbYEdFKac1BVasrbBWOPOqnnyc7MxCgUdDjVTViq
      Kss/Ss9zd+4L6sw4uAFDGUg5BnGK6TFYq9qhb2w8rZ/YvZK4GKwFTYDG91vvMn/Z
      ZN+oYPzC6Hc7ttns9vM4gTpQWVGTJlf+lKpPVGMCgYBEPBLdVE+/sR/4AP/0paK1
      5vPLt2Ii0Z0ufltPE0E6S1fuNL4p+FfiTLdPc/EGlcUqmm2y7o/qqNVGUOJbu+Eh
      nKQ4d75x0jgiqmdF8vgIUeLMOR74gLEQ1+cDRMfcR0Ho37L3kLgKNoypJlgBGa5v
      08YvvhqD9Us3qGHxjskljQKBgAiIznGU+6jVomBEPHStmbzbZh9wCpWAtkIGOKpN
      OpL76WoZIH+pAwT0YtQPSHdS9PsMjTzfw6JPSk46BWcEI7b25kcc/KlU8fqIuTeh
      6Efmyb3b9UgfwUfRlQ4OHxl4PR92ufQ2bnI7KcnZSSs/V0TvxvsU5sIiY8OIi7iQ
      Glw9AoGBAKpO0qC4RqbHW4BzJwXDGr9vefVBWJNiGptvQuDnDS4B6Vom2XiREWnM
      jH7AgEdOMY+5quT1nke/jE9iKpYG3dnHNh026kxMHCxBm69r4FBUzXCRjISn7aez
      NGc0RKpabZ25YMhOO6gklfRsdI56kLQ5b+27qdrFLBuT8iAls67Q
      -----END RSA PRIVATE KEY-----
    trust_self_signed_certificates: true
