---
name: bird
iaas_type: vsphere
vm_shepherd:
  vm_configs:
  - vcenter_creds:
      ip: 10.84.32.61
      username: root
      password: look74Beer
    vsphere:
      host: vcenter
      resource_pool: bird
      datacenter: private
      cluster: private
      datastore: private
      network: bird
      folder: bird
    cleanup:
      datacenter: private
      datastores:
      - private
      datacenter_folders_to_clean:
      - bird
      - bird_vms
      - bird_templates
      datastore_folders_to_clean:
      - bird
      - bird_disk
    vm:
      ip: 10.85.4.16
      gateway: 10.85.4.1
      netmask: 255.255.255.0
      dns: 10.87.8.10,10.87.8.11
      ntp_servers: time1.sf.cf-app.com
      vm_password: pivotalcf
ops_manager:
  url: https://pcf.bird.wild.cf-app.com
  username: pivotalcf
  password: wilderror16
  ntp_servers: time1.sf.cf-app.com
  vcenter:
    creds:
      ip: 10.84.32.61
      username: root
      password: look74Beer
    datacenter: private
    persistent_datastore: private
    bosh_vm_folder: bird_vms
    bosh_template_folder: bird_templates
    bosh_disk_path: bird_disk
  availability_zones:
  - name: first-az
    cluster: private
    resource_pool: bird
  networks:
  - name: first-network
    identifier: bird
    subnet: 10.85.4.0/24
    gateway: 10.85.4.1
    reserved_ips: 10.85.4.0-10.85.4.90
    dns: 10.87.8.10,10.87.8.11
  elastic_runtime:
    name: cf
    ha_proxy_static_ips: 10.85.4.254
    system_domain: sys.bird.wild.cf-app.com
    apps_domain: apps.bird.wild.cf-app.com
    smtp:
      from: identitystaging@mailinator.com
      address: smtp.sendgrid.net
      port: 587
      credentials:
        identity: PCFRelEng
        password: 4H-9Lh-wD{ZST28x{Q
      enable_starttls_auto: true
      smtp_auth_mechanism: plain
    trust_self_signed_certificates: true
