name: brinjal
iaas_type: aws
vm_shepherd_configs:
  - aws_access_key: AKIAI43577ARGHXPWIMQ
    aws_secret_key: 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
    ssh_key_name: releng-dev
    public_subnet_id: subnet-1c40de6b
    private_subnet_id: subnet-1b40de6c
    security_group: sg-dca5cdb8
    elastic_ip_id: eipalloc-5cd84639
    vm_name: 'OpsManager brinjal'

ops_manager:
  url: https://pcf.brinjal.cf-app.com/
  username: pivotalcf
  password: pivotalcf
  ntp_servers: 0.amazon.pool.ntp.org
  availability_zones:
  - iaas_identifier: us-east-1d

  aws:
    aws_access_key: AKIAI43577ARGHXPWIMQ
    aws_secret_key: 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
    vpc_id: vpc-72a9e817
    security_group: pcfVMs
    key_pair_name: releng-dev
    ssh_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpAIBAAKCAQEAhU5ETA/Pt42waL2WDKLBfhIXlaQ3YHem3Tojn044bs3GpGBWeHESchL6Ndjv
      Q8ANoeEJ3/P9AsCZTkd3GP+c8JRUcdvg61wIipzP0ltK1KbVt1N0z/E29c+nTqwM4o4zBUQMT3vj
      oG0Yf6iIx+88OcYRx7wUuUGb1NBXkn/GqnadfMO2g//i8UOF1tcz/jXdxf7i192aGPxeC/5bl70h
      Gnk/PlsZjYrq/cDqX4uI3ZdWC2Dsp6pbHilx1umB8FNHUOzh7yvaF4380y3t5I4oPRlD/8hMz/5L
      1R5GsMYHibkLgq48mjVgTsN3tMJU1DZUf6eHx7dqay7hr35vZFER3wIDAQABAoIBADe9OSuAtP7w
      HOI+253e8/8N+5STfKA2h6wbIkf7Qfd6zWNv8Ngdl3PhYYPgeHMgu9KDMUjWUWW0OKYVlcP7JZkm
      vIR7RvnCmsOyu+ceSxTNybEFEWPdXXi84h0wLZcRlF3QTUFy8QPkegju5HqNGuahXk/g4d1whIMg
      tm1IRj6CDZchKLx3G+Ae+rISf7p+o1pEfEgwMfWcIapa3PD/fwMpfRBwrsWdV9wPn63pzJc7pPFW
      H6y8ZEc2ldsrQThk4f1r0UMUFbD9I0yolVQMDA73ZzvCstamh3E4gga9N4XiUOSoT7JGbXdobumJ
      JLOi3XOmcWJaBl9Ocff9Qpp2UBECgYEAxVL9n3pA3/k+zxh+t0MDWt5SP+gKDbqaXLJl5w7zCuTo
      OFCAKnDxHDSxcbTNarcC32QOjV0F8plkxaNgFP3W9KvPk5mRnfTXJE67GsaOTtj0lYhHpo90NqYe
      U5IH2eA6PHzpmHPdEemQBa5O+mQOFRgvt4iXJaDqfK7Iro3UXicCgYEArPH3ffG14/0LuNq3Mt+E
      CAx0m2tmAIxTfpgd7BXz8scvg0DyGa49/8MO7pPEHrhjaocefuprJph0BawfdIR90GBu/ussuGS3
      pYCcLDTT7ma8bomlOi4apmYNjKUZDijnVFycHxhNfZVg+bzCklMDm3vfPSh1W85JM//sUIosOYkC
      gYBC7cxSzG+2yF6yddd9J4C60I/LV1QZpgJ3kJcZ0StEtbHCcCOYwag2bfUF4VKPcLXLua9p6XR7
      /eV9V9XeKN9BLAmDQeJvVj2m9gFmqpRYUCRdl9TdvOipJJ1CsVRyZSi7nY7KA/qm+ba9BouJSGiy
      ZPrCYNULkVIXql0tP7QZnwKBgQCmSjZlhA8Xu80UnkC+ispiDs/kTP0UE9mIhO1ofqdEzh8yPjVL
      Wg3FKaHm5nAR9cupt2gsMmx6/OW6Ook4ONjcjozLUgd6+WTXnvULUHRi66fNRU54xbHcQ45NqMWR
      puTfafi3sV95HDPVjZkspuN2EkJRhOBrOMuMU0y/GExzuQKBgQCbvIkXm3K6ZUCuOSzEHnprRBBt
      /ntsCJQDSBXfrzPTgkBBiMVx3aaJZYnsvxb2+Vl3YYiv/HM/W+rJZsSsbffwAngHNbUfVdlwnayn
      wB5+GnTcHRiog2K6DGyOfn1MXiQg2IX7ZpehJFoucNQ5IG4lioVZSmKwea9d8LFqIajoVA==
      -----END RSA PRIVATE KEY-----

  networks:
  - name: first-network
    identifier: subnet-1b40de6c
    subnet: 10.0.16.0/20
    reserved_ips: 10.0.16.2-10.0.16.4
    dns: 10.0.0.2
    gateway: 10.0.16.1

  elastic_runtime:
    name: cf
    system_domain: sys.brinjal.cf-app.com
    apps_domain: apps.brinjal.cf-app.com
    elb_name: brinjal
    smtp:
      from: identitystaging@mailinator.com
      address: smtp.sendgrid.net
      port: 587
      credentials:
        identity: PCFRelEng
        password: 4H-9Lh-wD{ZST28x{Q
      enable_starttls_auto: true
      smtp_auth_mechanism: plain
    ssl_certificate: |
      -----BEGIN CERTIFICATE-----
      MIICLzCCAZgCCQCE5TYXmTA1OzANBgkqhkiG9w0BAQUFADBcMQswCQYDVQQGEwJV
      UzELMAkGA1UECBMCQ0ExITAfBgNVBAoTGEludGVybmV0IFdpZGdpdHMgUHR5IEx0
      ZDEdMBsGA1UEAxQUKi5icmluamFsLmNmLWFwcC5jb20wHhcNMTUwNDAyMTgwMzM3
      WhcNMTUwNTAyMTgwMzM3WjBcMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExITAf
      BgNVBAoTGEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDEdMBsGA1UEAxQUKi5icmlu
      amFsLmNmLWFwcC5jb20wgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAJW9yvBq
      j1rWJmnLJeCR4d6asqEGGnLMFnXiFq3+Wfsu+AWzLk09B6AIyo2kHCBjeQ6eX279
      mvEzZ1iW8r9xOUkJAvTxzg8h8RFNzyL8mNdcDPuPG5m+X+RlkFCwLojhOV/y8r4y
      eyVYffn9Sfo1H1htHFW8gkr6GlZqelg4XRKnAgMBAAEwDQYJKoZIhvcNAQEFBQAD
      gYEAdW5UAurPm4Rkc6utMayx/9Hogu8a4heyFNtxNrls7PmusNR28my3ivEqj2A0
      EKiCDKKFgm6T9h+qA6LyuwCq8apTXfDj3tOpkb/IhLCQEbcZuhzv7bp4TGFlXbPM
      vebMfaWLtpsxTr0jFIw5lD0n7RhajjXku+ItHabVNsrYy3w=
      -----END CERTIFICATE-----
    ssl_private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIICXQIBAAKBgQCVvcrwao9a1iZpyyXgkeHemrKhBhpyzBZ14hat/ln7LvgFsy5N
      PQegCMqNpBwgY3kOnl9u/ZrxM2dYlvK/cTlJCQL08c4PIfERTc8i/JjXXAz7jxuZ
      vl/kZZBQsC6I4Tlf8vK+MnslWH35/Un6NR9YbRxVvIJK+hpWanpYOF0SpwIDAQAB
      AoGAcWRTtVM8U3EvjZWEjVZrUIKdGkrg5GWf7IzU19VwlkGvF8HkIiFBEPMXT8Mi
      eXRaS7OqWQY6usROUkucb1RyJ6/fw48QNKqJ/donjXt1JrCGiduPU+PWVDDI7gwq
      w2kKoYLcnGnEpOcP0kzY56sBWlY9tKnKSn9vheaEJ69H4KECQQDD0DznaIgyy9IK
      bz3VudNhc+g+FyEkDXCssLT0UyNZRarqJm5ykSyc49nGn3ywGWCTw2Rw62emeRvt
      4ffJT2mNAkEAw8RVIS1dMvRC2kfmdPSWTZmpWkFSefUQipt7hO0qC6+6KhbyWaDP
      4UZt5TA2pNsF3HvHD6JBbV64QhFmyrWuAwJBAL1YQ0xRHEJiLLzCTLy6b9gwSEah
      /v3psSaLyK7pJalRYLACcZJ/JvCesxsJZXyzTVwU+K7oMtYbDhK9CumyzJECQHx9
      wdUTUA0zH8BHsNn3IA3BBd0LZTOBED/UmDvzxaUg3rYdWYh9pzSO4Ru6CUXUsml/
      nRroB8tRTMNW5ZNK7ZkCQQCxPJ+wSsltmyhhJj54wArSFqNIwKdNItMr1blBUwwj
      nrGQHOlvIstpJUPUqUnaTiWPf+1hkA2oMJ/925Do5TEa
      -----END RSA PRIVATE KEY-----
    trust_self_signed_certificates: true
