name: cherry
iaas_type: aws
vm_shepherd:
  env_config:
    stack_name: cherry
    aws_access_key: AKIAJEAGY2FWB7DEGFXQ
    aws_secret_key: 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
    region: us-west-1
    json_file: config/ert_cloudformation.json
    parameters:
      01NATKeyPair: releng-dev-west
      05RdsUsername: pivotalcf
      06RdsPassword: pivotalcf
      07SSLCertificateARN: arn:aws:iam::491337929596:server-certificate/cherry
    outputs:
      ssh_key_name: {{ssh_key_pair_name}}
      security_group: {{ops_manager_security_group_id}}
      public_subnet_id: {{public_subnet_id}}
      private_subnet_id: {{private_subnet_id}}
      s3_bucket_names:
        - {{ ops_manager_s3_bucket_name }}
        - {{ ert_s3_bucket_name }}
  vm_configs:
    - vm_name: Cherry OpsManager
      vm_ip_address: 54.67.2.115

ops_manager:
  url: https://pcf.cherry.cf-app.com/
  username: pivotalcf
  password: wilderror16
  ntp_servers: 0.amazon.pool.ntp.org
  availability_zones:
  - iaas_identifier: us-west-1b

  aws:
    aws_access_key: {{iam_aws_access_key_id}}
    aws_secret_key: {{iam_aws_secret_access_key}}
    vpc_id: {{vpc}}
    security_group: {{vms_security_group_name}}
    key_pair_name: {{ssh_key_pair_name}}
    region: {{region}}
    ssh_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEAhjHuhEToOnffT0anE3LAu9ijudz+P7yzVmXW7Ignn+RP56GpFswvBS+rdMoF
      9d13dzom/QdR76EMch16uz0V3SrFyphB2XdHQ34cvJMjlgVxXsNfVHA96rTIP5QVaaB5TRgXsKD8
      /3pJ0q/dWoLq0a4MQT48DI8HCTYT9XnVjYHYJGZHKEj+5ztr4T0CuOuIwmElJJAXu33ooEDJZPYK
      57z7zfy3RtSs0t40A/KJN12fY2ra25P4k7q2o47349Hz+aBsHK9YMAQhGGdPwNOe4yw8Qt1LuK1B
      hxSgt4IWLMXljtHBA8tfBCD12DFQIej+5zBMnjxa9ONML47yZpX6qQIDAQABAoIBAAstj5Oe9cUh
      BQ3icbpR/bHn+sNZoCgI/Ns+gmeTc9GCwBEoSyBmA6in7t08ksCHIRNiWasL+AxA2vuKbxW3oeGZ
      VX5prlqB8AK0N4qRqw4tB+N/3Kn4639obaG2IQ56WoBMeHSzBD/3nLya/5Ixg4PRvp2UpIXbSBfB
      VGpHKr2tq0O4NHGfvNL5OQeI7bXFcDvgiRMTcmY0T0OcU3s2cROnMTgCjMiHSUwZqgaWYKxNCo0v
      jP8CgAHKOj4nNOJwbVcXxmClQocQwnwkyWKuCNWQaPb2js8u9xdekLS6/B+LQYrBfGjR4uFAfWgp
      IS30h+Ws8qplM4ryafHAFBcA14ECgYEAvWtzb6yrwJ6DgANiubhXSlP25z5Mh5O1vFkgYTcJCy4f
      1/u5Rnkeg5ZNNwl/iSVqrv1VT0JdD/HYAhY8iWAJApyYX/xbKilzd33iQtKQjj4uDQAkWRm56FjE
      eKs27u3vppWMLs4d2AAUZSba8gNBmcvNp+WubK2gEZSNBynBz7ECgYEAtV0zLI75LvaCXfk9yPIs
      4xCiwKk6oXncpOVGn0F8D+Y+ywogU3GPPxJQ1HL/WEt0qFt7KIenCLHppOsLSkgSrBM2l5KJBbpA
      3kVwfFTZPubedXHr1usGX/cKO37fZTdE3gqHH2VzND1WZNy8rTpJ5Kbbwd+fzPnXSBqDl1ar0HkC
      gYBmJp9fV0BcpV+HVswUGizBAd0CQh+lcewtQedrZfGznNFBehglwEXLcu/7QV0NCiepbSdnkgN8
      CNGT9of5EdhqFyc5hG9pomcJxtKRdNrOSwwsqKnxfyU5/z0dUkBSw/Bc5wNtbmy7wvc8waKLp2Pm
      W/lxlTTmmQ/cyz7u4P8LUQKBgQCywG4cn7nnWJz7JBmKQW6OSaove1vHJUWb3EIz2qX9QbBoC836
      kDVgM5wpGEKlcpFDEg8bzj+KKVgf7G2PQ+PrZ3BqCco1M/KVYBlS4YnRHljppmOMys3YrbKPGyfx
      KX0d34B4KFRYi4/oD0uC7K1ByFdWCSMGMsTFUySZd5oV+QKBgBop5BJF1e0qw2virzT7ZRbrrsVP
      IBk3hbF/UJ7zaF/pGynZmyjW1zBkO29c7zJxaCqnPdOCGibyFNTfcXNPw3jJcEPzzNa3TtrQLP8Z
      cBzOTY3vQeGxRW5wjIqg98ST3GzN4C2Rd+PpSFS6OvG9CYqBVl1mdde00nyVbcXPNkRv
      -----END RSA PRIVATE KEY-----

  networks:
  - name: first-network
    identifier: {{ private_subnet_id }}
    subnet: 10.0.16.0/20
    reserved_ips: 10.0.16.2-10.0.16.4
    dns: 10.0.0.2
    gateway: 10.0.16.1

  elastic_runtime:
    name: cf
    system_domain: cherry.cf-app.com
    apps_domain: cherry.cf-app.com
    elb_name: cherry-pcf-elb
    elb_dns_name: {{ ert_elb_dns_name }}
    ssh_elb_name: cherry-pcf-ssh-elb
    ssh_elb_dns_name: {{ ert_ssh_elb_dns_name }}
    file_storage:
      endpoint: https://s3-us-west-1.amazonaws.com
      bucket: {{ ert_s3_buildpacks_bucket_name }}
      buildpacks_bucket: {{ ert_s3_buildpacks_bucket_name }}
      droplets_bucket: {{ ert_s3_droplets_bucket_name }}
      packages_bucket: {{ ert_s3_packages_bucket_name }}
      resources_bucket: {{ ert_s3_resources_bucket_name }}
      access_key: {{iam_aws_access_key_id}}
      secret_key: {{iam_aws_secret_access_key}}
    rds:
      host: {{rds_address}}
      port: {{rds_port}}
      username: {{rds_username}}
      password: {{rds_password}}
    smtp:
      from: identitystaging@mailinator.com
      address: smtp.sendgrid.net
      port: 587
      credentials:
        identity: PCFRelEng
        password: 4H-9Lh-wD{ZST28x{Q
      enable_starttls_auto: true
      smtp_auth_mechanism: plain
    ssl_certificate: |
      -----BEGIN CERTIFICATE-----
      MIID8jCCAtoCCQDx6PcWd2j6KzANBgkqhkiG9w0BAQUFADCBujELMAkGA1UEBhMC
      VVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBGcmFuY2lzY28x
      EDAOBgNVBAoTB1Bpdm90YWwxHDAaBgNVBAsTE1JlbGVhc2UgRW5naW5lZXJpbmcx
      HDAaBgNVBAMUEyouY2hlcnJ5LmNmLWFwcC5jb20xMDAuBgkqhkiG9w0BCQEWIWNm
      LXJlbGVhc2UtZW5naW5lZXJpbmdAcGl2b3RhbC5pbzAeFw0xNTA3MTYxNzI4NTNa
      Fw0xNjA3MTUxNzI4NTNaMIG6MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZv
      cm5pYTEWMBQGA1UEBxMNU2FuIEZyYW5jaXNjbzEQMA4GA1UEChMHUGl2b3RhbDEc
      MBoGA1UECxMTUmVsZWFzZSBFbmdpbmVlcmluZzEcMBoGA1UEAxQTKi5jaGVycnku
      Y2YtYXBwLmNvbTEwMC4GCSqGSIb3DQEJARYhY2YtcmVsZWFzZS1lbmdpbmVlcmlu
      Z0BwaXZvdGFsLmlvMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1UCL
      puxOE3SQm/LrbMjowRpvzsRh/z+wcNL32tsKjCk/XNFqB1L8LoD8XfHPIlRu+bfJ
      zIw4Lxwe59DwB7rceFayTcLHOwZRuhiMYD82Bss7sQa2DbKfBSMKpnTEC7g/8XVi
      i6Tf97OSD0lhA8KI5p+wBmSnld483kQNjQvBhFoZz7Jk9jHI83gWV1ic78aD+d+T
      frSyJ2hoHVFqSN8kQjlR/B5PRimPrK+MIPBosJKjq6+nBMX+01Qi2zGfjE6bQCYW
      kXXvCFd30TtuBgWOg9KnPyspZmG43o4UcMlmGAX0VlKLAzlXS8nk36bB37RWqggl
      NyIWAh94LQWBRnO40wIDAQABMA0GCSqGSIb3DQEBBQUAA4IBAQCl7r5Zk0vNPw2E
      mWv/iRKElotinKqyi2mZddbJnlxF7+F/JrZotLR5B9Ion9uccXfHK1SxJJjZxgVv
      t5CrF4WUD+L0FQPKDx51I1/sovtZ7SSjrQnT+9tLTovyHNx470bTLWvU93TFGOUg
      m9Q9b5obmbU/54Ys5J71la7h8Mnlb+JqQZyWWgK3zLOeh0v5tlmfHRFjXeju7LV7
      KyoEZABLljH9/xHQZEn1JZURkbkBAnMbmaLXkL6AffjjeU0uNCKaV7KUaG5fgc/6
      hxJSZ+NpIiQfNn19ShR4quEaskiciNzYy5Yd3oC1C6B4628wqOv0VJjp3J+0ZnX3
      k0pBNDSE
      -----END CERTIFICATE-----
    ssl_private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEogIBAAKCAQEA1UCLpuxOE3SQm/LrbMjowRpvzsRh/z+wcNL32tsKjCk/XNFq
      B1L8LoD8XfHPIlRu+bfJzIw4Lxwe59DwB7rceFayTcLHOwZRuhiMYD82Bss7sQa2
      DbKfBSMKpnTEC7g/8XVii6Tf97OSD0lhA8KI5p+wBmSnld483kQNjQvBhFoZz7Jk
      9jHI83gWV1ic78aD+d+TfrSyJ2hoHVFqSN8kQjlR/B5PRimPrK+MIPBosJKjq6+n
      BMX+01Qi2zGfjE6bQCYWkXXvCFd30TtuBgWOg9KnPyspZmG43o4UcMlmGAX0VlKL
      AzlXS8nk36bB37RWqgglNyIWAh94LQWBRnO40wIDAQABAoIBAEfTt7X/fcS7zEFa
      rsUzXoI8H1CrgL5ye0FlLap/gKv48KiYuHfDEcGwHFCgM75CZiaiKsxEpl/nvtkh
      3Ncdr0ixGtlqM6TD2h8uSYnZgJ8FMRPNSOCQO1OFm/648Zdo9dCkUw7p9638w8N2
      WcDkcywKuUVN/cxS0HmkvlO1k/a5rPOsnU6NBr+TXxiWCGybrH73F4CAjKH9O07Q
      crGkSzHM72z2+iTjxrukq+15fj2w5a83G3suXwv3iIxJ96stpzf6IqdTW9QYWBq/
      xDFGSws+qUtpZa5/djXsGEBuA/07fKMsJdH9n8ht0kj6Kk8ppjhb9Tvmjxwe0b+N
      JIPf5VECgYEA7Ea6qyK9+iKkIW9LeFgEMv1hJ8TIYBDNHR2G6v/sKv0yfCKAU6+R
      6i8ZAIq11xa71BTgLGQ2WOZs+cNJkZwsyW3wAOrAKp3isgyqIYWlM1fbsTzLoPxf
      X8mValrJAVKOufsi1GpDojwPUlBLAofooG89DI4OpM6/BOXyH915vn0CgYEA5w3J
      HcgbNlOlDJa3tIIv1DbtE8zBsuWTFxbBsF0p17qfU4sZLiGNg8WvIvocpp/zBd0I
      7JpG7hp5Te27hWaSeMH7grgPPTJwXPwS8kMRMFwS7XMXaGgYDM06AHrrKmYkPSHF
      NwB2BeT2XDSdjyECpOFCe/VpgYuKaTrjXd9nZY8CgYAZ6wRNA4mdZ7FjbYb004ra
      YQsIRsDIMO+fEv8axioM6SthjJNRGsBB1RrEAXNC/d5qvEN++xsvE0++8hoe2+fZ
      zLJ4F0gvJJSafWMoPDXL9QZHYejgZu67XiyCtyS3fWvkoNTIQkPbBwWTPPWNeIUf
      HDSxLOAUWg2AJw0xS6UwLQKBgAJ+/6E2vDSGCs5sAmgMz/926HDCUYVhPYmOUWFa
      YE1YUshQRGFfM2wtAotaMF0MdU+m56XGtOV1m8Hfw5rZVNPBJLpwyplapiQbBQlg
      +BqRpBK0n5gdJ8VbojjHGytGFzYh20OQ2bWOl6q/VsRpEuI9HL7CE/W2UDR60mH9
      O9y5AoGAclCuzthGmJNHYvGtk2TbfuIY7IgietC209/WLJG49DdJ1DnNdkhwrwOy
      TecCbJv1uRkO5LDaVkAd5IFqkbChJoqMh/J0Kc1C5acogR3sggg+IuWxkF0NVU9f
      CxwGzoG2nU8M7fMjjOrN//lXc0PjBF42ydgPtKZnwiZs5pW0Lgk=
      -----END RSA PRIVATE KEY-----
    trust_self_signed_certificates: true
