---
name: deer
iaas_type: vsphere
vm_shepherd:
  vm_configs:
  - vcenter_creds:
      ip: 10.84.32.61
      username: root
      password: look74Beer
    vsphere:
      host: vcenter
      resource_pool: deer
      datacenter: private
      cluster: private
      datastore: private
      network: deer
      folder: deer
    cleanup:
      datacenter: private
      datastores:
      - private
      datacenter_folders_to_clean:
      - deer
      - deer_vms
      - deer_templates
      datastore_folders_to_clean:
      - deer
      - deer_disk
    vm:
      ip: 10.85.15.16
      gateway: 10.85.15.1
      netmask: 255.255.255.0
      dns: 10.87.8.10,10.87.8.11
      ntp_servers: time1.sf.cf-app.com
      vm_password: pivotalcf
ops_manager:
  url: https://pcf.deer.wild.cf-app.com
  username: pivotalcf
  password: wilderror16
  ntp_servers: time1.sf.cf-app.com
  vcenter:
    creds:
      ip: 10.84.32.61
      username: root
      password: look74Beer
    datacenter: private
    datastore: private
    microbosh_vm_folder: deer_vms
    microbosh_template_folder: deer_templates
    microbosh_disk_path: deer_disk
  availability_zones:
  - name: first-az
    cluster: private
    resource_pool: deer
  networks:
  - name: first-network
    identifier: deer
    subnet: 10.85.15.0/24
    gateway: 10.85.15.1
    reserved_ips: 10.85.15.0-10.85.15.90
    dns: 10.87.8.10,10.87.8.11
  elastic_runtime:
    name: cf
    ha_proxy_static_ips: 10.85.15.254
    system_domain: sys.deer.wild.cf-app.com
    apps_domain: apps.deer.wild.cf-app.com
    smtp:
      from: identitystaging@mailinator.com
      address: smtp.sendgrid.net
      port: 587
      credentials:
        identity: PCFRelEng
        password: 4H-9Lh-wD{ZST28x{Q
      enable_starttls_auto: true
      smtp_auth_mechanism: plain
    trust_self_signed_certificates: true
