---
name: dog
iaas_type: vsphere
vm_shepherd:
  vm_configs:
  - vcenter_creds:
      ip: 10.84.32.61
      username: root
      password: look74Beer
    vsphere:
      host: vcenter
      resource_pool: dog
      datacenter: private
      cluster: private
      datastore: private
      network: dog
      folder: dog
    cleanup:
      datacenter: private
      datastores:
      - private
      datacenter_folders_to_clean:
      - dog
      - dog_vms
      - dog_templates
      datastore_folders_to_clean:
      - dog
      - dog_disk
    vm:
      ip: 10.85.18.16
      gateway: 10.85.18.1
      netmask: 255.255.255.0
      dns: 10.87.8.10,10.87.8.11
      ntp_servers: time1.sf.cf-app.com
      vm_password: pivotalcf
ops_manager:
  url: https://pcf.dog.wild.cf-app.com
  username: pivotalcf
  password: pivotalcf
  ntp_servers: time1.sf.cf-app.com
  vcenter:
    creds:
      ip: 10.84.32.61
      username: root
      password: look74Beer
    datacenter: private
    datastore: private
    microbosh_vm_folder: dog_vms
    microbosh_template_folder: dog_templates
    microbosh_disk_path: dog_disk
  availability_zones:
  - name: first-az
    cluster: private
    resource_pool: dog
  networks:
  - name: first-network
    identifier: dog
    subnet: 10.85.18.0/24
    gateway: 10.85.18.1
    reserved_ips: 10.85.18.0-10.85.18.90
    dns: 10.87.8.10,10.87.8.11
  elastic_runtime:
    name: cf
    ha_proxy_static_ips: 10.85.18.254
    system_domain: sys.dog.wild.cf-app.com
    apps_domain: apps.dog.wild.cf-app.com
    smtp:
      from: identitystaging@mailinator.com
      address: smtp.sendgrid.net
      port: 587
      credentials:
        identity: PCFRelEng
        password: 4H-9Lh-wD{ZST28x{Q
      enable_starttls_auto: true
      smtp_auth_mechanism: plain
    trust_self_signed_certificates: true
