vcloud_creds: &vcloud_creds
  url: https://p3v13-vcd.vchs.vmware.com
  organization: VDC-M127900816-4614-483
  user: cf-release-engineering@pivotal.io
  password: NmJSSDasP$2$

name: e40
iaas_type: vcloud
vm_shepherd:
  vm_configs:
  - creds:
      <<: *vcloud_creds
    vdc:
      name: RELEASE-ENGINEERING
      catalog: e40-releng-ops-manager-catalog
      network: E40-NETWORK
    vapp:
      ops_manager_name: e40-releng-ops-manager
      product_catalog: e40-releng-cf
      product_names:
        - e40-releng-cf_cf
        - e40-releng-cf_p-bosh
      ip: 192.168.129.2
      public_ip: 107.189.121.227
      gateway: 192.168.129.1
      dns: 8.8.8.8
      ntp: us.pool.ntp.org
      netmask: 255.255.255.0

ops_manager:
  url: https://pcf.e40.cf-app.com
  ip_address: 107.189.121.227
  username: pivotalcf
  password: wilderror16
  ntp_servers: us.pool.ntp.org
  vcloud:
    creds:
      <<: *vcloud_creds
    vdc:
      name: RELEASE-ENGINEERING
      storage_profile: SSD-Accelerated
      catalog_name: e40-releng-cf
  networks:
    - name: first-network
      identifier: E40-NETWORK
      subnet: 192.168.129.0/24
      reserved_ips: 192.168.129.0 - 192.168.129.99
      dns: 8.8.8.8
      gateway: 192.168.129.1

  elastic_runtime:
    name: cf
    ha_proxy_static_ips: 192.168.129.3
    system_domain: sys.e40.cf-app.com
    apps_domain: apps.e40.cf-app.com
    smtp:
      from: identitystaging@mailinator.com
      address: smtp.sendgrid.net
      port: 587
      credentials:
        identity: PCFRelEng
        password: 4H-9Lh-wD{ZST28x{Q
      enable_starttls_auto: true
      smtp_auth_mechanism: plain
    trust_self_signed_certificates: true
