name: fig
iaas_type: aws
vm_shepherd:
  env_config:
    stack_name: fig
    aws_access_key: AKIAI43577ARGHXPWIMQ
    aws_secret_key: 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
    region: us-west-1
    json_file: config/ert_cloudformation.json
    parameters:
      01NATKeyPair: releng-dev-west
      05RdsUsername: pivotalcf
      06RdsPassword: pivotalcf
      07SSLCertificateARN: arn:aws:iam::491337929596:server-certificate/fig
    outputs:
      ssh_key_name: releng-dev
      ssh_key_name: {{ssh_key_pair_name}}
      security_group: {{ops_manager_security_group_id}}
      public_subnet_id: {{public_subnet_id}}
      private_subnet_id: {{private_subnet_id}}
      s3_bucket_names:
        - {{ s3_bucket_name }}
        - {{ ert_s3_bucket_name }}
  vm_configs:
    - vm_name: Fig OpsManager
      vm_ip_address: 52.8.136.254

ops_manager:
  url: https://pcf.fig.cf-app.com/
  username: pivotalcf
  password: pivotalcf
  ntp_servers: 0.amazon.pool.ntp.org
  availability_zones:
  - iaas_identifier: us-west-1b

  aws:
    aws_access_key: {{iam_aws_access_key_id}}
    aws_secret_key: {{iam_aws_secret_access_key}}
    vpc_id: {{vpc}}
    security_group: {{vms_security_group_name}}
    key_pair_name: {{ssh_key_pair_name}}
    region: {{region}}
    ssh_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEAhjHuhEToOnffT0anE3LAu9ijudz+P7yzVmXW7Ignn+RP56GpFswvBS+rdMoF
      9d13dzom/QdR76EMch16uz0V3SrFyphB2XdHQ34cvJMjlgVxXsNfVHA96rTIP5QVaaB5TRgXsKD8
      /3pJ0q/dWoLq0a4MQT48DI8HCTYT9XnVjYHYJGZHKEj+5ztr4T0CuOuIwmElJJAXu33ooEDJZPYK
      57z7zfy3RtSs0t40A/KJN12fY2ra25P4k7q2o47349Hz+aBsHK9YMAQhGGdPwNOe4yw8Qt1LuK1B
      hxSgt4IWLMXljtHBA8tfBCD12DFQIej+5zBMnjxa9ONML47yZpX6qQIDAQABAoIBAAstj5Oe9cUh
      BQ3icbpR/bHn+sNZoCgI/Ns+gmeTc9GCwBEoSyBmA6in7t08ksCHIRNiWasL+AxA2vuKbxW3oeGZ
      VX5prlqB8AK0N4qRqw4tB+N/3Kn4639obaG2IQ56WoBMeHSzBD/3nLya/5Ixg4PRvp2UpIXbSBfB
      VGpHKr2tq0O4NHGfvNL5OQeI7bXFcDvgiRMTcmY0T0OcU3s2cROnMTgCjMiHSUwZqgaWYKxNCo0v
      jP8CgAHKOj4nNOJwbVcXxmClQocQwnwkyWKuCNWQaPb2js8u9xdekLS6/B+LQYrBfGjR4uFAfWgp
      IS30h+Ws8qplM4ryafHAFBcA14ECgYEAvWtzb6yrwJ6DgANiubhXSlP25z5Mh5O1vFkgYTcJCy4f
      1/u5Rnkeg5ZNNwl/iSVqrv1VT0JdD/HYAhY8iWAJApyYX/xbKilzd33iQtKQjj4uDQAkWRm56FjE
      eKs27u3vppWMLs4d2AAUZSba8gNBmcvNp+WubK2gEZSNBynBz7ECgYEAtV0zLI75LvaCXfk9yPIs
      4xCiwKk6oXncpOVGn0F8D+Y+ywogU3GPPxJQ1HL/WEt0qFt7KIenCLHppOsLSkgSrBM2l5KJBbpA
      3kVwfFTZPubedXHr1usGX/cKO37fZTdE3gqHH2VzND1WZNy8rTpJ5Kbbwd+fzPnXSBqDl1ar0HkC
      gYBmJp9fV0BcpV+HVswUGizBAd0CQh+lcewtQedrZfGznNFBehglwEXLcu/7QV0NCiepbSdnkgN8
      CNGT9of5EdhqFyc5hG9pomcJxtKRdNrOSwwsqKnxfyU5/z0dUkBSw/Bc5wNtbmy7wvc8waKLp2Pm
      W/lxlTTmmQ/cyz7u4P8LUQKBgQCywG4cn7nnWJz7JBmKQW6OSaove1vHJUWb3EIz2qX9QbBoC836
      kDVgM5wpGEKlcpFDEg8bzj+KKVgf7G2PQ+PrZ3BqCco1M/KVYBlS4YnRHljppmOMys3YrbKPGyfx
      KX0d34B4KFRYi4/oD0uC7K1ByFdWCSMGMsTFUySZd5oV+QKBgBop5BJF1e0qw2virzT7ZRbrrsVP
      IBk3hbF/UJ7zaF/pGynZmyjW1zBkO29c7zJxaCqnPdOCGibyFNTfcXNPw3jJcEPzzNa3TtrQLP8Z
      cBzOTY3vQeGxRW5wjIqg98ST3GzN4C2Rd+PpSFS6OvG9CYqBVl1mdde00nyVbcXPNkRv
      -----END RSA PRIVATE KEY-----

  networks:
  - name: first-network
    identifier: {{ private_subnet_id }}
    subnet: 10.0.16.0/20
    reserved_ips: 10.0.16.2-10.0.16.4
    dns: 10.0.0.2
    gateway: 10.0.16.1

  elastic_runtime:
    name: cf
    system_domain: fig.cf-app.com
    apps_domain: fig.cf-app.com
    elb_name: fig-pcf-elb
    elb_dns_name: {{ ert_elb_dns_name }}
    file_storage:
      endpoint: https://s3-us-west-1.amazonaws.com
      bucket: {{ ert_s3_bucket_name }}
      access_key: {{iam_aws_access_key_id}}
      secret_key: {{iam_aws_secret_access_key}}
    rds:
      host: {{rds_address}}
      port: {{rds_port}}
      username: {{rds_username}}
      password: {{rds_password}}
    smtp:
      from: identitystaging@mailinator.com
      address: smtp.sendgrid.net
      port: 587
      credentials:
        identity: PCFRelEng
        password: 4H-9Lh-wD{ZST28x{Q
      enable_starttls_auto: true
      smtp_auth_mechanism: plain
    trust_self_signed_certificates: true
    ssl_certificate: |
      -----BEGIN CERTIFICATE-----
      MIIFaDCCA1ACCQCghFnCHsIfbzANBgkqhkiG9w0BAQUFADB2MQswCQYDVQQGEwJV
      UzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDVNhbiBGcmFuY2lzY28xEDAOBgNVBAoT
      B1Bpdm90YWwxMDAuBgkqhkiG9w0BCQEWIWNmLXJlbGVhc2UtZW5naW5lZXJpbmdA
      cGl2b3RhbC5pbzAeFw0xNTA2MjUyMjQwNTNaFw0xNjA2MjQyMjQwNTNaMHYxCzAJ
      BgNVBAYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UEBxMNU2FuIEZyYW5jaXNjbzEQ
      MA4GA1UEChMHUGl2b3RhbDEwMC4GCSqGSIb3DQEJARYhY2YtcmVsZWFzZS1lbmdp
      bmVlcmluZ0BwaXZvdGFsLmlvMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
      AgEA6jhTLbucbuU+Hz7DSd5I5T9cNDTwQPc25GwsNqG2eSEz9yf9GeDwUnnZ7snd
      Hi6A0rsvuZtSLYRJmtz90TQySNKJDJcRVml8HqkzTmuUpDXO/qJLJiDUIJpzY/ro
      1Zs6y/XuULiaGhPYgl71OJ9bPtu3jy7LUNUkGhkDRtSBWQruvkLCftIIEmY0Dw1E
      4qf0WCHGssXZT2PxFQZqPM7TfgW7zmZb5o/xrmBjWkgCgqtApdoAQHJNsKJCtZVe
      riHRc2uWPfd+tX7V3aqmE3jWyGShS7RVekpWcTK/3BUMjPQAxl8rr7UfoT/FcPR1
      vbPTpwDHGBYUwm35BnePRY4L9pZkGoB0RsJMYMY/z2fKhVaenR5hqx/yMowEY6pN
      D6DMijIkMGwpFHqI8ajuPVYfJDwxbmIO+wMsQn+4a4kXqvM3Qxd9IZWvhobT22j3
      fdZJ7AnmPvMhiog/p1IfxljMHlbAUXQ/vCGxMcYvbwyhJUUE/r5YaCkXP5VpxiQ2
      sWyMtmT/h+lSEVqCBUuz5Gkd5pvfCcLIG6Q0FkzlCA5JPfFGkTKCCySJHx/qeLDx
      71Bktrk1SoSEFXOqXdEMQC7p80Ba0XEmUep543pSExaqBKGeZ8PQND0pn+4psm2Q
      LbC97V35hEKbijaMfn8azDkDxnEEUjtOj+V8MIGRPYrznj8CAwEAATANBgkqhkiG
      9w0BAQUFAAOCAgEA0TV/tlSI7etmcyey9Gioy4/5oOlIJtOkdkqaO/C/3MSmCAy8
      xG3yK4WGBfojOYNuRjJ8nMCg0v8JyT3Q7TCSTHEQriTFG/coqoMatk5giWXynzYV
      NynGQKp+enosaq2fHVe5Myb2V4AJ9p10AVqiCYe1C/3hgBZi7pg2whE/BQoh3lQv
      auIfvMolofdgp0jA13j+mrhALpzG3RWA/bgG8ua4lKIOLqHh1ZL+u1bOPUdPAwZZ
      ynv4yczpyYkC2Ay8Gx21lpospE4AAfbd3tUJ5RBraLSNtYg9xGBQZ0WymGRcJD/R
      TbHI5JuzhlPCP2UzmLOCvzOrJy2fEoSGPBuNMjxp2JEELriWiAT5TLUUO1RgVixf
      FKoIjZHcFlSKxr4ds4+DwdNL+Ay3pFZt+Hq+gr7KWMPx4sstnj/Kg6z4HEjl6v1l
      EYn68Yp4H/+SC9b8okAKEn1PamjbyZ/CUQ5FBydgxWYxiEtgP+4uEOAxTtjsq4K0
      ozaJganXsw/kMeTd6GC9qp2jco+wN+i5yE/tELIWiwN2wC+IvdMe6t6nP9qi0ci3
      j4NBQA/45fqLDmpZqmSwkhl4NvTfRkZF7v2xK58mvQsCKYzwrW12Pf0LQlvM0KAV
      Zg8d6lAvUwCBn/0nguDQGWK3etAFVE7OKNN1z7LK/dXfW4uMi5K7swYeJJs=
      -----END CERTIFICATE-----
    ssl_private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIJKgIBAAKCAgEA6jhTLbucbuU+Hz7DSd5I5T9cNDTwQPc25GwsNqG2eSEz9yf9
      GeDwUnnZ7sndHi6A0rsvuZtSLYRJmtz90TQySNKJDJcRVml8HqkzTmuUpDXO/qJL
      JiDUIJpzY/ro1Zs6y/XuULiaGhPYgl71OJ9bPtu3jy7LUNUkGhkDRtSBWQruvkLC
      ftIIEmY0Dw1E4qf0WCHGssXZT2PxFQZqPM7TfgW7zmZb5o/xrmBjWkgCgqtApdoA
      QHJNsKJCtZVeriHRc2uWPfd+tX7V3aqmE3jWyGShS7RVekpWcTK/3BUMjPQAxl8r
      r7UfoT/FcPR1vbPTpwDHGBYUwm35BnePRY4L9pZkGoB0RsJMYMY/z2fKhVaenR5h
      qx/yMowEY6pND6DMijIkMGwpFHqI8ajuPVYfJDwxbmIO+wMsQn+4a4kXqvM3Qxd9
      IZWvhobT22j3fdZJ7AnmPvMhiog/p1IfxljMHlbAUXQ/vCGxMcYvbwyhJUUE/r5Y
      aCkXP5VpxiQ2sWyMtmT/h+lSEVqCBUuz5Gkd5pvfCcLIG6Q0FkzlCA5JPfFGkTKC
      CySJHx/qeLDx71Bktrk1SoSEFXOqXdEMQC7p80Ba0XEmUep543pSExaqBKGeZ8PQ
      ND0pn+4psm2QLbC97V35hEKbijaMfn8azDkDxnEEUjtOj+V8MIGRPYrznj8CAwEA
      AQKCAgBI/v7lbOgnI6kFweDJP87GK8YHu0v5Y1KnRBNPf3zIKZHxgHQAQbuEaNeD
      9UPFqUaa5p3MId0ttGHgMumj7rmROpRd6SMNJFj7kU4dLagouWBmuZvkKS0TcC9w
      RH2WPQfJEz+Pxsi4QeEjWIbie7/LSlzd8f6JlbPnsk30IDyjzKV1hIbrUXgUi+fD
      nSYP4bpkUTqE8uZ0OLilDdfEVc1SJGVQwVP4+nmfGAk+1Nx7bvX5+oRDkZwm5ZsW
      zpOwf3ewmiI788t4syviJtIVlX6S+9HNL0nIkCx6oQ9sft7nexBWwshxvWg7MA3P
      01Byq/3VuYdTOWaE5hNLca2kRs3xFk5m8epqsRjQ3G/gCx8PacpW4AgpDOWPFAjX
      8V21VkaH0WmY8bMEqJc3bW2+t2CslUIelbRBXkdxhAgdl5cC9n5scv3k0bk9xLv6
      Pg4SztBQ6hjw3cycwebQ02Drlmg6Zp2cqa6RRsT5IpPnZwpPv3/SWfcJu8eObgC8
      BoYo0dH99/CMbTWNSTfjgArmzAfyvuaUc6QEtDGVBKwVbe6wZC6UFGPocVri97u/
      pbz2pTvGPs56UMaoBlBf/Ci8/BSO71T4iFG5CEnsC8k4FvlHNRSo6N/YwLP5wW3e
      CglNCgfblTc0SWHPUCSoVO0muflzqEUMgvWWtmW+GjEx1NcisQKCAQEA/5SRZOI+
      rUJxCUtDLrVVMJsr37Bwfcip1okbtkzWkCf2uj+HXf3wKSlb4nFMATBsirAHKf5K
      zkhy1dUP65nDSzRb0JgiSBwaXy2Hf+1WA0QEZNpsImqFTsZsr/pXWFBLPB3vwt7/
      dORVCAahDxeVnlJYCEo82nZwGGp8i9aAycV43ruw/2tspPj6YNN71QDdh9kP3m8b
      /a4el8Bjibn9gajDDtrq2QPZpwX6cRlPntNGrINpL4rZzJUdc7yJUjJQIRuwWMnO
      wMv1n3lTWMNrbkUdkuV53bbW4bMwgmiiVJmkN3deZ+7RJ9Y7dzGCI7iwsVAts9vP
      ls3bNPOP0sh3hwKCAQEA6prHO6ojgw2L9FhFpV9OMYwp6UMutpWf5rowEunKl/IF
      NkY3yPISVkNYtAlOKsOtbd1zzhUjCIXpXTyjzNyKJhuOzyTFWiit/pe2vOEvS7h8
      4+3rK+QsFb7U9Tj2Ir2Q6m3//UQsXum3SQtdAz5mQT5HLqlwnt1yGwHLOkVNDMce
      HbCwk4TsvjGi7TPsG44qxUUxBlh3yG+ROqzre7JhJoU/npISWrHZfKsycJHEJs1+
      NJFg/yGBlA1J7vsl3M+QUqxjCyw6cT9HHFghUF1Qo4Og7gpUfgvkCoZhu7xBW2dO
      3Wb39gwIW8gkNAx8/kqzdp+j7wM7FlYj3gpOufLhiQKCAQEA1KTIv5YZrc/s+l2b
      PP50Lae9PjSvs4fD/xI+c1PE5VXKyzVWLFa+fZDCuUmoggjHFjDVFRRVKwJOQSkv
      QMfDHAwpJAmf5D01l+Dqrv5JpRfvS/YLKCtWVK90+ImiKIFNx2vk807UXm4nbTEO
      yd7Ghl5eji8uKFmIdFgM3dAPgVECetbQsgKv9yaMMwliK1u39XIc6OWq9Ursezf/
      2TRc/obqG6763Kp+aZ/oujbj7vI8CAah+oNdKQEb6xJ/clsYHiPKemUV14UbDJ9G
      QED/XlS1AWZaGaUpbcnH34itHxRh9CAl9PVXIfz1pvsTGyNsJ2rdS5rkQcVuz8Sh
      8i8GewKCAQEApXc7FALg/xq73j+wB35buSiBmurudIq9d89T/tL0OAzTzj7iM5FA
      i6T+WCTEA/d1R6rMdcqEpgtE16TgZqoZqdz/8Wue4gMVDR7WHQu5/u8E7wGsP42z
      5jZtHvPo7gHDxwSEa438uYif5B3moVYOau/Q5sFNFE9dnly6iMO+H0gFHq2zLKix
      DUgXALQBUEIKOo6dkDsvaKf/x2GUyO68BJ4wi9e8qEkN+xcIAUteDHwdCliLEAcC
      zHg+8BYk00N2KEk7pfKw2ZTmw8AI5xSZvmolRB73Dtu2IBI9tlqFwkDv58orE1fT
      QWC84BT6x6PKRd08k2Q09YEV1RJyCkaa+QKCAQEAlz2MaSn6ZtA8htyXDSXpGb8Z
      zvAX32Fb0x46lhNo5Oi1/TYFO7D5fMU5VQxxxy5fXRli+dh/ysUlT8CB64sxTi0u
      TDkQ6nY6zVPJBs+BJkERqvrzu1FMdCxmnR3WwdGzWbVJsE0+1uwUdQ5tRm+RV816
      kpfwJ5QpaYXsI8OvuIkTccPO0ApuNT/EAOA0leATVlEBLcEcNofnfwNCGFlE6zim
      qadV9kYYTDA5hNhAnFSnkceXccVYacKtFjNuHMvkJH1SV6b3xYlZPuYxSkCJ7XgP
      Ay5rAPZv6/EOaTWsaCjMRY2Z7MTHGWgdiVlhWhUjM4Q/dHkr1TbnGJwEzRizWA==
      -----END RSA PRIVATE KEY-----
