name: grape
iaas_type: aws
vm_shepherd:
  env_config:
    stack_name: grape
    aws_access_key: AKIAJEAGY2FWB7DEGFXQ
    aws_secret_key: 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
    region: us-east-1
    json_file: config/ert_cloudformation.json
    parameters:
      01NATKeyPair: releng-dev
      05RdsUsername: pivotalcf
      06RdsPassword: pivotalcf
      07SSLCertificateARN: arn:aws:iam::491337929596:server-certificate/grape
    outputs:
      ssh_key_name: {{ssh_key_pair_name}}
      security_group: {{ops_manager_security_group_id}}
      public_subnet_id: {{public_subnet_id}}
      private_subnet_id: {{private_subnet_id}}
      s3_bucket_names:
        - {{ ops_manager_s3_bucket_name }}
        - {{ ert_s3_bucket_name }}
  vm_configs:
    - vm_name: Grape OpsManager
      vm_ip_address: 52.3.141.60

ops_manager:
  url: https://pcf.grape.cf-app.com
  username: pivotalcf
  password: wilderror16
  ntp_servers: 0.amazon.pool.ntp.org
  availability_zones:
  - iaas_identifier: us-east-1a

  aws:
    aws_access_key: {{iam_aws_access_key_id}}
    aws_secret_key: {{iam_aws_secret_access_key}}
    vpc_id: {{vpc}}
    security_group: {{vms_security_group_name}}
    key_pair_name: {{ssh_key_pair_name}}
    region: {{region}}
    ssh_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpAIBAAKCAQEAhU5ETA/Pt42waL2WDKLBfhIXlaQ3YHem3Tojn044bs3GpGBWeHESchL6Ndjv
      Q8ANoeEJ3/P9AsCZTkd3GP+c8JRUcdvg61wIipzP0ltK1KbVt1N0z/E29c+nTqwM4o4zBUQMT3vj
      oG0Yf6iIx+88OcYRx7wUuUGb1NBXkn/GqnadfMO2g//i8UOF1tcz/jXdxf7i192aGPxeC/5bl70h
      Gnk/PlsZjYrq/cDqX4uI3ZdWC2Dsp6pbHilx1umB8FNHUOzh7yvaF4380y3t5I4oPRlD/8hMz/5L
      1R5GsMYHibkLgq48mjVgTsN3tMJU1DZUf6eHx7dqay7hr35vZFER3wIDAQABAoIBADe9OSuAtP7w
      HOI+253e8/8N+5STfKA2h6wbIkf7Qfd6zWNv8Ngdl3PhYYPgeHMgu9KDMUjWUWW0OKYVlcP7JZkm
      vIR7RvnCmsOyu+ceSxTNybEFEWPdXXi84h0wLZcRlF3QTUFy8QPkegju5HqNGuahXk/g4d1whIMg
      tm1IRj6CDZchKLx3G+Ae+rISf7p+o1pEfEgwMfWcIapa3PD/fwMpfRBwrsWdV9wPn63pzJc7pPFW
      H6y8ZEc2ldsrQThk4f1r0UMUFbD9I0yolVQMDA73ZzvCstamh3E4gga9N4XiUOSoT7JGbXdobumJ
      JLOi3XOmcWJaBl9Ocff9Qpp2UBECgYEAxVL9n3pA3/k+zxh+t0MDWt5SP+gKDbqaXLJl5w7zCuTo
      OFCAKnDxHDSxcbTNarcC32QOjV0F8plkxaNgFP3W9KvPk5mRnfTXJE67GsaOTtj0lYhHpo90NqYe
      U5IH2eA6PHzpmHPdEemQBa5O+mQOFRgvt4iXJaDqfK7Iro3UXicCgYEArPH3ffG14/0LuNq3Mt+E
      CAx0m2tmAIxTfpgd7BXz8scvg0DyGa49/8MO7pPEHrhjaocefuprJph0BawfdIR90GBu/ussuGS3
      pYCcLDTT7ma8bomlOi4apmYNjKUZDijnVFycHxhNfZVg+bzCklMDm3vfPSh1W85JM//sUIosOYkC
      gYBC7cxSzG+2yF6yddd9J4C60I/LV1QZpgJ3kJcZ0StEtbHCcCOYwag2bfUF4VKPcLXLua9p6XR7
      /eV9V9XeKN9BLAmDQeJvVj2m9gFmqpRYUCRdl9TdvOipJJ1CsVRyZSi7nY7KA/qm+ba9BouJSGiy
      ZPrCYNULkVIXql0tP7QZnwKBgQCmSjZlhA8Xu80UnkC+ispiDs/kTP0UE9mIhO1ofqdEzh8yPjVL
      Wg3FKaHm5nAR9cupt2gsMmx6/OW6Ook4ONjcjozLUgd6+WTXnvULUHRi66fNRU54xbHcQ45NqMWR
      puTfafi3sV95HDPVjZkspuN2EkJRhOBrOMuMU0y/GExzuQKBgQCbvIkXm3K6ZUCuOSzEHnprRBBt
      /ntsCJQDSBXfrzPTgkBBiMVx3aaJZYnsvxb2+Vl3YYiv/HM/W+rJZsSsbffwAngHNbUfVdlwnayn
      wB5+GnTcHRiog2K6DGyOfn1MXiQg2IX7ZpehJFoucNQ5IG4lioVZSmKwea9d8LFqIajoVA==
      -----END RSA PRIVATE KEY-----

  networks:
  - name: first-network
    identifier: {{ private_subnet_id }}
    subnet: 10.0.16.0/20
    reserved_ips: 10.0.16.2-10.0.16.4
    dns: 10.0.0.2
    gateway: 10.0.16.1

  elastic_runtime:
    name: cf
    system_domain: grape.cf-app.com
    apps_domain: grape.cf-app.com
    elb_name: grape-pcf-elb
    elb_dns_name: {{ ert_elb_dns_name }}
    ssh_elb_name: grape-pcf-ssh-elb
    ssh_elb_dns_name: {{ ert_ssh_elb_dns_name }}
    file_storage:
      endpoint: https://s3.amazonaws.com
      bucket: {{ ert_s3_buildpacks_bucket_name }}
      buildpacks_bucket: {{ ert_s3_buildpacks_bucket_name }}
      droplets_bucket: {{ ert_s3_droplets_bucket_name }}
      packages_bucket: {{ ert_s3_packages_bucket_name }}
      resources_bucket: {{ ert_s3_resources_bucket_name }}
      access_key: {{iam_aws_access_key_id}}
      secret_key: {{iam_aws_secret_access_key}}
    rds:
      host: {{rds_address}}
      port: {{rds_port}}
      username: {{rds_username}}
      password: {{rds_password}}
    smtp:
      from: identitystaging@mailinator.com
      address: smtp.sendgrid.net
      port: 587
      credentials:
        identity: PCFRelEng
        password: 4H-9Lh-wD{ZST28x{Q
      enable_starttls_auto: true
      smtp_auth_mechanism: plain
    ssl_certificate: |
      -----BEGIN CERTIFICATE-----
      MIIDJzCCAg+gAwIBAgIUbdGPesRtBx0BTdUoe/8g5GemLaMwDQYJKoZIhvcNAQEF
      BQAwPDELMAkGA1UEBhMCVVMxEDAOBgNVBAoMB1Bpdm90YWwxGzAZBgNVBAMMEiou
      Z3JhcGUuY2YtYXBwLmNvbTAeFw0xNTA3MjIxNjU3NTBaFw0xNzA3MjExNjU3NTBa
      MDwxCzAJBgNVBAYTAlVTMRAwDgYDVQQKDAdQaXZvdGFsMRswGQYDVQQDDBIqLmdy
      YXBlLmNmLWFwcC5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDO
      i7jsz9+AUx4JDGdCzPsXBeluOD6KyjDTHK75xEcMICmZF3LDes4tOvAZc7hvLxis
      5HFoQfrysqQd053reckfS5X5UPpQPYxBWoIw4NNsnNLlCqIeblKTmAxm27IrhhIg
      FESFfGnFdBgqfbOmOOGmJrEflB5P1Xv7wZ71L5ohxoUhJfEHzvTROWfY+C5jCMb7
      OG/FrFg+PjSLocWVqVIkN50wg4Ig1N0gVIMGd3WrIyw80MfUe+bjgt7Rbb5+r6py
      6JbNuTBbESQm6BeMMt/r110mDr+I5CKZRHPI8AarCw6HgXB75oG2RWiZ9D0CnFJ0
      rFE58ZmQkIxKQtHK2qZVAgMBAAGjITAfMB0GA1UdEQQWMBSCEiouZ3JhcGUuY2Yt
      YXBwLmNvbTANBgkqhkiG9w0BAQUFAAOCAQEAVuZBUCvYY9q+dBuqZJUv0sAR/2PD
      9wktd/H4IEfxjT1QKtgYvbEqp3SQl1qDkGwcX74o3ANLz7pE6GueXogO94hRsHha
      wH2fykXFiSHnX0E/9ptZRJzgIKgeBBZC18TAmzc2rT6otVmxUGFYpqOFnTcp1Bpc
      Fh67CMjNoEKmaaezlayu/XdqWQvCUkWORD8URE7Mey2m7SwCFwWiPLLgelJegk5s
      bP+784D4wsusWNJz6KtI5ZOUd7avoDJnwtPz4BAItESR0xeTDyLd38R+gN1xeOcq
      CitNRR+CNuVRkeOYMHkBweKYUqSdH87bLz0DDB8yPXXMZ+BjRzPDvxfndw==
      -----END CERTIFICATE-----
    ssl_private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEAzou47M/fgFMeCQxnQsz7FwXpbjg+isow0xyu+cRHDCApmRdy
      w3rOLTrwGXO4by8YrORxaEH68rKkHdOd63nJH0uV+VD6UD2MQVqCMODTbJzS5Qqi
      Hm5Sk5gMZtuyK4YSIBREhXxpxXQYKn2zpjjhpiaxH5QeT9V7+8Ge9S+aIcaFISXx
      B8700Tln2PguYwjG+zhvxaxYPj40i6HFlalSJDedMIOCINTdIFSDBnd1qyMsPNDH
      1Hvm44Le0W2+fq+qcuiWzbkwWxEkJugXjDLf69ddJg6/iOQimURzyPAGqwsOh4Fw
      e+aBtkVomfQ9ApxSdKxROfGZkJCMSkLRytqmVQIDAQABAoIBAC8Rqk/VQ3LD/klD
      mVigy+vAPiUPDjmkwCGsHLfwodxCjBhGPrILj2bBUqwKMhKsYewslyeSObULPtlJ
      O2jJNSs7l27cpF6a2BagoKCw652J04m8tZtHuuvFr7XVBTJj+Ed1NvRQmO4Vedhd
      Ew6jUdECakTvBUVeOkXyJt5rPa3KXd6Ms5ErlCVEEY9FjCEzFZdP0jV/RfS4XFSf
      z3LSmpHQNA0HaWySfgc0uUoaY2kl+7eVME8gUFgOP9mz9pEie52BSGH8YDbm5e3R
      GAZHZjoqOfRVtkXE1auQCAfSv0xITziUDGiEnMJyLIVWjrv4CvSpsuugyXhpDAsV
      JGFNNKECgYEA8x/q1BCGRr7+1L0cH4+WWHmTY+6Leq5tG1yqbPR6bs52RlEGWUlp
      bvrXzo14YCRmMdPuaK0hFY6hI8Sp+TkxqEyUtd1TibP8x4OLg0PkzmB2vonDy5tZ
      a0SSb8D/LwW8vZkNpc51vriYmzz5FLYWgVCrCFNnTK4EX0X9erR67UkCgYEA2Xvm
      G/TzQt/ZEBPevf5dP8GbjvIrJGws4yNpKSwyAD6ebPJRoYOVsIV2qbGnG6LtpMOL
      WVZpwazxFy7ppb9hcFCU8pbxT90Axc1+YkaikJD5iCnUzpqT7jEzm7a2sr2iugZG
      CvJC0bbH/QGZ8yuMIEkR1TpUhwpxXBD8e7XB7K0CgYEAzZq9Xa/HzoZxPXncEbi9
      XX8bLVSrsglWjeA05EVwUMrbbSXSZ6nUtxz9allrZmsB3burj+xx4Sgoj/YeBHzg
      yMJStOZCYl7LM/LEBjNhiUI8yW/6G/L5kOSBrm6Zn6uLbQ/FYeYS30J/FDFhN6mx
      qJSOv1DBODCl0+h9r8p3drkCgYBu2q1+4ItCMhFVFZu6ojXrsobVBPEinpT+reUD
      XIicAU8FXzpmpkidcln6wxfXiWOyUQ3tWpOLadh1pa7okjVbZ2eUg4W63H5xVH4w
      H6rrH0phsljLepUemyugGjDjyK9yPJJlL/kJJi6n8rIC9dZ1+mjBk/rT3mnLsMjR
      UeLn/QKBgC32F+3//vWk3qeqguk5pv2ZaOaocMS38ED8hBEQ1+rF9JUM+GdusA+n
      VnO/oBDHEp5Ypz1bkvx7A5RZ6nRoSVRbbEuZfDePdGolKPIR5g+Kt0QXxYljT5S1
      RQACvBgnV17N8QLmYA/32pQNUstumWr2t6kFoRKJNjVh+XzHr0pa
      -----END RSA PRIVATE KEY-----
    trust_self_signed_certificates: true
