---
name: jaqen
iaas_type: vsphere
vm_shepherd:
  vm_configs:
  - vcenter_creds:
      ip: 10.87.41.3
      username: root
      password: look74Beer
    vsphere:
      host: vcenter
      resource_pool: jaqen
      datacenter: pizza-boxes-dc
      cluster: pizza-boxes
      datastore: emc-ds
      network: magneto
      folder: jaqen
    cleanup:
      datacenter: pizza-boxes-dc
      datastores:
      - emc-ds
      datacenter_folders_to_clean:
      - jaqen
      - jaqen_vms
      - jaqen_templates
      datastore_folders_to_clean:
      - jaqen
      - jaqen_disk
    vm:
      ip: 172.16.80.126
      gateway: 172.16.80.1
      netmask: 255.255.254.0
      dns: 10.87.8.10,10.87.8.11
      ntp_servers: time1.sf.cf-app.com
      vm_password: pivotalcf
ops_manager:
  url: https://pcf.jaqen.cf-app.com
  username: pivotalcf
  password: pivotalcf
  ntp_servers: time1.sf.cf-app.com
  vcenter:
    creds:
      ip: 10.87.41.3
      username: root
      password: look74Beer
    datacenter: pizza-boxes-dc
    datastore: emc-ds
    microbosh_vm_folder: jaqen_vms
    microbosh_template_folder: jaqen_templates
    microbosh_disk_path: jaqen_disk
  availability_zones:
  - name: first-az
    cluster: pizza-boxes
    resource_pool: jaqen
  networks:
  - name: first-network
    identifier: magneto
    subnet: 172.16.80.0/23
    gateway: 172.16.80.1
    reserved_ips: 172.16.80.1-172.16.80.126,172.16.80.251-172.16.81.255
    dns: 10.87.8.10,10.87.8.11
  elastic_runtime:
    name: cf
    ha_proxy_static_ips: 172.16.80.250
    system_domain: sys.jaqen.cf-app.com
    apps_domain: apps.jaqen.cf-app.com
    smtp:
      from: identitystaging@mailinator.com
      address: smtp.sendgrid.net
      port: 587
      credentials:
        identity: PCFRelEng
        password: 4H-9Lh-wD{ZST28x{Q
      enable_starttls_auto: true
      smtp_auth_mechanism: plain
    trust_self_signed_certificates: true
