name: lime
iaas_type: aws
vm_shepherd:
  env_config:
    stack_name: lime
    aws_access_key: AKIAI43577ARGHXPWIMQ
    aws_secret_key: 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
    region: us-east-1
    json_file: config/ert_cloudformation.json
    parameters:
      01NATKeyPair: releng-dev
      05RdsUsername: pivotalcf
      06RdsPassword: pivotalcf
      07SSLCertificateARN: arn:aws:iam::491337929596:server-certificate/lime
    outputs:
      ssh_key_name: releng-dev
      ssh_key_name: {{ssh_key_pair_name}}
      security_group: {{ops_manager_security_group_id}}
      public_subnet_id: {{public_subnet_id}}
      private_subnet_id: {{private_subnet_id}}
      s3_bucket_name: {{ s3_bucket_name }}
  vm_configs:
    - vm_name: Lime OpsManager
      vm_ip_address: 52.4.189.82

ops_manager:
  url: https://pcf.lime.cf-app.com/
  username: pivotalcf
  password: pivotalcf
  ntp_servers: 0.amazon.pool.ntp.org
  availability_zones:
  - iaas_identifier: us-east-1a

  aws:
    aws_access_key: {{iam_aws_access_key_id}}
    aws_secret_key: {{iam_aws_secret_access_key}}
    vpc_id: {{vpc}}
    security_group: {{vms_security_group_name}}
    key_pair_name: {{ssh_key_pair_name}}
    region: {{region}}
    ssh_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpAIBAAKCAQEAhU5ETA/Pt42waL2WDKLBfhIXlaQ3YHem3Tojn044bs3GpGBWeHESchL6Ndjv
      Q8ANoeEJ3/P9AsCZTkd3GP+c8JRUcdvg61wIipzP0ltK1KbVt1N0z/E29c+nTqwM4o4zBUQMT3vj
      oG0Yf6iIx+88OcYRx7wUuUGb1NBXkn/GqnadfMO2g//i8UOF1tcz/jXdxf7i192aGPxeC/5bl70h
      Gnk/PlsZjYrq/cDqX4uI3ZdWC2Dsp6pbHilx1umB8FNHUOzh7yvaF4380y3t5I4oPRlD/8hMz/5L
      1R5GsMYHibkLgq48mjVgTsN3tMJU1DZUf6eHx7dqay7hr35vZFER3wIDAQABAoIBADe9OSuAtP7w
      HOI+253e8/8N+5STfKA2h6wbIkf7Qfd6zWNv8Ngdl3PhYYPgeHMgu9KDMUjWUWW0OKYVlcP7JZkm
      vIR7RvnCmsOyu+ceSxTNybEFEWPdXXi84h0wLZcRlF3QTUFy8QPkegju5HqNGuahXk/g4d1whIMg
      tm1IRj6CDZchKLx3G+Ae+rISf7p+o1pEfEgwMfWcIapa3PD/fwMpfRBwrsWdV9wPn63pzJc7pPFW
      H6y8ZEc2ldsrQThk4f1r0UMUFbD9I0yolVQMDA73ZzvCstamh3E4gga9N4XiUOSoT7JGbXdobumJ
      JLOi3XOmcWJaBl9Ocff9Qpp2UBECgYEAxVL9n3pA3/k+zxh+t0MDWt5SP+gKDbqaXLJl5w7zCuTo
      OFCAKnDxHDSxcbTNarcC32QOjV0F8plkxaNgFP3W9KvPk5mRnfTXJE67GsaOTtj0lYhHpo90NqYe
      U5IH2eA6PHzpmHPdEemQBa5O+mQOFRgvt4iXJaDqfK7Iro3UXicCgYEArPH3ffG14/0LuNq3Mt+E
      CAx0m2tmAIxTfpgd7BXz8scvg0DyGa49/8MO7pPEHrhjaocefuprJph0BawfdIR90GBu/ussuGS3
      pYCcLDTT7ma8bomlOi4apmYNjKUZDijnVFycHxhNfZVg+bzCklMDm3vfPSh1W85JM//sUIosOYkC
      gYBC7cxSzG+2yF6yddd9J4C60I/LV1QZpgJ3kJcZ0StEtbHCcCOYwag2bfUF4VKPcLXLua9p6XR7
      /eV9V9XeKN9BLAmDQeJvVj2m9gFmqpRYUCRdl9TdvOipJJ1CsVRyZSi7nY7KA/qm+ba9BouJSGiy
      ZPrCYNULkVIXql0tP7QZnwKBgQCmSjZlhA8Xu80UnkC+ispiDs/kTP0UE9mIhO1ofqdEzh8yPjVL
      Wg3FKaHm5nAR9cupt2gsMmx6/OW6Ook4ONjcjozLUgd6+WTXnvULUHRi66fNRU54xbHcQ45NqMWR
      puTfafi3sV95HDPVjZkspuN2EkJRhOBrOMuMU0y/GExzuQKBgQCbvIkXm3K6ZUCuOSzEHnprRBBt
      /ntsCJQDSBXfrzPTgkBBiMVx3aaJZYnsvxb2+Vl3YYiv/HM/W+rJZsSsbffwAngHNbUfVdlwnayn
      wB5+GnTcHRiog2K6DGyOfn1MXiQg2IX7ZpehJFoucNQ5IG4lioVZSmKwea9d8LFqIajoVA==
      -----END RSA PRIVATE KEY-----

  networks:
  - name: first-network
    identifier: {{ private_subnet_id }}
    subnet: 10.0.16.0/20
    reserved_ips: 10.0.16.2-10.0.16.4
    dns: 10.0.0.2
    gateway: 10.0.16.1

  elastic_runtime:
    name: cf
    system_domain: lime.cf-app.com
    apps_domain: lime.cf-app.com
    elb_name: lime-pcf-elb
    elb_dns_name: {{ ert_elb_dns_name }}
    file_storage:
      endpoint: https://s3.amazonaws.com
      bucket: {{ s3_bucket_name }}
      access_key: {{iam_aws_access_key_id}}
      secret_key: {{iam_aws_secret_access_key}}
    rds:
      host: {{rds_address}}
      port: {{rds_port}}
      username: {{rds_username}}
      password: {{rds_password}}
    smtp:
      from: identitystaging@mailinator.com
      address: smtp.sendgrid.net
      port: 587
      credentials:
        identity: PCFRelEng
        password: 4H-9Lh-wD{ZST28x{Q
      enable_starttls_auto: true
      smtp_auth_mechanism: plain
    ssl_certificate: |
      -----BEGIN CERTIFICATE-----
      MIICKTCCAZICCQCYjs8Jtc84cTANBgkqhkiG9w0BAQUFADBZMQswCQYDVQQGEwJV
      UzELMAkGA1UECBMCQ0ExITAfBgNVBAoTGEludGVybmV0IFdpZGdpdHMgUHR5IEx0
      ZDEaMBgGA1UEAxQRKi5saW1lLmNmLWFwcC5jb20wHhcNMTUwNDAzMTkyMjEyWhcN
      MTUwNTAzMTkyMjEyWjBZMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExITAfBgNV
      BAoTGEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDEaMBgGA1UEAxQRKi5saW1lLmNm
      LWFwcC5jb20wgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBALkJZuJdzzp8XLia
      kB/o+bFBOffp35uPx9QOjo1lDsHS3BNbmJD+l0BKQ2+BJZ6IUhjHN0ThiXI9mM1B
      HiLd6vzf6GarOuieLvbCyie82W0IefvJzfSEttDXjyn8uEuDs4PeBYqd/YGy9j6A
      gS5ylwnSx4s8S5SaABEpRhslQgETAgMBAAEwDQYJKoZIhvcNAQEFBQADgYEAV32g
      d2n4QLXL2oT4l8mxEssHpWC4lp7V5KHWtCcjtxNNSIpiFl05lJ13x9hgATidS3P6
      df+1OQt+VzUKM4fPqejPmtaE31qbFspAmIAViLqrRDdcrVpwExM8UGrxZ9atSOWB
      sMmF33cdeRgR3/IrQgvbuO6XzXK0ZjLqKocO0ts=
      -----END CERTIFICATE-----
    ssl_private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIICXgIBAAKBgQC5CWbiXc86fFy4mpAf6PmxQTn36d+bj8fUDo6NZQ7B0twTW5iQ
      /pdASkNvgSWeiFIYxzdE4YlyPZjNQR4i3er83+hmqzroni72wsonvNltCHn7yc30
      hLbQ148p/LhLg7OD3gWKnf2BsvY+gIEucpcJ0seLPEuUmgARKUYbJUIBEwIDAQAB
      AoGBAKsRCyIqUkSi5uHwW2B09isuv1X4zTa3daoSDy6fiEYfGEF5RBKAnPrd7Xxv
      7ISlSSkJPIqc7IJGejcAhcj8W5r8oV7Yo1oCqLLPGnUK7qEWkOV/A88sX9MYZOaC
      KaEt/et46UwK7ojT3uRucdlR2KU8A8cbENlnh7v3Mq0GqnQJAkEA5jgV2ET+l7VS
      xvQZliW1ClkqQAxUVWMxy02e371t6FC1BG7i6C/yWYXaH9vM/ZIndg7isJrCefve
      RfGh6HzybQJBAM3CB6kgTGvkw5fc4e/pQYnm2UDxPz3JBk5tPrV2VBZM77w9xjPQ
      BSEIsBIDmWQ2H85rzk+iUWYabxFSmugOkX8CQCLXDgdCuby/xh0xx8V/Q1yjjc9P
      jlu1vU1lG8wEYOOtgxd+qHw29Vgy94Wmv+kH+0zUh93uLcxEH6k6HiSO9CkCQQC1
      0ZdjZB8j2Greb1lX3w8DBPNF5+iyeEkSVIbtYzq62hGejhfvAQsHPd4YjQWnAAzr
      I2iUBiNXzlQHQq+QEA+RAkEAvBRUbFlc8YzIZhPH10ins0I+d1QIkcgO7PUyG2gv
      bkFC8o11iFw06lCUA/xnBXQ0GuP3mWSb7MOOW1qmPkGD5w==
      -----END RSA PRIVATE KEY-----
    trust_self_signed_certificates: true
