iaas_type: openstack
name: mars
vm_shepherd:
  vm_configs:
  - creds:
      auth_url: http://10.85.38.2:5000/v2.0/tokens
      username: releng-ci
      api_key: 'cS3T3SZOaxKU'
      tenant: mars
    vm:
      name: 'mars-ops-manager'
      flavor_name: opsman
      network_name: 'mars_net'
      key_name: releng-openstack-key
      security_group_names:
        - mars-ops-manager
        - mars-products
      private_ip: 192.168.116.100
      public_ip: 10.85.38.81

ops_manager:
  url: https://pcf.mars.cf-app.com
  username: pivotalcf
  password: pivotalcf
  ntp_servers: time1.sf.cf-app.com
  availability_zones:
    - iaas_identifier: nova
  openstack:
    identity_endpoint: http://10.85.38.2:5000/v2.0
    username: releng-ci
    password: 'cS3T3SZOaxKU'
    tenant: mars
    region: RegionOne
    security_group_name: mars-products
    key_pair_name: releng-openstack-key
    ssh_private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEAoksCySvsJjMQXeYmva5IOhrBUv9oIYEzUw3cODLthEq4MUvf
      oYtY/yqcsjKraDJrXPlI1jX+GzHp1rSZ/jcgztFsPPxwnqY1TaMvh4ZNOTYLnyPC
      6m3aBNKtxWY0r938LM9wegxChQgyQarwF8nY+9W4AGLoe4abDr1l509AG6BoBAVa
      m5fFERX0+GI0bigBw39Wu5/2stZix2or08u0hxSorDD8ne08pAb3Z+DtoHCVbr/3
      CNde+DBxzuMRQ0C53725jd+BiYlWpgkBgg0Zz0FNnubiYv1BjBKSESfMKUKXaAjO
      m37OqLnObsXofkDsF4So7+yJvv263iwKLI/KJwIDAQABAoIBAQCZY/hQF1ltiVnw
      xfTb1nuhn2QVhBzxfeH6n+ECpO/k15Jb1XCaiNAm7CmKK2XiZ7Ud/Ocgv4taPMTd
      D3l00roJf9qjkZ0H9ePva0si9obKihBV60Dwvb8QS+e96SnnBxKvb6jJUgkVH3gQ
      pPWkJj0VWRw+ET3WcpTfS5ejFj5rXKE7CkYxsZcwUQpapOCQ042rWE/qvTlUDAL9
      Ze8aCjv7cARCSS64PCdHu6OlpAuuC8y6MK/HodKVg8r83VQeTDgh+4f8MCl7Uotl
      ZiJzqLl1xnUUj/stx3LbFqC5G/YHZaANqa91ODDKeJ8eAKQpCNuU0HcChJLkmohL
      UoNfHjARAoGBANHbUihfipw9e/gI11TfKU1SXXZUS3y+M2wPYSUD02R5gdfIkOb7
      2caXdog1WjZ+BQ1vlyrjFVqHg/1cYVgcsOJ3XACACtiv2JjJQGhgBsNHcIujBbJ+
      fsn2gjeN7yWu8pSr4Uv++HEYkImvVPJ5G1IqoRXp7NY36JglEV+bJRdDAoGBAMX6
      XS1f2flZJI2WpaIHeglpHVVcPad8lB9SqwBIUp3PjAXSc4k1OFp3cgbtZHK8Dv4Q
      vj5BaJr2iWOoICqPFNxy9H+uqn0kmE4Tdrnf5L2+VCfUsgPnKUkUIcQoqIxHIdT6
      fN/ttGfq3T3Pa4ebX5/nIsJACOMTcCvh1a1UkNlNAoGAZ29AaWHeAfBUIAbLi6uK
      we+s3Vvi8RMWaVaTPRlLoiQ5mU/kC9Vqm3WgGLajRmSKvPqZeav/pGVS6xgTasiJ
      brYCBMUXk4HosjXPpyJdcvbNRCYP8tBiUc1MlXFBxEMckaa+HyUG80d2RkbDCdgj
      XTZhu1lXQKbB3+u1Sng/qd0CgYBwOlfdo+tttUHKXa6xJing8cxmGi79JdrV0sgL
      FfR3bzMCDeXezuOOLQ3frWz2uXKKRbWClxOUXNNPQfxSA+Agg63kP4B4BmmsQM5Z
      2fjSMvWDysfK/Jxjx9zIVQAO3TfpgsGNMzPEgNg/9LgRHFvdymni0ef3yYoZ5iB5
      7GlcNQKBgAZLn9BAiUQUKiYk7810tod+pcvFl69lOt1gBT5QDacmPsej7Xvr9Xim
      nsbcAi6Jzt/s9WWesNB0ip6hVCcVBxlg9qMhRALsyCB1AEGkUPkvRgGzqzM9frEv
      TRRpD1U2HXvKycKpCsXqsxrgDMZzN3GZ0sys6IAS7kg7l0Upj91Z
      -----END RSA PRIVATE KEY-----
  networks:
  - name: first-network
    identifier: 481e972e-c3d2-4671-bb32-e780053b9bd3
    subnet: 192.168.116.0/24
    reserved_ips: 192.168.116.2-192.168.116.4
    dns: 10.87.8.10,10.87.8.11
    gateway: 192.168.116.1
  elastic_runtime:
    name: cf
    ha_proxy_floating_ips: 10.85.38.80
    system_domain: sys.mars.cf-app.com
    apps_domain: apps.mars.cf-app.com
    smtp:
      from: identitystaging@mailinator.com
      address: smtp.sendgrid.net
      port: 587
      credentials:
        identity: PCFRelEng
        password: 4H-9Lh-wD{ZST28x{Q
      enable_starttls_auto: true
      smtp_auth_mechanism: plain
    trust_self_signed_certificates: true
