---
name: mesa
iaas_type: vsphere
vm_shepherd:
  vm_configs:
  - vcenter_creds:
      ip: 10.84.32.61
      username: root
      password: look74Beer
    vsphere:
      host: vcenter
      resource_pool: mesa
      datacenter: private
      cluster: private
      datastore: public
      network: mesa
      folder: mesa
    cleanup:
      datacenter: private
      datastores:
      - public
      datacenter_folders_to_clean:
      - mesa
      - mesa_vms
      - mesa_templates
      datastore_folders_to_clean:
      - mesa
      - mesa_disk
    vm:
      ip: 10.85.87.16
      gateway: 10.85.87.1
      netmask: 255.255.255.0
      dns: 10.87.8.10,10.87.8.11
      ntp_servers: time1.sf.cf-app.com
      vm_password: pivotalcf
ops_manager:
  url: https://pcf.mesa.cf-app.com
  username: pivotalcf
  password: wilderror16
  ntp_servers: time1.sf.cf-app.com
  vcenter:
    creds:
      ip: 10.84.32.61
      username: root
      password: look74Beer
    datacenter: private
    datastore: public
    bosh_vm_folder: mesa_vms
    bosh_template_folder: mesa_templates
    bosh_disk_path: mesa_disk
  availability_zones:
  - name: first-az
    cluster: private
    resource_pool: mesa
  networks:
  - name: first-network
    identifier: mesa
    subnet: 10.85.87.0/24
    gateway: 10.85.87.1
    reserved_ips: 10.85.87.0-10.85.87.90
    dns: 10.87.8.10,10.87.8.11
  elastic_runtime:
    name: cf
    ha_proxy_static_ips: 10.85.87.254
    system_domain: sys.mesa.cf-app.com
    apps_domain: apps.mesa.cf-app.com
    smtp:
      from: identitystaging@mailinator.com
      address: smtp.sendgrid.net
      port: 587
      credentials:
        identity: PCFRelEng
        password: 4H-9Lh-wD{ZST28x{Q
      enable_starttls_auto: true
      smtp_auth_mechanism: plain
    trust_self_signed_certificates: true
