---
name: moose
iaas_type: vsphere
vm_shepherd:
  vm_configs:
  - vcenter_creds:
      ip: 10.84.32.61
      username: root
      password: look74Beer
    vsphere:
      host: vcenter
      resource_pool: moose
      datacenter: private
      cluster: private
      datastore: private
      network: moose
      folder: moose
    cleanup:
      datacenter: private
      datastores:
      - private
      datacenter_folders_to_clean:
      - moose
      - moose_vms
      - moose_templates
      datastore_folders_to_clean:
      - moose
      - moose_disk
    vm:
      ip: 10.85.45.16
      gateway: 10.85.45.1
      netmask: 255.255.255.0
      dns: 10.87.8.10,10.87.8.11
      ntp_servers: time1.sf.cf-app.com
      vm_password: pivotalcf
ops_manager:
  url: https://pcf.moose.wild.cf-app.com
  username: pivotalcf
  password: pivotalcf
  ntp_servers: time1.sf.cf-app.com
  vcenter:
    creds:
      ip: 10.84.32.61
      username: root
      password: look74Beer
    datacenter: private
    datastore: private
    microbosh_vm_folder: moose_vms
    microbosh_template_folder: moose_templates
    microbosh_disk_path: moose_disk
  availability_zones:
  - name: first-az
    cluster: private
    resource_pool: moose
  networks:
  - name: first-network
    identifier: moose
    subnet: 10.85.45.0/24
    gateway: 10.85.45.1
    reserved_ips: 10.85.45.0-10.85.45.90
    dns: 10.87.8.10,10.87.8.11
  elastic_runtime:
    name: cf
    ha_proxy_static_ips: 10.85.45.254
    system_domain: sys.moose.wild.cf-app.com
    apps_domain: apps.moose.wild.cf-app.com
    trust_self_signed_certificates: true
