name: passion
iaas_type: aws
vm_shepherd:
  env_config:
    stack_name: passion
    aws_access_key: AKIAJEAGY2FWB7DEGFXQ
    aws_secret_key: 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
    region: us-west-1
    json_file: config/ert_cloudformation.json
    parameters:
      01NATKeyPair: releng-dev-west
      05RdsUsername: pivotalcf
      06RdsPassword: pivotalcf
      07SSLCertificateARN: arn:aws:iam::491337929596:server-certificate/passion
    outputs:
      ssh_key_name: {{ssh_key_pair_name}}
      security_group: {{ops_manager_security_group_id}}
      public_subnet_id: {{public_subnet_id}}
      private_subnet_id: {{private_subnet_id}}
      s3_bucket_names:
        - {{ ops_manager_s3_bucket_name }}
        - {{ ert_s3_buildpacks_bucket_name }}
        - {{ ert_s3_droplets_bucket_name }}
        - {{ ert_s3_packages_bucket_name }}
        - {{ ert_s3_resources_bucket_name }}
  vm_configs:
    - vm_name: Passion OpsManager
      vm_ip_address: 54.153.74.8

ops_manager:
  url: https://pcf.passion.cf-app.com/
  username: pivotalcf
  password: wilderror16
  ntp_servers: 0.amazon.pool.ntp.org
  availability_zones:
  - iaas_identifier: us-west-1b

  aws:
    aws_access_key: {{iam_aws_access_key_id}}
    aws_secret_key: {{iam_aws_secret_access_key}}
    vpc_id: {{vpc}}
    security_group: {{vms_security_group_name}}
    key_pair_name: {{ssh_key_pair_name}}
    region: {{region}}
    ssh_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEAhjHuhEToOnffT0anE3LAu9ijudz+P7yzVmXW7Ignn+RP56GpFswvBS+rdMoF
      9d13dzom/QdR76EMch16uz0V3SrFyphB2XdHQ34cvJMjlgVxXsNfVHA96rTIP5QVaaB5TRgXsKD8
      /3pJ0q/dWoLq0a4MQT48DI8HCTYT9XnVjYHYJGZHKEj+5ztr4T0CuOuIwmElJJAXu33ooEDJZPYK
      57z7zfy3RtSs0t40A/KJN12fY2ra25P4k7q2o47349Hz+aBsHK9YMAQhGGdPwNOe4yw8Qt1LuK1B
      hxSgt4IWLMXljtHBA8tfBCD12DFQIej+5zBMnjxa9ONML47yZpX6qQIDAQABAoIBAAstj5Oe9cUh
      BQ3icbpR/bHn+sNZoCgI/Ns+gmeTc9GCwBEoSyBmA6in7t08ksCHIRNiWasL+AxA2vuKbxW3oeGZ
      VX5prlqB8AK0N4qRqw4tB+N/3Kn4639obaG2IQ56WoBMeHSzBD/3nLya/5Ixg4PRvp2UpIXbSBfB
      VGpHKr2tq0O4NHGfvNL5OQeI7bXFcDvgiRMTcmY0T0OcU3s2cROnMTgCjMiHSUwZqgaWYKxNCo0v
      jP8CgAHKOj4nNOJwbVcXxmClQocQwnwkyWKuCNWQaPb2js8u9xdekLS6/B+LQYrBfGjR4uFAfWgp
      IS30h+Ws8qplM4ryafHAFBcA14ECgYEAvWtzb6yrwJ6DgANiubhXSlP25z5Mh5O1vFkgYTcJCy4f
      1/u5Rnkeg5ZNNwl/iSVqrv1VT0JdD/HYAhY8iWAJApyYX/xbKilzd33iQtKQjj4uDQAkWRm56FjE
      eKs27u3vppWMLs4d2AAUZSba8gNBmcvNp+WubK2gEZSNBynBz7ECgYEAtV0zLI75LvaCXfk9yPIs
      4xCiwKk6oXncpOVGn0F8D+Y+ywogU3GPPxJQ1HL/WEt0qFt7KIenCLHppOsLSkgSrBM2l5KJBbpA
      3kVwfFTZPubedXHr1usGX/cKO37fZTdE3gqHH2VzND1WZNy8rTpJ5Kbbwd+fzPnXSBqDl1ar0HkC
      gYBmJp9fV0BcpV+HVswUGizBAd0CQh+lcewtQedrZfGznNFBehglwEXLcu/7QV0NCiepbSdnkgN8
      CNGT9of5EdhqFyc5hG9pomcJxtKRdNrOSwwsqKnxfyU5/z0dUkBSw/Bc5wNtbmy7wvc8waKLp2Pm
      W/lxlTTmmQ/cyz7u4P8LUQKBgQCywG4cn7nnWJz7JBmKQW6OSaove1vHJUWb3EIz2qX9QbBoC836
      kDVgM5wpGEKlcpFDEg8bzj+KKVgf7G2PQ+PrZ3BqCco1M/KVYBlS4YnRHljppmOMys3YrbKPGyfx
      KX0d34B4KFRYi4/oD0uC7K1ByFdWCSMGMsTFUySZd5oV+QKBgBop5BJF1e0qw2virzT7ZRbrrsVP
      IBk3hbF/UJ7zaF/pGynZmyjW1zBkO29c7zJxaCqnPdOCGibyFNTfcXNPw3jJcEPzzNa3TtrQLP8Z
      cBzOTY3vQeGxRW5wjIqg98ST3GzN4C2Rd+PpSFS6OvG9CYqBVl1mdde00nyVbcXPNkRv
      -----END RSA PRIVATE KEY-----

  networks:
  - name: first-network
    identifier: {{ private_subnet_id }}
    subnet: 10.0.16.0/20
    reserved_ips: 10.0.16.2-10.0.16.4
    dns: 10.0.0.2
    gateway: 10.0.16.1

  elastic_runtime:
    name: cf
    system_domain: passion.cf-app.com
    apps_domain: passion.cf-app.com
    elb_name: passion-pcf-elb
    elb_dns_name: {{ ert_elb_dns_name }}
    ssh_elb_name: passion-pcf-ssh-elb
    ssh_elb_dns_name: {{ ert_ssh_elb_dns_name }}
    file_storage:
      endpoint: https://s3-us-west-1.amazonaws.com
      bucket: {{ ert_s3_buildpacks_bucket_name }}
      buildpacks_bucket: {{ ert_s3_buildpacks_bucket_name }}
      droplets_bucket: {{ ert_s3_droplets_bucket_name }}
      packages_bucket: {{ ert_s3_packages_bucket_name }}
      resources_bucket: {{ ert_s3_resources_bucket_name }}
      access_key: {{iam_aws_access_key_id}}
      secret_key: {{iam_aws_secret_access_key}}
    rds:
      host: {{rds_address}}
      port: {{rds_port}}
      username: {{rds_username}}
      password: {{rds_password}}
    smtp:
      from: identitystaging@mailinator.com
      address: smtp.sendgrid.net
      port: 587
      credentials:
        identity: PCFRelEng
        password: 4H-9Lh-wD{ZST28x{Q
      enable_starttls_auto: true
      smtp_auth_mechanism: plain
    ssl_certificate: |
      -----BEGIN CERTIFICATE-----
      MIID9DCCAtwCCQDu878At7QxqjANBgkqhkiG9w0BAQUFADCBuzELMAkGA1UEBhMC
      VVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBGcmFuY2lzY28x
      EDAOBgNVBAoTB1Bpdm90YWwxHDAaBgNVBAsTE1JlbGVhc2UgRW5naW5lZXJpbmcx
      HTAbBgNVBAMUFCoucGFzc2lvbi5jZi1hcHAuY29tMTAwLgYJKoZIhvcNAQkBFiFj
      Zi1yZWxlYXNlLWVuZ2luZWVyaW5nQHBpdm90YWwuaW8wHhcNMTUwODE0MjE0NDUw
      WhcNMTYwODEzMjE0NDUwWjCBuzELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlm
      b3JuaWExFjAUBgNVBAcTDVNhbiBGcmFuY2lzY28xEDAOBgNVBAoTB1Bpdm90YWwx
      HDAaBgNVBAsTE1JlbGVhc2UgRW5naW5lZXJpbmcxHTAbBgNVBAMUFCoucGFzc2lv
      bi5jZi1hcHAuY29tMTAwLgYJKoZIhvcNAQkBFiFjZi1yZWxlYXNlLWVuZ2luZWVy
      aW5nQHBpdm90YWwuaW8wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCy
      EX5HYmjSfv9E/qXwtpRux2Jo7/R3y29mKyWb3uKF5UQyDiHokcjCzHuo2NSPYzec
      E0cQR3Pi17RCKsqb+iR9yOrTjnSBP3UoCzJzl9RSgaidjwduvMbpukev8DOy24zA
      q1pCEUyAlxb72a20Te09V9JU4Qu/Z1U4CGfnXYWOzVZsuur0udVQO+nt5BV7sSAc
      iXHHztK0RxLhS+w823JQF4YE8VgMXaCw5MKxHBfflJmRlNBOEaQD/piuIYER08YC
      7j6LRWxbR99kLweocEiDcplXfRTuNZ2ewJgpnoEMn5bvAVXsBLzlkj02HJCHn3TP
      zVDn2dLtDTPLCTQeUx2BAgMBAAEwDQYJKoZIhvcNAQEFBQADggEBAGKibtD7wd2y
      ED+SPk6mXoqb9aZzMs8e33DMj8hMxjbVoDV1ffKVrluIiTb/4uj4Yn/2oDvVC4jl
      RGF3mk+AN/99H5N6Co6xkPpZjIiRr8CaFSle5O0k8Z8t/VHr2fpberwtv5q0xTbH
      cYS4CkcCusz7I/JiWlBehIYU7HfqfO34+CMUq2HDlsQYpCA1vwCIOUezSanbWeR4
      Gu0SYZPSUNSfrBZULBha4dOjvV2UD+jSkEudkUsmuAaaVzm1fwECrWYYwnrDY2Y6
      zFv5Bx5L5PoChF3dqB9yo2IKEUCsdMBGU3nZxQH8RVVQhDGgJmMtHK9y2O7Lrzef
      DRY7TyhaRq0=
      -----END CERTIFICATE-----
    ssl_private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEogIBAAKCAQEAshF+R2Jo0n7/RP6l8LaUbsdiaO/0d8tvZislm97iheVEMg4h
      6JHIwsx7qNjUj2M3nBNHEEdz4te0QirKm/okfcjq0450gT91KAsyc5fUUoGonY8H
      brzG6bpHr/AzstuMwKtaQhFMgJcW+9mttE3tPVfSVOELv2dVOAhn512Fjs1WbLrq
      9LnVUDvp7eQVe7EgHIlxx87StEcS4UvsPNtyUBeGBPFYDF2gsOTCsRwX35SZkZTQ
      ThGkA/6YriGBEdPGAu4+i0VsW0ffZC8HqHBIg3KZV30U7jWdnsCYKZ6BDJ+W7wFV
      7AS85ZI9NhyQh590z81Q59nS7Q0zywk0HlMdgQIDAQABAoIBABXnrP8fDgIG+WQF
      Z2hrLWtLP8Hk8s/hyLxqxl+cVYVfJLp7npQ7itTbzsKAmfVhoS+j93P7NjhLjLMv
      DGmPpfmLQ8fumEpmAgWBCx3JKadUp+dp9uIaeuW5sqPkCpgQBgqVia7i7eRLsdod
      dw7dHzgSm58xZ/6NuaAA+LcvfASK7WqaxqGlXoO9gNfqUV0cpMY4Nyo9GjosX6zI
      ciTPaeEgkJwBguHroYLIPEUOO2vSUwL2omsJxe1gNSRn9XX7KyVAORqy79f9DYeY
      Ie6XmksiKJ2za+O4pmKCAuaB9PUyl1iyexYbclG01cCWce9pSVuJxpc2M+vL+sqr
      vYoJQgECgYEA3iAaJ1euJgYaU/MYB2X7C3dM0X4ClUwcKFzhc1pvGPOEZ8/hadwh
      mKh5sRiDKVAKFC2YkBR2YNM94mOljkccG25TU1m7g2EKdF8P06EXeTfi3Ub+U9BB
      3eluw5bFEt3UasT4TVZZJdXjxmF+fsjKdv6ofKiLs2EkiiLTMqjBZbECgYEAzTlh
      BsqUqn3DMdioEajLjMZbQaWvZHy5n3pQd9QVo5XH9wE8a9Mt4x8pfsndD4UBwySN
      YsieuYhTZg+kFu4B/4pmg3S6ijHH4WDGPmvEfaoL9sAHkC4AozhS3YMCOCobvyTV
      SBLkCPUpfvpVt6Hlq2vQGwby05dX6OPkM3JumNECgYAEqQnDb4yA0bn1rvD/Hr2g
      pPUgpBMrzLf+hMxaHjicfmd1wh/Jl8vApzA+bfQ6hqpfeAFubG97YpM2z75meMl3
      Ld5jrktH215byK7NUuDqMyj4WYf2fDUVkdM4GU6zMaJGRzGqdbhTGeS4gc0kndPZ
      oUgprWOY9N3OZCKoOnAsUQKBgHtD76donosZJtkVzT1uKXTQ35c6sXKmB8hma1bO
      KIEtQgJ215fcLD+zQ/VHwmPD/B7+IX4oCk5eN9mho2myY7jdpF1pC3JeHDSfL/Pm
      PwtLzAvVo7VSLEfdWMh8HCUoBap1sTWtQxKuTtJaAopdz9l61HCnZ8r3qHHWEAdm
      wE9BAoGAAWmi6TJ3DPmjEUp9RypfXuH2mkStSkabECSRT0HKJ9YxNlhKLuhJV9ID
      pRz6JWcykLJuyEZycS3+ifjQOn7r7fpIgEVYODry0ORo4PChfmUjZGcNejNrb6pp
      hmi00gPKy2tIvids9itXGN8lt6QQqXqcxircRPpzTx4Y1VAQ0m0=
      -----END RSA PRIVATE KEY-----
    trust_self_signed_certificates: true
