name: pear
iaas_type: aws
vm_shepherd:
  env_config:
    stack_name: pear
    aws_access_key: AKIAI43577ARGHXPWIMQ
    aws_secret_key: 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
    region: us-west-1
    json_file: config/ert_cloudformation.json
    parameters:
      01NATKeyPair: releng-dev-west
      05RdsUsername: pivotalcf
      06RdsPassword: pivotalcf
      07SSLCertificateARN: arn:aws:iam::491337929596:server-certificate/pear
    outputs:
      ssh_key_name: releng-dev
      ssh_key_name: {{ssh_key_pair_name}}
      security_group: {{ops_manager_security_group_id}}
      public_subnet_id: {{public_subnet_id}}
      private_subnet_id: {{private_subnet_id}}
      s3_bucket_names:
        - {{ ops_manager_s3_bucket_name }}
        - {{ ert_s3_bucket_name }}
  vm_configs:
    - vm_name: Pear OpsManager
      vm_ip_address: 52.6.145.125

ops_manager:
  url: https://pcf.pear.cf-app.com
  username: pivotalcf
  password: pivotalcf
  ntp_servers: 0.amazon.pool.ntp.org
  availability_zones:
  - iaas_identifier: us-west-1b

  aws:
    aws_access_key: {{iam_aws_access_key_id}}
    aws_secret_key: {{iam_aws_secret_access_key}}
    vpc_id: {{vpc}}
    security_group: {{vms_security_group_name}}
    key_pair_name: {{ssh_key_pair_name}}
    region: {{region}}
    ssh_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEAhjHuhEToOnffT0anE3LAu9ijudz+P7yzVmXW7Ignn+RP56GpFswvBS+rdMoF
      9d13dzom/QdR76EMch16uz0V3SrFyphB2XdHQ34cvJMjlgVxXsNfVHA96rTIP5QVaaB5TRgXsKD8
      /3pJ0q/dWoLq0a4MQT48DI8HCTYT9XnVjYHYJGZHKEj+5ztr4T0CuOuIwmElJJAXu33ooEDJZPYK
      57z7zfy3RtSs0t40A/KJN12fY2ra25P4k7q2o47349Hz+aBsHK9YMAQhGGdPwNOe4yw8Qt1LuK1B
      hxSgt4IWLMXljtHBA8tfBCD12DFQIej+5zBMnjxa9ONML47yZpX6qQIDAQABAoIBAAstj5Oe9cUh
      BQ3icbpR/bHn+sNZoCgI/Ns+gmeTc9GCwBEoSyBmA6in7t08ksCHIRNiWasL+AxA2vuKbxW3oeGZ
      VX5prlqB8AK0N4qRqw4tB+N/3Kn4639obaG2IQ56WoBMeHSzBD/3nLya/5Ixg4PRvp2UpIXbSBfB
      VGpHKr2tq0O4NHGfvNL5OQeI7bXFcDvgiRMTcmY0T0OcU3s2cROnMTgCjMiHSUwZqgaWYKxNCo0v
      jP8CgAHKOj4nNOJwbVcXxmClQocQwnwkyWKuCNWQaPb2js8u9xdekLS6/B+LQYrBfGjR4uFAfWgp
      IS30h+Ws8qplM4ryafHAFBcA14ECgYEAvWtzb6yrwJ6DgANiubhXSlP25z5Mh5O1vFkgYTcJCy4f
      1/u5Rnkeg5ZNNwl/iSVqrv1VT0JdD/HYAhY8iWAJApyYX/xbKilzd33iQtKQjj4uDQAkWRm56FjE
      eKs27u3vppWMLs4d2AAUZSba8gNBmcvNp+WubK2gEZSNBynBz7ECgYEAtV0zLI75LvaCXfk9yPIs
      4xCiwKk6oXncpOVGn0F8D+Y+ywogU3GPPxJQ1HL/WEt0qFt7KIenCLHppOsLSkgSrBM2l5KJBbpA
      3kVwfFTZPubedXHr1usGX/cKO37fZTdE3gqHH2VzND1WZNy8rTpJ5Kbbwd+fzPnXSBqDl1ar0HkC
      gYBmJp9fV0BcpV+HVswUGizBAd0CQh+lcewtQedrZfGznNFBehglwEXLcu/7QV0NCiepbSdnkgN8
      CNGT9of5EdhqFyc5hG9pomcJxtKRdNrOSwwsqKnxfyU5/z0dUkBSw/Bc5wNtbmy7wvc8waKLp2Pm
      W/lxlTTmmQ/cyz7u4P8LUQKBgQCywG4cn7nnWJz7JBmKQW6OSaove1vHJUWb3EIz2qX9QbBoC836
      kDVgM5wpGEKlcpFDEg8bzj+KKVgf7G2PQ+PrZ3BqCco1M/KVYBlS4YnRHljppmOMys3YrbKPGyfx
      KX0d34B4KFRYi4/oD0uC7K1ByFdWCSMGMsTFUySZd5oV+QKBgBop5BJF1e0qw2virzT7ZRbrrsVP
      IBk3hbF/UJ7zaF/pGynZmyjW1zBkO29c7zJxaCqnPdOCGibyFNTfcXNPw3jJcEPzzNa3TtrQLP8Z
      cBzOTY3vQeGxRW5wjIqg98ST3GzN4C2Rd+PpSFS6OvG9CYqBVl1mdde00nyVbcXPNkRv
      -----END RSA PRIVATE KEY-----

  networks:
  - name: first-network
    identifier: {{ private_subnet_id }}
    subnet: 10.0.16.0/20
    reserved_ips: 10.0.16.2-10.0.16.4
    dns: 10.0.0.2
    gateway: 10.0.16.1

  elastic_runtime:
    name: cf
    system_domain: pear.cf-app.com
    apps_domain: pear.cf-app.com
    elb_name: pear-pcf-elb
    elb_dns_name: {{ ert_elb_dns_name }}
    file_storage:
      endpoint: https://s3-us-west-1.amazonaws.com
      bucket: {{ ert_s3_bucket_name }}
      access_key: {{iam_aws_access_key_id}}
      secret_key: {{iam_aws_secret_access_key}}
    rds:
      host: {{rds_address}}
      port: {{rds_port}}
      username: {{rds_username}}
      password: {{rds_password}}
    smtp:
      from: identitystaging@mailinator.com
      address: smtp.sendgrid.net
      port: 587
      credentials:
        identity: PCFRelEng
        password: 4H-9Lh-wD{ZST28x{Q
      enable_starttls_auto: true
      smtp_auth_mechanism: plain
    ssl_certificate: |
      -----BEGIN CERTIFICATE-----
      MIICKTCCAZICCQCTqZGx8T2dYDANBgkqhkiG9w0BAQUFADBZMQswCQYDVQQGEwJV
      UzELMAkGA1UECBMCQ0ExITAfBgNVBAoTGEludGVybmV0IFdpZGdpdHMgUHR5IEx0
      ZDEaMBgGA1UEAxQRKi5wbHVtLmNmLWFwcC5jb20wHhcNMTUwNDEwMDAzMDIyWhcN
      MTUwNTEwMDAzMDIyWjBZMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExITAfBgNV
      BAoTGEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDEaMBgGA1UEAxQRKi5wbHVtLmNm
      LWFwcC5jb20wgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBALYf8AYNqZEanhQa
      S/iMaJAQPVjOccbG3t4g4D1SJWLwOH8L9spzja54yyPIngvbHtrwERZZLWch8MpR
      0Jew/AxmrsXbQtKn2CQnYenO5rt34PzzIhchBQBfQB+AiZfzgLvuJJjoRZhF6fzt
      tTfL6yqLJrE0dgmD4oBeqoLYQhcXAgMBAAEwDQYJKoZIhvcNAQEFBQADgYEAjK+s
      vSoHkOAC8mmLKHRydIvKCs6enDOrPbEUjILQNXVmi7TO73TvhpRUICRSH79X2sD2
      oryUxyn/e7c2X0TS1PIXSkP/nT1jrLiXdkiLiq1Y2Iq8OccfBakXgbuQEPp2GrlV
      hQ955JZyH6mDJrN35LWr7WajxDesxg0kPG9/aWg=
      -----END CERTIFICATE-----
    ssl_private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIICWwIBAAKBgQC2H/AGDamRGp4UGkv4jGiQED1YznHGxt7eIOA9UiVi8Dh/C/bK
      c42ueMsjyJ4L2x7a8BEWWS1nIfDKUdCXsPwMZq7F20LSp9gkJ2Hpzua7d+D88yIX
      IQUAX0AfgImX84C77iSY6EWYRen87bU3y+sqiyaxNHYJg+KAXqqC2EIXFwIDAQAB
      AoGASqdszA5to301ryfYXFmxwtvlSbHWEZUTZhoz0O8LRDMT9YAB+ZrESPBa1KA3
      qMR5MWWWm4KSiePvv/8pcgSqS/mso4rXJozp4VaSRkOSZCL+rfc1toVLh61oevjE
      aUjLK7/OSd/SslLUPGL3muo7Hh6z9JXk6CwfCz4vTKT/gAECQQDl6GdA/aaEJGji
      RPTJBjpCa77qdAAp4BcYF7SIit4cfxyQCQPtZN6M5zvhKTYCsPjsypaQs5777oXB
      2t5ZvLQBAkEAystGcNk1jdF67DAL1oc8PYMbq/Ey6lEoKeG+W96v9LIkN+Tnoz1B
      Xq9cC0oBxL+G6L8G4IFUQqmAqV2kmxHrFwJAMRBRyLrY6GZkw7T3kFb14+reiWZM
      CqO6Cfg1HNaV4/r0e4CRB/54yBUo4DpNPnHKDa6GR0ct7JHQlbhBr2DoAQJAexF5
      oipvUa17B7LwvDQ93qaeOG6cE49E7IXO3Dn8Vmd1i2YjHPGjpi6NkVxMTnZdDQpA
      xiY2WG49Yostxd3N6QJAWysiaEd1GSvb13xP/HPwhitvs4YZd0xbf+gx/LYsNgj+
      twmLkIa0MPbkjuy2Y7mGyZUFMCeXg7+v9c16znLoCw==
      -----END RSA PRIVATE KEY-----
    trust_self_signed_certificates: true
