---
name: skunk
iaas_type: vsphere
vm_shepherd_configs:
- vcenter_creds:
    ip: 10.84.32.61
    username: root
    password: look74Beer
  vsphere:
    host: vcenter
    resource_pool: skunk
    datacenter: private
    cluster: private
    datastore: private
    network: skunk
    folder: skunk
  cleanup:
    datacenter: private
    datastores:
    - private
    datacenter_folders_to_clean:
    - skunk
    - skunk_vms
    - skunk_templates
    datastore_folders_to_clean:
    - skunk
    - skunk_disk
  vm:
    ip: 10.85.59.16
    gateway: 10.85.59.1
    netmask: 255.255.255.0
    dns: 10.87.8.10,10.87.8.11
    ntp_servers: time1.sf.cf-app.com
    vm_password: pivotalcf
ops_manager:
  url: https://pcf.skunk.wild.cf-app.com
  username: pivotalcf
  password: pivotalcf
  ntp_servers: time1.sf.cf-app.com
  vcenter:
    creds:
      ip: 10.84.32.61
      username: root
      password: look74Beer
    datacenter: private
    datastore: private
    microbosh_vm_folder: skunk_vms
    microbosh_template_folder: skunk_templates
    microbosh_disk_path: skunk_disk
  availability_zones:
  - name: first-az
    cluster: private
    resource_pool: skunk
  networks:
  - name: first-network
    identifier: skunk
    subnet: 10.85.59.0/24
    gateway: 10.85.59.1
    reserved_ips: 10.85.59.0-10.85.59.90
    dns: 10.87.8.10,10.87.8.11
  elastic_runtime:
    name: cf
    ha_proxy_static_ips: 10.85.59.254
    system_domain: sys.skunk.wild.cf-app.com
    apps_domain: apps.skunk.wild.cf-app.com
    smtp:
      from: identitystaging@mailinator.com
      address: smtp.sendgrid.net
      port: 587
      credentials:
        identity: PCFRelEng
        password: 4H-9Lh-wD{ZST28x{Q
      enable_starttls_auto: true
      smtp_auth_mechanism: plain
    trust_self_signed_certificates: true
