---
resource_types: &resource_types
  - image: docker:///pcfseceng/email-resource#latest
    type: email
  - image: /var/vcap/packages/archive_resource
    type: archive
  - image: /var/vcap/packages/cf_resource
    type: cf
  - image: /var/vcap/packages/docker_image_resource
    type: docker-image
  - image: /var/vcap/packages/git_resource
    type: git
  - image: /var/vcap/packages/s3_resource
    type: s3
  - image: /var/vcap/packages/semver_resource
    type: semver
  - image: /var/vcap/packages/time_resource
    type: time
  - image: /var/vcap/packages/tracker_resource
    type: tracker
  - image: /var/vcap/packages/pool_resource
    type: pool
  - image: /var/vcap/packages/vagrant_cloud_resource
    type: vagrant-cloud
  - image: /var/vcap/packages/github_release_resource
    type: github-release
  - image: /var/vcap/packages/bosh_io_release_resource
    type: bosh-io-release
  - image: /var/vcap/packages/bosh_io_stemcell_resource
    type: bosh-io-stemcell
  - image: /var/vcap/packages/bosh_deployment_resource
    type: bosh-deployment

#  syslog:
#    destination:
#      address: logs3.papertrailapp.com:25911
#      transport: tls


name: vsphere-concourse-worker

director_uuid: 3f9c052c-8afe-4ad6-8a89-85328792bc60

networks:
- name: private
  type: manual
  subnets:
  - range: 10.85.1.0/24
    gateway: 10.85.1.1
    dns: [10.87.8.10,10.87.8.11]
    cloud_properties: {name: badger}

releases:
  - name: concourse
    version: latest
  - name: garden-linux
    version: latest

jobs:
  - name: vsphere-worker
    instances: 2
    resource_pool: workers
    templates:
      - {release: concourse, name: groundcrew}
      - {release: concourse, name: baggageclaim}
      - {release: garden-linux, name: garden}
    networks: [{name: private}]
    properties:
      groundcrew:
        tags: ["vsphere","openstack"]
        garden:
          forward_address: 127.0.0.1:7777
        baggageclaim:
          forward_address: 127.0.0.1:7788
        resource_types: *resource_types
        tsa:
          host_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDOJ2NAgif/I2ePWgqcNuDRyqsKo9CqglVDSRcpUEaDcLz/qUyEOZzfiP21nD01eKv22T6kO0lPeV3N3DMpJc0hxej9CV6C00a2Psk+B36AResIC2OFODkbty5+FcEky4ytjwpDtn+7DG0+FElSY72hEHOx0ymLy7BXswlyXEE+SlqsM4KVzP4x3K6LQ1LW2hq4wmwDXL+J16ejZWZT+P2UiQGIMk7MhnL36pCf3J1sgTwSb7b5LWFy1YH4FxkLMQ8kNRkxmmAj/8v2rv7Y8a/b5vaeZqT+kerPslbK09ZAWnKSCi3ZCcDsfSHi1OADO2igww+hZNmkB6R8LqVvaPlhi18u8ONTjtLV3YRefxbj5FZBdF+lGZ4Jjca0QdiPE2i8d1BhBb6Wd8Dv3zL2DkSHz2eqAyA6AteGNvBBTY3wVqh+ir2+tQc+defBA2sJSRKx8fJF4Qc1ig+SVx5t3nQVJu5Wg4RgT/rdo5/FX7snnfaSIXODHkX7Bv3pIkKHYtlji1l1wv0AkVGzDWnIB4Zi0KOfg4AqVe76gGVyzAWX5c2jVCrnI0GrTkxco/+6pHm3EihpDm3yCoFYABzYLBH8ksgin1KwAkqujqsoirW7CaWsubodQkHNmsxfkOegfLkJj4i9oL4suBHqxA007X8QFPy2Ad89VaY6OHIh8C2H2Q=="
          host: releng.ci.cf-app.com
          private_key: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIJKAIBAAKCAgEAsjV2Yeq4cCssiIP8V4zhN3Ga6u8k6miIIZJpctlj1x/5csVs
            +GWq8G7jQiao7p0mejq7+E8oXL3jeJrtmFLiJyWM4SAheEp6W4kvt7l4Q06giHNh
            fzOuMSTmal4DgBlMhULuMaqpCU9/KkYv7ktTvifB9FHMFpOPGALkZlDrf7YMGlbb
            EXUNeMMtwHYb6rhXnYAWXtieZWm/nLA7W3qiniY3ywX1Y0XDo5NR/TdMbbT/3MZG
            ObVJm5JhJm0omM/v6ZeIhDq+OuumNUGDqnOK7MxxrcTij+FH56R9zMh6lWXGiuJW
            wkWPAf/iAV11NHUwpym/5MYzsHmSEFIxfYIG8AGjw9XKPsljfmeolNqxDxobPY2c
            d6Fu58eSwdWQ/mJE3VUxEU8ecg/dpW3fZCZ4JuyXqTiiVZXJzbJ/MabtPfnMeaIf
            0R2xEyMgq2HMxNuLO/mQx3mpqWdZ4l4JSL56Bzu0nTcTFSWcXWtVXBsoGrba0T5a
            PKQl+0dTMxOg6qbbkMXH2jZUbAw/bTGK1XG242ycEX5jisjEZizK5GqJN3UHeVvT
            tytMuimWHdNItomGuAraJbm7jvMZ8yILXS5v232GG16qKKK5DDaaxWILUiQjCwzS
            M1qk5evHYZmeLPh4FgOqMx8kSAl8OipbGVNjxFH7hwFw/IDloAcCMEcIzUsCAwEA
            AQKCAgAy5TvrGRsVxe7RCkjeRDjqGcLxx9zWKYZ/eA4vo9B01wfp9GJ7yqV4R2MW
            OG5Uv4MGs5GNiCXx3rWBc1XaBAncvkeu3/tPHI43aEW9hfXH20PT1IgKyRq9pFk+
            FZ2QTylggc3/V0sxgofB7guwVckT7Mzi1x2fcQMUC3dplUC816Q7PYURRknTrIJ7
            jf/JGF7Fd5hr/Be4xOvZdydsp+ibnDShAhGkCX+nTuLCm7FzP5c3WVUjFBhymuqu
            C8zlX7WYFBQEF7bOoxBz80MEQj1yBa2NwEYoa2Ga0YqwGq2Pz2JVtfCrSSxfmNHW
            K/fWRIXhp/XLA6QtiXriuGaz/pe2J4CSJVRkNfdkEV3ac9ozFNeQeJWl3pcJBZ/Q
            3DfuLNjE3crTG6ks+gUssJv8R/VuwSRWMlsCsGzAlGCHs67/ERwqS/sWZ8ASxww8
            3M6xu6dEhttcEvcx6tnu+SzDC6EaW4VZ2q/rwKJjkmmQvMK0e1CRfK2tqf1YUrU8
            MXiSCLtLeMlzq+GD0jiEMK9poykXajyWvMgp0H985lg5r1uTROKrTvbuSHgM918d
            QZbnah3DDjkgrLdsoe2j415w3R3Zr7j7/b0Imandmvv4fw8CAOr1kjU0hHvAa0D/
            N5lR/6YrzhGsRppKLaIdj+ftybh+Tj2yVnGFlIxtSkkkJFjnyQKCAQEA6H6KczE8
            U4QqAHorGPLH2O1yA+1NmutuJ2tpo/IiXmiRLNhQq9rQkJd5CsKmC1xohnOD4T7j
            BRdvs84/ORmHohxYlbQSHh/eaL7hk+SAhg1AmcLdUGwV3lsw6HtXk7bn1koyGZL9
            Fa+ypB4AVMtEEJDvl9QNrmIuN7QK+FvqCu7iTsLtLpVNg9mHMQNogLF/gOQ9Q2Aw
            4RZSAq2VquPA1DIG45QFC0xePDIv3HjgViGX4CjT5gnjmVO5ltIlh/QHMed5dGSI
            rp3dayzUle1NMkNbSGdKi1vNHK/kUBgVwpgKiP2JSTPCdGU4pHHCX4rNniuYBRDv
            OUav8BC44Mkj/QKCAQEAxDnlQby6RCWTjhE23gFr79SdNd4SSrlekAs+ltmSNwBJ
            YxhqU6Fk+NK584XT3g5tBjTlY9iDBuCOQrwbTs+OyTiRv5NyQbDgKLQnpPaUbJDe
            MtkokQ/htuz4PQCDwZE2xqcBEuPIV7qa38PrTRQ8ST2TEga7kXtjeIGPY31OK2Vh
            v0qspWrJ2I6DxKeeJRu7OBs5HCiBKe3g4GQ8/MRhIn8V2fF4qSdjcbDXuowJqybn
            n+RPdn6s2bIDGA4k4JbYSAbptiylLrUeSb8AAZbKOo5XIqhypCSwYcM3ajSXrsf3
            ZcFTRIN9D/oy23F5namOs/nxTyAcE+gPOSv/9izk5wKCAQBZlfD5ZB5vu/yHRIv4
            yAwzzYLien0t1cwTSnNhZfrSUA6org2fuugk3wkYGVrsA8aPEFHf6GCH5Lj5Gt8H
            vIuj7rI/tSxKCVOlHvBDEYhonxCmbwziYVOn45Gb83MSiycYTmyxqA73XUVDsf/E
            rLJkg8Sex2oiKNjQRAL6Ikizv8raOIg2K/e7d4V9YGfTNxH/c3Mb1CPhh71AJO0H
            9UynN0OqS64J5XpmTZxdowImjjk8ed70xBi8SyO3NvCZS3G+TAhjzh1Q06mvE44y
            20akuImjA5IY0t3dUPVz22P/IKDmmnNdDqG+Qgaqbt9L+2sxqHCiex0C//bpVTg3
            /altAoIBAQCYdgNSmDiBSlDjSSzAQYqDxUaA3BKKTIzUjmgK/PFGGsrqW8YBRJ0X
            V2Nzer+rALpk4CR693aWmVLvNwhgq5PddD6KAx37PFpuRcunuI6J6+U4zNFgJF7T
            qjsV6ph0hUdyAcAr1R+MSkibI7ZnJRnSLi1fDCwgVSZsMv4d5vYdcaAI6RRLUjWS
            NOjcmv+dBXbpmP0+i5oP4eufbUKVgl+WVfe8ZonBpAD4DNcQ8k1w1cGR0eqLvtC+
            NDmDLzon5gwVqolcKkQNjlwCIIz4rxhhdsbs/sRUFM2Wp/8eXc6c1nG6dgMkcKVz
            DIsHRZugjGV8IO8E84XdUajCWxV9SFRxAoIBADONvgEWrAI7XZ+SnfQ0PhWOOMdl
            BRxSMRA8Buo7ksyggFawX2IgaCJWuZZIuSYZWktbY6oN6zwxnV+Durm8P29eDvj6
            /PjJPUelhbtoeekVar4r/C+isjSBHoS3Bm8x2NhfQzcW0mki9Tv4ephrme/TKndT
            q/231AwZXLHtyZZsCG79722y27k3Qf3H7G4dL47cRzzS8qQAlWn6NHOGMemA39hj
            6u0RACZD1oKPKjayA32ktdsQne6L2DkG9N+p/wSyiCkxnYqFMD84uEHZRLbN9drS
            GZmQn+3OJzg/V2rWWuM04bedPFtz3oWqot3nVbRP5++XCgEu6KQabKqTj1I=
            -----END RSA PRIVATE KEY-----
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777
        allow_host_access: true
        btrfs_store_size_mb: 144000

resource_pools:
  - name: workers
    network: private
    stemcell:
      name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      cpu: 2
      ram: 8_192
      disk: 160_000

compilation:
  workers: 3
  network: private
  reuse_compilation_vms: true
  cloud_properties:
    cpu: 2
    ram: 8_192
    disk: 30_000

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
