---
name: concourse

# replace with bosh status --uuid
director_uuid: 3fcab573-7a98-40dd-b2f1-a032821b53be

# pick a sane db name and password
atc_db_name: &atc-db-name atc
atc_db_role: &atc-db-role
  name: atc
  password: richpear91
atc_db_address: &atc-db-address concoursedb.chskomywcsf9.us-west-1.rds.amazonaws.com:5432

# replace with an AZ from your account
availability_zone: &az us-west-1b

resource_types: &resource_types
  - image: docker:///pcfseceng/email-resource#latest
    type: email
  - image: /var/vcap/packages/archive_resource
    type: archive
  - image: /var/vcap/packages/cf_resource
    type: cf
  - image: /var/vcap/packages/docker_image_resource
    type: docker-image
  - image: /var/vcap/packages/git_resource
    type: git
  - image: /var/vcap/packages/s3_resource
    type: s3
  - image: /var/vcap/packages/semver_resource
    type: semver
  - image: /var/vcap/packages/time_resource
    type: time
  - image: /var/vcap/packages/tracker_resource
    type: tracker
  - image: /var/vcap/packages/pool_resource
    type: pool
  - image: /var/vcap/packages/vagrant_cloud_resource
    type: vagrant-cloud
  - image: /var/vcap/packages/github_release_resource
    type: github-release
  - image: /var/vcap/packages/bosh_io_release_resource
    type: bosh-io-release
  - image: /var/vcap/packages/bosh_io_stemcell_resource
    type: bosh-io-stemcell
  - image: /var/vcap/packages/bosh_deployment_resource
    type: bosh-deployment

#  syslog:
#    destination:
#      address: logs3.papertrailapp.com:25911
#      transport: tls

# replace all addresses with your VPC range
#
# e.g. X.X.0.2 -> 10.0.0.2
networks:
  - name: concourse
    type: manual
    subnets:
      - range: 10.0.16.0/20
        reserved: [10.0.16.2 - 10.0.16.9]
        static:
          - &discovery_static_ip 10.0.16.10
        dns: [10.0.0.2]
        gateway: 10.0.16.1
        cloud_properties:
          security_groups: [concourse-InternalSecurityGroup-1NG976INKZJIS]
          subnet: subnet-6a19e233

releases:
  - name: concourse
    version: latest
  - name: garden-linux
    version: latest

jobs:
  - name: discovery
    instances: 1
    resource_pool: discovery
    persistent_disk: 1024
    templates:
      - {release: concourse, name: consul-agent}
    networks:
      - name: concourse
        static_ips: [*discovery_static_ip]
    properties:
      consul:
        agent:
          mode: server

  - name: web
    instances: 1
    resource_pool: web
    templates:
      - {release: concourse, name: consul-agent}
      - {release: concourse, name: tsa}
      - {release: concourse, name: atc}
    networks: [{name: concourse}]
    properties:
      atc:
        basic_auth_username: releng
        basic_auth_password: eyed1+kipsey
        postgresql:
          database: *atc-db-name
          role: *atc-db-role
          address: *atc-db-address

      tsa:
        host_key: |
          -----BEGIN RSA PRIVATE KEY-----
          MIIJKgIBAAKCAgEAzidjQIIn/yNnj1oKnDbg0cqrCqPQqoJVQ0kXKVBGg3C8/6lM
          hDmc34j9tZw9NXir9tk+pDtJT3ldzdwzKSXNIcXo/QlegtNGtj7JPgd+gEXrCAtj
          hTg5G7cufhXBJMuMrY8KQ7Z/uwxtPhRJUmO9oRBzsdMpi8uwV7MJclxBPkparDOC
          lcz+Mdyui0NS1toauMJsA1y/ideno2VmU/j9lIkBiDJOzIZy9+qQn9ydbIE8Em+2
          +S1hctWB+BcZCzEPJDUZMZpgI//L9q7+2PGv2+b2nmak/pHqz7JWytPWQFpykgot
          2QnA7H0h4tTgAztooMMPoWTZpAekfC6lb2j5YYtfLvDjU47S1d2EXn8W4+RWQXRf
          pRmeCY3GtEHYjxNovHdQYQW+lnfA798y9g5Eh89nqgMgOgLXhjbwQU2N8Faofoq9
          vrUHPnXnwQNrCUkSsfHyReEHNYoPklcebd50FSbuVoOEYE/63aOfxV+7J532kiFz
          gx5F+wb96SJCh2LZY4tZdcL9AJFRsw1pyAeGYtCjn4OAKlXu+oBlcswFl+XNo1Qq
          5yNBq05MXKP/uqR5txIoaQ5t8gqBWAAc2CwR/JLIIp9SsAJKro6rKIq1uwmlrLm6
          HUJBzZrMX5DnoHy5CY+IvaC+LLgR6sQNNO1/EBT8tgHfPVWmOjhyIfAth9kCAwEA
          AQKCAgEAm1vJi3rLA5a926Viq5kb0l5mie0sOuNfuAZkAwlxKmsSs6T1egwk8by+
          XlfxNNPM3ImZkJDxTYhMLfCNSawoLBSG4fJmnDb2ai9k328sYSTP288hX+sf9ogU
          7IYeeUlAqidK9/6XwfG6ffcxznpGFRRd7BwTijulmGHfc6ScsoG8VVu4RIYo5pDF
          pUPGMQ5K5wP1/I6v9gRkXFn1RME28PJTCj3HbpDAIZ9PAHp01KmMCOTRwnT1pGHM
          wZc+k1WUcJfndZ8+ZsLGBhCZFAsHmbQ0FOmL3CFBEOb4S4BbTUIcZ3xuUsrr7gzb
          NaNxcl4aGlUF+X4UGm58Ae3xVMWKcSHk+i+AuJ4c2fYYFIWtLqGPbFi+6JB7v7Zi
          DA+DDoIN3LUu0lXQE+0YrdfrcD6LA+Leqi3D5ebxXTpMtceXsZJxP08RKL1tRE/Y
          oZkHoZ9vcpv5lTtNVCOpoQHJ0xhaeKfQ0wrJH7Ldql0g2fjYnENYht6vf21pbOCG
          ycm4Q80KWqrO7JFswOaFMlzZSgFEcMN46sVi4O5WEVgez51ux1bIncgIWI5Qhccu
          W1lCoprbV4SNvrsTUoivpROHew/H6rbO3wgXBQNe5bzmcrFYl5o73BXBluWF7Tvq
          5k1hWLz/C5bMVb5OHHWQHkvRp4ESMT31lvX1mV4NU08WJKjmH9UCggEBAPoH6jvg
          bDBas6frFVFMxHH8MA1/jnyagM16RfTX4u82amPlO5E9J89AJloostCQRXFuitw+
          iN8zR71197jvxlZBofsHjE/94FqyIJ+vnJ1pdiXPjeMDNUQza5S4SEcdVgb98t9w
          yxNE4TszSyG66ij25PVjYJhHymM7bp+2YKcNdLmEMot7pUGOfkUScXHYORC3Oijt
          2OfSeDhbYS8+nWGQHkKOpurnG5EFcgXVFKfj2qzYCCASQIniNERe6zva3ayYc9Tx
          C43u3tciYtSssfJCj9qTLIbRbPGzpLXGPUXruiFTudR2pZPCae4hCk/6tDJh1Ou6
          xlWvCJM1Ckf4DhsCggEBANMTUHsrwhyuDOP8ow3XSXQtE7px7NlgmvBWyO24y4FV
          hu9xg5Im9AZQLu27UyDI8Zh+0LnIQk9TTNQ1CvLb3vIzTIpmy1TOuYI73W4rkV+Z
          sZYtEZuMzCjdlW6QhXDJlAi/C2gtTNi/jvPOzhGY8NJSGHtRz/gETgozJFriX5vZ
          02TNuVqMVqfPuXx5c1bHNslH8AhRpiqP5EgnDi9Zh0HDosQWcJu+cFRxeWEfWsYa
          hCZhtdMj4uj0x6vQ13ez6DS7SAVKMUNcaX9QlkYytGQrt34jIJGS9PeSWcVDg5kJ
          rCP6E9Oj+AQVLlko5zZqsdBVp/k+DvjXENKJ59iA0RsCggEBAJ+gyAG8UTY54jNV
          mgGSwmSHfmJPyrdwqMUGyHz+C8tvcVMfuf0LD0x5B0NOcoNHaJ531b2xSw89HRMv
          qp1ur7DILFMpSYKUclVVHhD1PEcfWqffMBX8KVjGf2uuj66fYxoJrbLLv0spEacL
          I2+Adxj6L8kezj/KrcLW4dSjymc85wW+CcsVgLcu8xzEHptxUVWDtWUGHRI8RDau
          2IgiMLZmHXueuaCFNgtLb7WbiZl6llT9g4p+PKgLPBVeiE5peFdF6cXMsvTFyY2O
          TYy8SMuDhXYluirEsApMB99plhr62ZWHb7/ek+2XFKxMedoAFGWKIjbxwshXfGEH
          Xu39x3sCggEAaRKETcxKpNw/rn5k7M7u0dZeq8FqlgtxFZMeEribFZbtxORNCsQ5
          Vas0sUM+7mMZYUA/xzvZRoPBCyIcgSjSot7Gi18AeQcvcZU7dUxa4awwqwFkcnp0
          ZyNm79MhmjO+bVws4X8rcfppvxSDoF7yAsC7Tyg6zsvVzV4ICvYFgh+9C8EdM+YI
          fSD6xOvwbpJcw3X8FygN/8IBcal/djKrEiHBNLu28tCqOl8CfUaOeW9ZuYGKccC7
          hBvWCcG8gOod/aH9CCUWwOGP4sDLDcbP5c2dWj1CSTVOnK9N4NTq/ZPDDWW/2OsW
          23Fv0RJ7hqs2OO9q3rf13AmzZhsgPrZhYQKCAQEAokGaEyMUs6snEHc8xU7nVcbc
          MkYa2vtSKJxzKL76u91KbTnbPl+DpZ6nu0fA/3C0eMXlJHSdxZ1E1EnuKqUPLsfI
          8puyDhuIKYySgyy/L/I2iteafaK02UHqLylnB/uRGGeWn69PMAvS7o0V2yFc5vP8
          ZrWdnmI9sKK+NYGDuI4If5+hWkJFNs2R0FA8aIHtSur6OseuhoIzLl8Mj557+LA4
          ei9j53oJIRMfouypcpHD6CJM7LO3w5Gfuqa/RFdghV/xlXvDaFYqMVU1AQcw+C0V
          +cercc0JkAFc40HppS2+p0d8Ui/UO67IlyKy2xVRUseAVXoqtPllh3c2PvBb6A==
          -----END RSA PRIVATE KEY-----
        authorized_keys:
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCyNXZh6rhwKyyIg/xXjOE3cZrq7yTqaIghkmly2WPXH/lyxWz4ZarwbuNCJqjunSZ6Orv4TyhcveN4mu2YUuInJYzhICF4SnpbiS+3uXhDTqCIc2F/M64xJOZqXgOAGUyFQu4xqqkJT38qRi/uS1O+J8H0UcwWk48YAuRmUOt/tgwaVtsRdQ14wy3AdhvquFedgBZe2J5lab+csDtbeqKeJjfLBfVjRcOjk1H9N0xttP/cxkY5tUmbkmEmbSiYz+/pl4iEOr4666Y1QYOqc4rszHGtxOKP4UfnpH3MyHqVZcaK4lbCRY8B/+IBXXU0dTCnKb/kxjOweZIQUjF9ggbwAaPD1co+yWN+Z6iU2rEPGhs9jZx3oW7nx5LB1ZD+YkTdVTERTx5yD92lbd9kJngm7JepOKJVlcnNsn8xpu09+cx5oh/RHbETIyCrYczE24s7+ZDHeampZ1niXglIvnoHO7SdNxMVJZxda1VcGygattrRPlo8pCX7R1MzE6DqptuQxcfaNlRsDD9tMYrVcbbjbJwRfmOKyMRmLMrkaok3dQd5W9O3K0y6KZYd00i2iYa4CtolubuO8xnzIgtdLm/bfYYbXqooorkMNprFYgtSJCMLDNIzWqTl68dhmZ4s+HgWA6ozHyRICXw6KlsZU2PEUfuHAXD8gOWgBwIwRwjNSw=="


      consul:
        agent:
          servers: {lan: [*discovery_static_ip]}

  - name: worker
    instances: 3
    resource_pool: workers
    templates:
      - {release: concourse, name: consul-agent}
      - {release: concourse, name: groundcrew}
      - {release: concourse, name: baggageclaim}
      - {release: garden-linux, name: garden}
    networks: [{name: concourse}]
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777
        btrfs_store_size_mb: 150000

      consul:
        agent:
          servers: {lan: [*discovery_static_ip]}

      groundcrew:
        tsa:
          host_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDOJ2NAgif/I2ePWgqcNuDRyqsKo9CqglVDSRcpUEaDcLz/qUyEOZzfiP21nD01eKv22T6kO0lPeV3N3DMpJc0hxej9CV6C00a2Psk+B36AResIC2OFODkbty5+FcEky4ytjwpDtn+7DG0+FElSY72hEHOx0ymLy7BXswlyXEE+SlqsM4KVzP4x3K6LQ1LW2hq4wmwDXL+J16ejZWZT+P2UiQGIMk7MhnL36pCf3J1sgTwSb7b5LWFy1YH4FxkLMQ8kNRkxmmAj/8v2rv7Y8a/b5vaeZqT+kerPslbK09ZAWnKSCi3ZCcDsfSHi1OADO2igww+hZNmkB6R8LqVvaPlhi18u8ONTjtLV3YRefxbj5FZBdF+lGZ4Jjca0QdiPE2i8d1BhBb6Wd8Dv3zL2DkSHz2eqAyA6AteGNvBBTY3wVqh+ir2+tQc+defBA2sJSRKx8fJF4Qc1ig+SVx5t3nQVJu5Wg4RgT/rdo5/FX7snnfaSIXODHkX7Bv3pIkKHYtlji1l1wv0AkVGzDWnIB4Zi0KOfg4AqVe76gGVyzAWX5c2jVCrnI0GrTkxco/+6pHm3EihpDm3yCoFYABzYLBH8ksgin1KwAkqujqsoirW7CaWsubodQkHNmsxfkOegfLkJj4i9oL4suBHqxA007X8QFPy2Ad89VaY6OHIh8C2H2Q=="
        tags: ["aws","vcloud"]
        resource_types: *resource_types

  - name: default_worker
    instances: 2
    resource_pool: default_workers
    templates:
      - {release: concourse, name: consul-agent}
      - {release: concourse, name: groundcrew}
      - {release: concourse, name: baggageclaim}
      - {release: garden-linux, name: garden}
    networks: [{name: concourse}]
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777
        btrfs_store_size_mb: 150000

      consul:
        agent:
          servers: {lan: [*discovery_static_ip]}

      groundcrew:
        tsa:
          host_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDOJ2NAgif/I2ePWgqcNuDRyqsKo9CqglVDSRcpUEaDcLz/qUyEOZzfiP21nD01eKv22T6kO0lPeV3N3DMpJc0hxej9CV6C00a2Psk+B36AResIC2OFODkbty5+FcEky4ytjwpDtn+7DG0+FElSY72hEHOx0ymLy7BXswlyXEE+SlqsM4KVzP4x3K6LQ1LW2hq4wmwDXL+J16ejZWZT+P2UiQGIMk7MhnL36pCf3J1sgTwSb7b5LWFy1YH4FxkLMQ8kNRkxmmAj/8v2rv7Y8a/b5vaeZqT+kerPslbK09ZAWnKSCi3ZCcDsfSHi1OADO2igww+hZNmkB6R8LqVvaPlhi18u8ONTjtLV3YRefxbj5FZBdF+lGZ4Jjca0QdiPE2i8d1BhBb6Wd8Dv3zL2DkSHz2eqAyA6AteGNvBBTY3wVqh+ir2+tQc+defBA2sJSRKx8fJF4Qc1ig+SVx5t3nQVJu5Wg4RgT/rdo5/FX7snnfaSIXODHkX7Bv3pIkKHYtlji1l1wv0AkVGzDWnIB4Zi0KOfg4AqVe76gGVyzAWX5c2jVCrnI0GrTkxco/+6pHm3EihpDm3yCoFYABzYLBH8ksgin1KwAkqujqsoirW7CaWsubodQkHNmsxfkOegfLkJj4i9oL4suBHqxA007X8QFPy2Ad89VaY6OHIh8C2H2Q=="
        resource_types: *resource_types

disk_pools:
  - name: database
    disk_size: 10240
    cloud_properties:
      type: gp2

resource_pools:
  - name: web
    network: concourse
    stemcell: &stemcell
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      instance_type: m3.medium
      availability_zone: *az
      elbs: [concourse-WebELBLo-1SZ5ILPCZCQ6B]

  - name: discovery
    network: concourse
    stemcell: *stemcell
    cloud_properties:
      instance_type: m3.medium
      availability_zone: *az

  - name: databases
    network: concourse
    stemcell: *stemcell
    cloud_properties:
      instance_type: m3.medium
      availability_zone: *az

  - name: workers
    network: concourse
    stemcell: *stemcell
    cloud_properties:
      instance_type: m3.large
      availability_zone: *az
      ephemeral_disk:
        size: 200_000
        type: gp2

  - name: default_workers
    network: concourse
    stemcell: *stemcell
    cloud_properties:
      instance_type: m3.xlarge
      availability_zone: *az
      ephemeral_disk:
        size: 200_000
        type: gp2

compilation:
  workers: 3
  network: concourse
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: c4.large
    availability_zone: *az
    ephemeral_disk:
      size: 30000 # in MB
      type: gp2

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
