---
name: concourse

# replace with bosh status --uuid
director_uuid: 3fcab573-7a98-40dd-b2f1-a032821b53be

# pick a sane db name and password
atc_db_name: &atc-db-name atc
atc_db_role: &atc-db-role
  name: atc
  password: richpear91
atc_db_address: &atc-db-address concoursedb.chskomywcsf9.us-west-1.rds.amazonaws.com:5432

# replace with an AZ from your account
availability_zone: &az us-west-1b

blackbox_config: &blackbox_config
  expvar:
    datadog:
      api_key: bc6ef2a698fdb4fb1400d4542aec0c39

  syslog:
    destination:
      address: logs3.papertrailapp.com:25911
# replace all addresses with your VPC range
#
# e.g. X.X.0.2 -> 10.0.0.2
networks:
  - name: concourse
    type: manual
    subnets:
      - range: 10.0.16.0/20
        reserved: [10.0.16.2 - 10.0.16.9]
        static:
          - &discovery_static_ip 10.0.16.10
        dns: [10.0.0.2]
        gateway: 10.0.16.1
        cloud_properties:
          security_groups: [concourse-InternalSecurityGroup-1NG976INKZJIS]
          subnet: subnet-6a19e233

releases:
  - name: concourse
    version: latest
  - name: garden-linux
    version: latest

jobs:
  - name: discovery
    instances: 1
    resource_pool: discovery
    persistent_disk: 1024
    templates:
      - {release: concourse, name: consul-agent}
      - {release: concourse, name: blackbox}
    networks:
      - name: concourse
        static_ips: [*discovery_static_ip]
    properties:
      blackbox: *blackbox_config
      consul:
        agent:
          mode: server

  - name: web
    instances: 1
    resource_pool: web
    templates:
      - {release: concourse, name: consul-agent}
      - {release: concourse, name: blackbox}
      - {release: concourse, name: tsa}
      - {release: concourse, name: atc}
    networks: [{name: concourse}]
    properties:
      blackbox: *blackbox_config
      atc:
        basic_auth_username: releng
        basic_auth_password: eyed1+kipsey
        postgresql:
          database: *atc-db-name
          role: *atc-db-role
          address: *atc-db-address

      tsa:
        host_key: |
          -----BEGIN RSA PRIVATE KEY-----
          MIIJKQIBAAKCAgEAsF4lAfEHdgXVmZpvYpn2M58x9nUGNGNB2LFV8DZwUBz6BqvJ
          mW9d2Xtlg0zLCqUKQUVV0npsvAxAlRGXqsU8GrVT8W4uatOqvo07oIVHsCc0B9c7
          VHfTAVaD6cLuecLPNPysJJhzIxz1IMwPH0pT5Hpph+dooopS7kD4haUIgj9ka4Pd
          OMvxmdfjyvCspvbrvAX3eXINjcszgXyHn8x1sBvzPVMWdAh0bK9xGOXQuyl5VcgZ
          rXvn9PbyKRLeLxhwrjvKdwn6kSBygv0vgH11Zb3QNnRdt3C38gFLJ5x4Eu3qhanB
          8lGUSPFNodsL+fI5JkVIRNZ/K8Ol5W7veTeXNH+DZK8El941aeR9J1gTtzOGmWHy
          sLt1Z2N5oHHZICOqd6zLNPgTnfTX0g+Vqf26kBI3/HVgwDBPlV0SwIgqW+fTgR4p
          CzpAHr897KeDZfRwQL71pLPJKcE96uBAGIDjenVxoAjzg+XqocojvcV30rkV/wWs
          BJkDe6Hl75VuDxwquLmcaIb18YJSU9HxU1qr4R92qH0FT+AVIYPRpzI9U3oo649d
          LIrdEFsDonA85z1pl7x6hD0vJa4dGFwbiZYkspQDFzx0hjHoXRzU/pvPo9F7Bm1O
          k+mdFyko0WwmbQGj/oRwRf9WPWBeAV57wuzCWQO+ccezRM/VGbcEiljH30MCAwEA
          AQKCAgEAkWwvK5ioREKvS0YxzaWRgiMjuUno4c1t/9TJPZZFqWkbJ+ECC8fuJGNA
          4rCxQoevGv6mszRK8AtSPRgSbLbQxlz5aDsnfuIlCZW+sq7y22aX2lc4Dn/2tkW1
          40veAvwEinZFIq+pUCySWoaneW96GQxuc6b1egCAPP/Ja7kWeP74OEa0ZB6Vifqf
          Uzh7w/gZjCGHWtYWIvKH957M3ZBjAeEqAUi/XNGT3gITSSpFn+2kpHyn34opSq1M
          I13xYffPAXs/iEPsHToZ8bP+NP49jLSkOCJfG+CPa7ZxV6oGv+T42VmOF9X4ZOTC
          1FCfYWq+gLXjzw7mMRnTcoi0YMjbnQkIydI7VE+AHG9D4PG5lCLrOU24ExPHCzfE
          WhGs5k9H6Wcdeq03MRSV4VVTQusZnazGPUsHGxYDOH2MBcYfx0p/jNRnJ3/n01aL
          XcnzOocbQmccRx8D9EVEnADHi/pdUxMg4kW92/nleidwjRJ2ay2W4Gh0gnkVg6Fm
          f/XN1JXQFfiTQGPTCLuyiX4i0DC2t7HeCdfEEFh99QSM67YdIJfOB5MqZt1v0GNg
          PzGnLJwFyzZAMosI6y18k6RQ3yU04Jv0HTSL0rPjJ+OnL0Mds4ZBEtsjSl5Y/RhV
          4apGMMyMED6/KN2TOPztXa2sxGfiL6JIzSnnMZh9ueOKgZWdvTECggEBAOC8mtYj
          eN04TRLuyzs5CWeyBGvLGQra7AIZJMDq6+bEKJQbO+BR0AG1eqVO0qa9/FtG6MLU
          kRwy8R0mqdMtWAi0qiLRMcLmGDpf4I1SQMqrWpzYt0C/nEZkpprbKwerueIaQwcr
          q62xBkqlsRwLgRI3FT1ORw+enH+4lCUQrLnOMjzs8z4d6v2XJ6KXdS/8rnV7Fiqe
          qRWiitZ6S4yXBSAgoPXsypc5OZl4avBXMBuOxvvzKb9z+Gf+a6CG+/ObPwcEfAGt
          oujsWRq584zXIAFkTjVpQdlSAjbGwY/itlg8IodDrb8TW5aaM4utOSgC6x3l0gRL
          ibdS9asiwJ985h8CggEBAMjnAhz/cooT6zOx2fpfdafUQjkWcuZc61v/SpLVeZBy
          j7gihkYSEHHuWBUHbNJ9ASMsRAqayLeDWKCoW0GulduyMfzUrjyyP8EuQmy2ePTy
          s9lCB6GyGBJYyD06pb132h4UxvOMgVPHxtm1TdzYaMoPWTWsOa/mVQPKc99+8Tf/
          ERm3FK8ITnUQMaYUGADUbpbkaDKh4zWFY5FLzCfUYPSv0/gS1AKiqjMnPs4eoRtr
          YFVLqvlN4kT0oTAsxzaGIGfDu94BDqmDtwpc0o8JicD20Al6XJnySViB6CQo+uB8
          +ZWeB286PQBgQjxOhghKeXbgBsoB6ErGhMwWEI6S+l0CggEBAJWNbQxrdpbgTIn4
          1s2GWzfiQwbolLWgkcWjrc2jh3B9wPMuXF4ek2lPt1oiZhQIAdNMEMD2a8p0K/fW
          LtUVK6w/bajVxWOJcz4FZ40j23IDLb2KighQelJt0GDk0HG+WWiZSVmQOiLP1vv9
          3ypmjXHtrfiqCqfeSQ7FafBwdEEBcnUQyZ3gkuxGll2gpJ9Wa1JKoqmiA6seC35G
          y9e29/Y1QGfnN7oCns3+UEu3+Y+dJ9WqL3H0Xq31pPGiYi/uc7bbyRnkzrBp97HN
          ZMGotue2NEVe0i8oX8jL4ys5F1cITYHuC8VHwH8sBnlAwPRbXNL8iRHKos6YKlvE
          OKLpnskCggEAD5gWyudtHZikNhQFBnEoccmBBmteqdDml/J9+F3HnNW3oCRV5dR7
          IEzO23sDEGeRkghak7QmBlCUrYvD4ZpKmY4AYU6k46M2XalYkJWtV94K5b9BVmS7
          h5kKme4WdVl7PcCBHOB4HWexYK65B35oy95bH1Zp9+RaDvxE+EEjOiR7UFKssVVk
          uaNzJyACKPZUSzQZfmygdUQQUXPfueu7RuLrAiN7/2Re76+JKXipKrav+I7yC33n
          JVETveiL4giRNVy1FWthlvjZWV2RHncwESFXTpUH4Q80cEFNIplnt8sbmGh2zURo
          /cF7ArFZqAUX3olPHZj+TeeQ4UKJMHfqJQKCAQBpk3zxrmmzNNVpycMgz4svxNty
          WHZQpZwAM5lnUaqifmSuGHZMtBMcoLVWKAldCDS1oUKot27pmkG/ty22BxmqdS6D
          rp+vrxnCjMMpjQCG79MF7WnRcpobz505QpK9Np9ZP9oEtDvOWyu6bZxCgcCyyYXw
          7TXl4+jd3mWQ/rl5dv5KpuFY/5OPco0IKoTOw+y2/sOaaOAmakqRDD57d4BKTRgz
          UfmRN+KRTUurYnY6UtV8FR07CIaMrU/y9i/DqGHyBUONEMFsD9eXqGsgj6JmYrKY
          dVDBsMj/vgjFRdr6k+1PltY6uuU1jLQL3WB0SKVuh8EJiGk+UaTgkP1VNhvN
          -----END RSA PRIVATE KEY-----
        authorized_keys:
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDAqx2BVNHaIImwaKPqXj8RbO3u8jJkfCasC0fs3Kf5h66ZqrJgAhKvmSKnkNh0GPam56L3KyVgqGUTIkm3KsytdXr/UhB0LMBvWKIdws80KwnmJ7h5gj2RjFJRTLUTqgT1CbN8GSCtvLr0ffw5Kj/fLt5/jYDgwCON+bvBQj1WYKP/t2nmZQwkZIHEUz2SH5Rf1IzCB7yFJD+xmsGv15U2SvsSUz0g4wCo7E/RsCRfLFZP8R1OJNlAUL6qCk4r88PEBz/L84kXqk52F4OVComl7HYAbOP36RjPWWza26DlPMkfIOsHFx+lRvbU1xbkCpsjSMTJCrfUTbq+glfLOdT2L6MNJcvtgdrhUe1vHTt+zQiNrkjmDUhkcTZTe6rNIHL8RJLLz7XPJPc1oWvFX/1dGRrFjlvCuK4InRpEo2I9G3yVBHthUNvOCtlzarmgxKSt/Am6ZMsKPh5Q+/ew7GK5xyRzyJiyDIEl6BUx4DA36ojhlaYyjeRwp7CcR96cdlQNjYpLEItKtyKeB8JzcJAL0g3Ti5/XVqK+WcENpurmYGeOJdzT/gqt024ZYD9AaUQNG9pAMeQ/NMHjyuDL+dRnLjne1e0BSE1kBRoKnMqWnz2smKI0q38wIvr54htMvs9FvREK2D83Ma0CMvwROrm3H68yP7mB2EnnBcxs4EnI6Q=="
        atc:
          username: releng
          password: eyed1+kipsey

      consul:
        agent:
          servers: {lan: [*discovery_static_ip]}

  - name: worker
    instances: 1
    resource_pool: workers
    templates:
      - {release: concourse, name: consul-agent}
      - {release: concourse, name: blackbox}
      - {release: concourse, name: groundcrew}
      - {release: garden-linux, name: garden}
    networks: [{name: concourse}]
    properties:
      blackbox: *blackbox_config
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777
        default_container_grace_time: 30m
        btrfs_store_size_mb: 150000

      consul:
        agent:
          servers: {lan: [*discovery_static_ip]}

      groundcrew:
        tsa:
          host_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCwXiUB8Qd2BdWZmm9imfYznzH2dQY0Y0HYsVXwNnBQHPoGq8mZb13Ze2WDTMsKpQpBRVXSemy8DECVEZeqxTwatVPxbi5q06q+jTughUewJzQH1ztUd9MBVoPpwu55ws80/KwkmHMjHPUgzA8fSlPkemmH52iiilLuQPiFpQiCP2Rrg904y/GZ1+PK8Kym9uu8Bfd5cg2NyzOBfIefzHWwG/M9UxZ0CHRsr3EY5dC7KXlVyBmte+f09vIpEt4vGHCuO8p3CfqRIHKC/S+AfXVlvdA2dF23cLfyAUsnnHgS7eqFqcHyUZRI8U2h2wv58jkmRUhE1n8rw6Xlbu95N5c0f4NkrwSX3jVp5H0nWBO3M4aZYfKwu3VnY3mgcdkgI6p3rMs0+BOd9NfSD5Wp/bqQEjf8dWDAME+VXRLAiCpb59OBHikLOkAevz3sp4Nl9HBAvvWks8kpwT3q4EAYgON6dXGgCPOD5eqhyiO9xXfSuRX/BawEmQN7oeXvlW4PHCq4uZxohvXxglJT0fFTWqvhH3aofQVP4BUhg9GnMj1Teijrj10sit0QWwOicDznPWmXvHqEPS8lrh0YXBuJliSylAMXPHSGMehdHNT+m8+j0XsGbU6T6Z0XKSjRbCZtAaP+hHBF/1Y9YF4BXnvC7MJZA75xx7NEz9UZtwSKWMffQw=="
        tags: ["aws","vcloud"]

  - name: default_worker
    instances: 1
    resource_pool: default_workers
    templates:
      - {release: concourse, name: consul-agent}
      - {release: concourse, name: blackbox}
      - {release: concourse, name: groundcrew}
      - {release: garden-linux, name: garden}
    networks: [{name: concourse}]
    properties:
      blackbox: *blackbox_config
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777
        default_container_grace_time: 30m
        btrfs_store_size_mb: 150000

      consul:
        agent:
          servers: {lan: [*discovery_static_ip]}

      groundcrew:
        tsa:
          host_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCwXiUB8Qd2BdWZmm9imfYznzH2dQY0Y0HYsVXwNnBQHPoGq8mZb13Ze2WDTMsKpQpBRVXSemy8DECVEZeqxTwatVPxbi5q06q+jTughUewJzQH1ztUd9MBVoPpwu55ws80/KwkmHMjHPUgzA8fSlPkemmH52iiilLuQPiFpQiCP2Rrg904y/GZ1+PK8Kym9uu8Bfd5cg2NyzOBfIefzHWwG/M9UxZ0CHRsr3EY5dC7KXlVyBmte+f09vIpEt4vGHCuO8p3CfqRIHKC/S+AfXVlvdA2dF23cLfyAUsnnHgS7eqFqcHyUZRI8U2h2wv58jkmRUhE1n8rw6Xlbu95N5c0f4NkrwSX3jVp5H0nWBO3M4aZYfKwu3VnY3mgcdkgI6p3rMs0+BOd9NfSD5Wp/bqQEjf8dWDAME+VXRLAiCpb59OBHikLOkAevz3sp4Nl9HBAvvWks8kpwT3q4EAYgON6dXGgCPOD5eqhyiO9xXfSuRX/BawEmQN7oeXvlW4PHCq4uZxohvXxglJT0fFTWqvhH3aofQVP4BUhg9GnMj1Teijrj10sit0QWwOicDznPWmXvHqEPS8lrh0YXBuJliSylAMXPHSGMehdHNT+m8+j0XsGbU6T6Z0XKSjRbCZtAaP+hHBF/1Y9YF4BXnvC7MJZA75xx7NEz9UZtwSKWMffQw=="
        resource_types:
          - image: docker:///pcfseceng/email-resource#latest
            type: email
          - image: /var/vcap/packages/archive_resource
            type: archive
          - image: /var/vcap/packages/cf_resource
            type: cf
          - image: /var/vcap/packages/docker_image_resource
            type: docker-image
          - image: /var/vcap/packages/git_resource
            type: git
          - image: /var/vcap/packages/s3_resource
            type: s3
          - image: /var/vcap/packages/semver_resource
            type: semver
          - image: /var/vcap/packages/time_resource
            type: time
          - image: /var/vcap/packages/tracker_resource
            type: tracker
          - image: /var/vcap/packages/pool_resource
            type: pool
          - image: /var/vcap/packages/vagrant_cloud_resource
            type: vagrant-cloud
          - image: /var/vcap/packages/github_release_resource
            type: github-release
          - image: /var/vcap/packages/bosh_io_release_resource
            type: bosh-io-release
          - image: /var/vcap/packages/bosh_io_stemcell_resource
            type: bosh-io-stemcell
          - image: /var/vcap/packages/bosh_deployment_resource
            type: bosh-deployment

disk_pools:
  - name: database
    disk_size: 10240
    cloud_properties:
      type: gp2

resource_pools:
  - name: web
    network: concourse
    stemcell: &stemcell
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      instance_type: m3.medium
      availability_zone: *az
      elbs: [concourse-WebELBLo-1SZ5ILPCZCQ6B]

  - name: discovery
    network: concourse
    stemcell: *stemcell
    cloud_properties:
      instance_type: m3.medium
      availability_zone: *az

  - name: databases
    network: concourse
    stemcell: *stemcell
    cloud_properties:
      instance_type: m3.medium
      availability_zone: *az

  - name: workers
    network: concourse
    stemcell: *stemcell
    cloud_properties:
      instance_type: m3.large
      availability_zone: *az
      ephemeral_disk:
        size: 200_000
        type: gp2

  - name: default_workers
    network: concourse
    stemcell: *stemcell
    cloud_properties:
      instance_type: m3.xlarge
      availability_zone: *az
      ephemeral_disk:
        size: 200_000
        type: gp2

compilation:
  workers: 3
  network: concourse
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: c4.large
    availability_zone: *az
    ephemeral_disk:
      size: 30000 # in MB
      type: gp2

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
