---
name: vsphere-concourse-worker

director_uuid: 3f9c052c-8afe-4ad6-8a89-85328792bc60

networks:
- name: private
  type: manual
  subnets:
  - range: 10.85.1.0/24
    gateway: 10.85.1.1
    dns: [10.87.8.10,10.87.8.11]
    cloud_properties: {name: badger}

releases:
  - name: concourse
    version: latest
  - name: garden-linux
    version: latest

jobs:
  - name: worker
    instances: 1
    resource_pool: workers
    templates:
      - {release: concourse, name: groundcrew}
      - {release: garden-linux, name: garden}
    networks: [{name: private}]
    properties:
      groundcrew:
        tags: ["vsphere"]
        garden:
          forward_address: 127.0.0.1:7777
        tsa:
          host_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCwXiUB8Qd2BdWZmm9imfYznzH2dQY0Y0HYsVXwNnBQHPoGq8mZb13Ze2WDTMsKpQpBRVXSemy8DECVEZeqxTwatVPxbi5q06q+jTughUewJzQH1ztUd9MBVoPpwu55ws80/KwkmHMjHPUgzA8fSlPkemmH52iiilLuQPiFpQiCP2Rrg904y/GZ1+PK8Kym9uu8Bfd5cg2NyzOBfIefzHWwG/M9UxZ0CHRsr3EY5dC7KXlVyBmte+f09vIpEt4vGHCuO8p3CfqRIHKC/S+AfXVlvdA2dF23cLfyAUsnnHgS7eqFqcHyUZRI8U2h2wv58jkmRUhE1n8rw6Xlbu95N5c0f4NkrwSX3jVp5H0nWBO3M4aZYfKwu3VnY3mgcdkgI6p3rMs0+BOd9NfSD5Wp/bqQEjf8dWDAME+VXRLAiCpb59OBHikLOkAevz3sp4Nl9HBAvvWks8kpwT3q4EAYgON6dXGgCPOD5eqhyiO9xXfSuRX/BawEmQN7oeXvlW4PHCq4uZxohvXxglJT0fFTWqvhH3aofQVP4BUhg9GnMj1Teijrj10sit0QWwOicDznPWmXvHqEPS8lrh0YXBuJliSylAMXPHSGMehdHNT+m8+j0XsGbU6T6Z0XKSjRbCZtAaP+hHBF/1Y9YF4BXnvC7MJZA75xx7NEz9UZtwSKWMffQw=="
          host: releng.ci.cf-app.com
          private_key: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIJKgIBAAKCAgEAwKsdgVTR2iCJsGij6l4/EWzt7vIyZHwmrAtH7Nyn+Yeumaqy
            YAISr5kip5DYdBj2puei9yslYKhlEyJJtyrMrXV6/1IQdCzAb1iiHcLPNCsJ5ie4
            eYI9kYxSUUy1E6oE9QmzfBkgrby69H38OSo/3y7ef42A4MAjjfm7wUI9VmCj/7dp
            5mUMJGSBxFM9kh+UX9SMwge8hSQ/sZrBr9eVNkr7ElM9IOMAqOxP0bAkXyxWT/Ed
            TiTZQFC+qgpOK/PDxAc/y/OJF6pOdheDlQqJpex2AGzj9+kYz1ls2tug5TzJHyDr
            BxcfpUb21NcW5AqbI0jEyQq31E26voJXyznU9i+jDSXL7YHa4VHtbx07fs0Ija5I
            5g1IZHE2U3uqzSBy/ESSy8+1zyT3NaFrxV/9XRkaxY5bwriuCJ0aRKNiPRt8lQR7
            YVDbzgrZc2q5oMSkrfwJumTLCj4eUPv3sOxiucckc8iYsgyBJegVMeAwN+qI4ZWm
            Mo3kcKewnEfenHZUDY2KSxCLSrcingfCc3CQC9IN04uf11aivlnBDabq5mBnjiXc
            0/4KrdNuGWA/QGlEDRvaQDHkPzTB48rgy/nUZy453tXtAUhNZAUaCpzKlp89rJii
            NKt/MCL6+eIbTL7PRb0RCtg/NzGtAjL8ETq5tx+vMj+5gdhJ5wXMbOBJyOkCAwEA
            AQKCAgByTRHUCF326hbFcU7NW9xOmjEN8OG0e3L13jttafq9LqGGyJ3KF3C+fDry
            7ht7xNOPcRxdRluGXGCaWV0iLWIABhJSJn1cbrA7XnnO7iO+70mQIUBv1bRxBK5R
            TRCf+d23AWpZ1Q5uA+ll4tgfkdESttuJEInEzDhLojyhCosZE3w32Lga1xe8/2N8
            9WUxq0p7D73x3mUZF8gxtX3ytBLxgsowtPEu8X0Suh8gZz8st0D9bC3WjkXUwhJb
            DoIR0Svyv9o5ROGwCHlD1e9aHEZNCVt4JSGZkdAGMydBL8rkNIuczAqiyjUb+F23
            J2ONJj2jUShtnM4yRWrkWq97AXQ1ED+rynr7YiDZ0n7k9vlClasGq/AXxf9YHWWM
            ZvrIBbUm5jGfqTs6Ava0E45tk7flnforS60y9+Xg4yOmlPfiLgNsdNjhuBYIYwq9
            zxXOtcuqU8DZV+Ey0g3zwfPaAk1jE9mUsPIAyOyJDCqWWXUdj+21RdZPVaK9RR22
            CbCmJFZfvhtLaQ0MQICCdniRGExCN5SLPY8KIG8mxm1Tf7OazyucCx+xHeVO8SnI
            CLPb5vbq+Kfrm0gZc+zPN6EHAOaPSBPxZaMr45FKBu4lqFt6tCmJGlZmXwgmPe4y
            FREoowLibAuUmYw1V7jzlOHFRtFrIOAzmFM0iz+3C76sm8v3gQKCAQEA93PnHMAg
            dT0QaNZftBjvfngkGZspYfik3IYspzzJgU3nY1qNtmhlP6eroiA2O0VMjrlduSqt
            131yHbesaEstkOtTvfDZJieEMW5UfC5rBmajR4+xOZ8TWn0suKkJUzx3g23TiZMG
            2Rnra3BbklQRoeNL8RX0UVJO9yHnkMPM/P05P8WbKNfWIb9SQyUKKJFuOK5i8fw6
            RJFbqpZx/BbjRv8hBemVubJeGxO/TyHCPVo77hXzHbNh3KTwym5djAoqA/975CMD
            mC5dveOegsSmMxgkg5LqafBLC0qnr/PBepyDWp9QILw41oDwOJpqA87AXnjL49Be
            wRE0v4xajE4mAwKCAQEAx1LIavoQSA79B7CBd0N4qesJj67EG+Iybvz+FRE1IgIF
            vXMzLSROTlb49+d4Kb1gQG0kyrTHGRKBXkaB8fzIE0ZIR486unSncgy4yH0bijyQ
            7KjvgtvT/zncT0RbY8szgeRKogHCaUEvKDwaVV6huHQ/IJbYmcqvcFO97/MYPOQu
            jx4r+oC/Su1I4KuwYvtH0bDAVgrORbvLQoYXeQ5peyFYv3pTkEKGWqO4VqxRHaws
            uwWXA2p1tMeYXyekWvLMIjNEA5Ak1W8AOBf/p2Unu8NdEvS8vEzpRDj1rWRziQVs
            UiDRBGlmoGXwLM8Lc3MrGTXX+a4Oc8u/5PmJntSHowKCAQEAva3+bi9nsfaI6ZPJ
            8IdcrZjyMx6Y7hxmYxQGjnsuCwvoXmQ/VJ9ZXR3tlm0SpQRN1umISjPI5fGm09jD
            M37NAtUgb+x6x6Bq2Gk2IaqDJ3jtmCExPHYPo8Fn0nTgTQmAoyJAkKg/C5OuvcB2
            sQf4LBvLTpYBnYR2O0Gl+3XbX+HLTHLwqLIp1dyN9iIiU06HKrOh7NPm5kB1/6Eq
            5o200esnKR0QRDPRpvfQIZxDBDxyy+HPZejnDvbwDHvlAT+ZTU89bHbafoCsIq6k
            BqEutOPAuYqYXXRwUct8FofGu3HVzlVoWm9tMh/MA9d5hEmrc78sqwhCWcQSpvGz
            RvFweQKCAQEAjc3+WeU36hwHtg3DvbaZxME7VyZtzKybVszUcuaAF4a60LKBiS8Y
            KrHDhJL/sSpSrOM5VqFQOC0rLogY8LD3IodQ6uAiVv6hFgmo+LHRAwLd1BDH/SAp
            7Z0beKVYI2IwbcudsS5xQnKmewhvb6bYhSLmume3B4rkT5S0P16CMuffm+BKR3iL
            H2I7A+QBpBnDWZJW85/SalgVXmmJj41KS9hIjEkZ5Dr/3MI3ZipHt0WDuTZb3olB
            3nBVnfTVAANWaUpxq9tD6TiEPmQMdOoJX5K4x8Cn+Yr6NZgUaNxbOfNKwg8oxOu7
            oIeFXEuciPE5i0D8O1yyWX1uMxe46e+n4wKCAQEAxeQ2BhtxbALOeD2rBwR/mTrb
            Nk/9nzlf0JzzsxwiS9+8spTL3p3GktjN8j5m1gLqkXS4CFT24vL05REsmYzbLbVa
            pYoD/Kj5qIaylk+UyNGaVF6Rl0vfb6vzFULvvoE525bfSuhG4lL54czYV/of1HeQ
            UvTsWKmwM5G9360AnS2kXEBiHvVSzl+qqH/nXYv0ZceO7bUMo4M8oDTsOKrhwceu
            900uYZHiMQK6kQbz35BEunSjObJ+BXw0INYI8QUCNFJvM5Y8J/DErKRTl9o1kZYJ
            My+A7vQV+l9ktLGLhRCNnlYxbIX1udS3oA0JgG6IqJG0T+yJa8w7+f4Op1K7uA==
            -----END RSA PRIVATE KEY-----
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777
        allow_host_access: true
        default_container_grace_time: 30m
        btrfs_store_size_mb: 50000

resource_pools:
  - name: workers
    network: private
    stemcell:
      name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      cpu: 2
      ram: 8_192
      disk: 80_000

compilation:
  workers: 3
  network: private
  reuse_compilation_vms: true
  cloud_properties:
    cpu: 2
    ram: 8_192
    disk: 30_000

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
