---
resources:
  - name: p-runtime
    type: git
    source:
      uri: git@github.com:pivotal-cf/p-runtime.git
      branch: salmon/push-apps-manager-release
      private_key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIJKAIBAAKCAgEA1b1PjU8Z9eyVxVquclBsaZW7irH12wSqGp6KuXqtXKyE6P70
        NVLgxcY+xKE1Qs3qlEo0Bw4qJP2O8RI05VDDLf5m5z3VsnjXm+U9pw84xsqpTduX
        yS6W+/XVRvwFkqxAyGJz3/uEjLOjmyW26ZGROPCdr5q1QnNYeGcDIros17CBn9FR
        giVxvjRL2p4p3vFz6v2JjhlVyLvath4GpZDgcIdM9Hm0Biyu9iSo4wCNVpkuPRfD
        LBeNaW+rs47UnrmcwfqA/+BUx1qAiQwgCipPP1UN6i8hlib98rs/AN6AK4tJhJFA
        oRSgH4b+jGlEhY/wXk7hoTINaFAzyJEuGHBVUzUP6dcZr+vt3iZf/tpdu7hRWTDb
        qZ/XpRTp0TEAOymSrNu2HVcTd4YDR0g42PfTRhu8TLwEgN/TjanoRZwEndu2cKC+
        gOyk/YZp4pDf7fHnH59BRAfllO1nOJPsN5oJJag4rPkj7sDQ14p3T9ZT4yzy6gVv
        VEQdPyYCZ4iIYnpVFjIcdUgbjZxc6/TzkR7+ktbDL/wlaeM3I+CuqjZIARp0sW0M
        ve4Je/rbtqGvRZ+0wAnFA0tYQ90YzAl2kDv0vdE2FO1NkuQwhFSEBOLMeZluihxX
        thkCLCmkYz0pjHS0tGrhyGdsJhvJYV5guvy/T1njYa96fqfrFr6pckFNpD0CAwEA
        AQKCAgBt3K7FPYFkjMS2+lNsYrY210Xclnh+qTkeEZvQlqQBXJO8hz/TINR0E+Az
        hYEw41LOAg4YCknTVZlhhDA4JnkMbRVLitcKs15vvTchZYuTcpvvbw3n1NC6lbOY
        lvXuXCe4WBKjcE7DW5qeppYMHEx+7f6/QlAk5dD1ok1UTkm6W/lkwlyY/tImKA9N
        QbrX41fn04Yeyhrz4MscjPZxp7QVYxZFG0FTYyhTUKiWdbQwbO/9avdg9II1Tbb9
        xk63f0R52F7yJsas6XHj/52AXBr7vKY4Vx12ZnhliaVqtvM+bovNXjPQGB/t1J+G
        YJ1d4Yx1jSoghu+pTIAxeZ4t5Z+VAk/WrDRKX4UdGA5clfosUGgcttBAitmVUafP
        yuVsYWbdQfEVWl3rkUvQMgqa17PQcqoNAINv35EMc7NW+ESbTrVQotncyeSbLZkl
        2bTmc3cgkAcyexZgjScD4PFVJumzlehZlZUcQZusBMxTD3xk+EOYHbHNI3yXAvDL
        jMkdFKdsQZT/xecGR2g/NzRb6gju1Gl8yGXucn8NPQMsO07n1DFYGj+UAMSKdyFZ
        KxeNwkM/5WHFIs9XAjW+SVeYjrYKLKn5HzUjluf/rvadV2Z3aue/F8qpfOoH4mYv
        izWpylOLFr2wFx1z53lBEp9Qni6954AWge2BIbPss4BWVrawQQKCAQEA+itZcH2V
        T+MosA9NrtHNAYyiptSswXgkuggn1YlVhU640mNh9mDsbXN6G17jffqKqx0+wzyO
        +UNOK5zIj/6HgNHZZCkmhCAJ0odMiSiBEZJx8vaTmpTZnfaUjMgWdJm+xoNb0epI
        80uP0O6nARPWzX8bx9ulR3EdHtpmpnhPHFpi8k5cTXKfl7VDizypb5kwAEFJ55wl
        h9XCnK4av9B0F4Bd+Er1TTdO5A/bC8L7HogWKYQhWYoPFKDwjQRDG+MYP1bprGJn
        tUHOMYNXtIJ6b1u9hCm835fr65V6WFq8V8r6GWsjd8zfzTUUgfwmSIwEOS3OK6NS
        Na3imkg6k8HXmQKCAQEA2riZu5iqHytOcscmUqnfZ2kB/wIVVLpr8sIoZuZzDHYu
        fIPoHPXM3moQ0/H7aqCR7WM/j/6VROXZiA3pVDkhIvCiLcaOQSxZBNlF7IT6XOBM
        SHM4t0xq+JCQ/7MTwP4OxmFvv+0bEwbun53ZJxY3eQdABu+5OLIxkKoyLV6oEATQ
        4Ul1iQ4YHd3K61YfjevFUYb7PQV7zORK6Dnxbt+7ju4XkwlDewv/62dvNkjBpwcq
        fJwuIjn8K2Teq3F7NPaZxReHeSs6K10hDkTIIP3AWdIJE1crN7dlXusZ0xd1HY5y
        JnlnesY1DH/mFbyLXDeUOAZgBR/wdgflpIQpYffIRQKCAQBXIMvoosRi62GbV+kd
        TtKQjJOFeSKlyxs3c2m0ND2FzTIPjC9tKLqPMB3B9J1UnfK3v9rBEpFU/Pz3sYYk
        qGg3FF8bRD223JWvLhIY3vN81D09emVT/C2Cl4OLOJChkX5hExTimi9IFPQEt2mQ
        tYElVvSs+bGpnRqgST5hEhuza0N00pfRHW+53Zalor38MSUHobWEpdxoX6mE+ho0
        3fvgx4Ny22BtwSqHwYHvqbveGVVmpi8bSTsRWzAMXQSmbMRgIvwFXsxx03ZlxjHA
        m4Tazd/GbObsFLRE+2194jQge3/5ZFgY/FCh3q/CybfnomRCKdLZXete6K24QBmu
        pl9ZAoIBAQCnPSWXcqkKAjQOwUYFSQygZoN3OGGVEqI90cXQwH7R1X/AB6AwnKXU
        nudVGB70rehGym+sq635K4MEbBawJqq2q6ZmN/9HyCAc/AFiU1+YKo1JjIieZ1kX
        zHqCeawuElS7zX8EEslz6AYHmEuVfoBWE3wakaxftKj/g5Owa0M4VGZfDKtJa7R3
        CcMB5S1leBS9POfYBdxek2TPYpa//2TLajQuYpPtfwRlPAamTEV+cJVFCKqh0xKF
        H7C/CJt7qN90+4PD25Cz3ZbL8T3RNBWi2F3GIw3RoXJqfHuXk8UiH2wbDRNZpjqj
        3xvQHQW2Mm0r1XwQDxbvOSSXgdKerTa9AoIBAFlFzTMZ//v7F948Iz6DXJCjnQc8
        QS2WhFpK0IvCqTQOP6sF5+1WXC+h/0enu/gAPnVcHtZXIFmQdewxhhPcOAdH2BZh
        2NsDfcYJVx4Wtw9C9jikZQQYx505ZkYubo3GBgMRwHNGjBs16IdvsdX5AgxmSArT
        dXgfTDbXcRy62CIscE9V2fxABna7Vvik+/xt0KMvL8M/nzdBVc0bcbZm1KC+/Ycz
        pUEDWOX9vSlDhKleUJz6YFJiDE6JJ9yh8gwumDqrkPyAIRwHZeKYovrPpBQD7Seg
        jVZlEocQRYfQd6Sz8V+7xdz0Q47ix7QkOeiKNOsy5ESzLdqfNDZ/RPC2nF8=
        -----END RSA PRIVATE KEY-----

  - name: version
    type: semver
    source:
      access_key_id: AKIAJEAGY2FWB7DEGFXQ
      secret_access_key: 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
      bucket: ert-concourse-products
      region_name: us-west-1
      key: ert-1.6/version
      initial_version: 1.6.0-build.0

  - name: ert-product
    type: s3
    source:
      access_key_id: AKIAJEAGY2FWB7DEGFXQ
      secret_access_key: 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
      bucket: ert-concourse-products
      region_name: us-west-1
      private: true
      versioned_file: salmon/push-apps-manager-release/ert.pivotal

  - name: environment
    type: pool
    source:
      uri: git@github.com:pivotal-cf-experimental/releng-env-resource-pool
      branch: master
      pool: aws-apps-manager
      private_key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIJKQIBAAKCAgEA03pnH/e8lfNriECxroDeZkxY5uEgLhxpcGSFD4oczVP2FzMg
        4hOq9JM5jNqHW3ZL/s9aAq8nkPLnkq8E6IEjL3+dZJUTjlIAvcKl5VCThLMpAJx3
        UEg04q6vIEHKzZh6XKQtDWUxRH+TcGwqo5vKZ3WPUeZdd+7ZUzEzOl/+iz3Peobj
        eVcl+7maMUzlSymAjAQDhdRnZ30l61AuVH9ursCMY0OJwchCoxZFxn0n4qUaTzf0
        she9U4cNwExMWLwidHrhbFanKk1vXN7ZhECuL5rMnTuDy5++R2svAogK2wBmUr/S
        tMMekF6gxSQOSWGV7orhGa0iF3reXkeKUGgMfaXiW1S9BaWKaRfmF63jfH/iBLSQ
        CfWBVmgvMWGeQXm6sx020282Rgvcr5h2QUHx+HqDOOtEij6HPiKm0R9DygtpspX3
        RxES49k0S+Jy2vP21j9Qu92sqCbI7h0jCAadYmvN7+li6hBZNNup2TXMeyTjH08U
        Fa0jPlyM2cufJmt1iMSjXHk0utmO2v6o+GZ8S9GMKfMli2Fv/kWm2OlOs9wON+bw
        YX2XqBmF10UW0wGutu/E9TizhTVYvNOan45NYc/n+Ldh0bfXgchrWXc/Qwobp6DX
        h/WjQSkMfTGSX7obK0vo6+VWs1/249EwuXy/6rJo6lKDXmpkxUqHGpswZAcCAwEA
        AQKCAgAv9e+TWWzkmQsHIJzrVYCatK/o1J+mtXzYJ4PhzVHQ4zzJcCgB/bHku8ru
        fdT60i5UAJSKTUzs25nXM2gqjrb7G7cHS6PewAw4/P8ArbB3BObEo7ePdoC/9Bv1
        ddZXoEAH6JfrFMsCnOhEM9PLvRY/NnMlgNgrzfhtnJfgokqpK4B1akgGidQsbaBh
        k+3giO4FUxe1b0FwP/qsjkejlC725OYx0OxaDV/HetKiPFoiVY1M8ATHqwid++AL
        f4JFEY3C2udq2ZAZ0OvzpPqxurWGSFYlRo0STg0qR02nBlFn74RFOgnAQwwYc82E
        SDQRQldtfQOl/hTgPFZYDWN57s79+jc61bFDrm1+q2m8Yp708wVzxHmL15QnFjfQ
        X5LdS39PITF27nzjF2nZwoCNWe1iMUolPxH227Cxq9LtZRBrNKPG/eMVQd0EVc+U
        DtlcffIbJc19ByYHtFubMwWTmd2vdIYRIbuOKDxT/Q7oGfWSBtfceGCjHgQkQme6
        oM2Kvj7zifLeETHUhxDGH0X1eBKjnuyvCYqXls2/l2Ae4Sigp4S7r78tti/KRvwN
        1bhsVfuXGpjAjS+Y5laY1d6myAvr0qvYhDZ9+HWA0358bvLaq/Ru4LEUe9gTFgZX
        CG6uYI0EEAoj2ZyzAh/0JCeNGXV0X2ucQSzwAwDlI0K6Qz53gQKCAQEA92zsgWmN
        alL0NHfDuDl8TGAu5SGtgXq5c89l7NiKlT9rGXURkN9Hw1Ln1N+rkbI0IvojIfX2
        mr+gSxgQS/A71YioNaxZyfDW0Botd3oxWISjT03XS48VlJkSULK0V2TpWoRA/Q8C
        9jWaxazARr4uf2K5Jq5wj4VImjnASpvyFue7iWpJjZXfHI0683c8jUhkTtzZpJYh
        Dz4NJNXNEbPcz+ln7osBIw4RzYlgYubiJ2CMcbh2mOgECIFR7yhPZRoMv+w0qjqt
        IVDseDK5jtRRJwJ35Wlzv6+KmJATAropiIP/gVal6U2hNiaBgHwf6tDI30j5Il25
        /FsdYGumz6lqwQKCAQEA2s6Q7ijIPfPDwjLtCkrhUajREy9Q4GYx2XjYb7RSCjV6
        nC3IsKXRRZxyuSC9o8z7+yPm98YLIOKeF2nxGr1+3OZ48VE6dZ2lkvbYq6yy64tl
        Y13WoCbtfWAB2k7VLxYj1vVcUgYEjwekvap4oe66Y/vE3kwyV1AaVVlD5nV1eZui
        4RmfZemdfh3M5OdqsEJt7xZZI47uSM1dQhkonmDH/bzlhsWQfQdHmrYXH0JRXnLw
        DFas/gHuTrH8ojZCVdU9a8Iuzfmmt0t3NLWIwFmOIQ0dhjVotoCOCN/QOMVAWhPL
        D3skurIHCigv81KFrRqgJcQF+ymrY6ulHxuUwyBoxwKCAQB/dqu4V4o0tht8VB6N
        739rUTmXbOwXggO796JIi52JGayw5rBv87bilvk7nyah3i4hvr8OpcmvGv0W8oSi
        ulX4wXf2fp2a/OmNN48ot9hoA5ymJDG/iSzS6rCWxhlF1ISqzusz8uHRuPfM0hwT
        1bHaih9cIA14wm8OlKXNSd1Dk4n3Vrwhpo3UBaXS+yBEoICcaAXvVjAdzBe1XDdS
        4Vfl/BZAu3eQeZUOT7FKAiuLoZ94jlD6oLxDLWvqStfr+6mJzcOr1qKOQUQw/+C8
        BgDwmcLueo7YtzQtODuy8finjWi5VswODqH4ZYndiRRgQcLZ1JwT6jkAGmhd3deH
        r32BAoIBAQDHtNHDDaX2JY7+qMyBIGcWySZKhF0k8yF8hDfHfKWEe9s0wPTzheTD
        zE9JeQCdiHJUfihI7ZEqqqvwYtmUtnAb3p90YdchkomU4YhQ6IdFRS18zCEge2c3
        j3Ehd+JL38FGaRuiIav3f9p04irIYcPtjdXZr2IjHxFp5Nd8eKiIHe1D1scNlXQR
        r9Fa+3z88ySzm4owUjxaZlZABgZ0x5DBnq8/mwKNmx9XrerctQLfWbiPCm1KSSjg
        2sLiqvNQtBgjSlC93qazlUVv7mCqbxKyR+4ymHzCVgNNRjoeFqrtjDNCJfsYC3Ux
        aAyb4S3xGOQilA+Bdj7f8cH76oiUr/fxAoIBAQDZHN3cSZQdF5nc06w6ToD2AuJH
        csEryys4lrglW6CVr2gjnaCH4mwp2Ac4JLnTLu84gDYVZKATaJV/Rv2XNpnmXg9x
        nyAPNw+lv1I8I0kqiA/f8fjkjnptwTRGapacyVt4IN52fvB5xGohVwLp0omb1En9
        ivzguGbOdNX4szbFNv9t5xhw3bvvpR3fKStaYlWjIOD07w/ekU3G0fBSqnSNblFw
        J+R2R0z5fNX5AD8RfiVPLhmLTpbY5rwuujFiaHDs/nJvtgeSgQ9y9y9DyB99ZtPP
        OVKNK3IjWsq4oU3qLRZ8w9ZdA06jePzJ6x3ppx6H60u+sock2D8+eeMxjtmJ
        -----END RSA PRIVATE KEY-----

  - name: ops-manager-stable
    type: s3
    source:
      access_key_id: AKIAJEAGY2FWB7DEGFXQ
      secret_access_key: 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
      bucket: ert-concourse-products
      region_name: us-west-1
      private: true
      versioned_file: ops_manager_images/aws/stable/ops_man_image

  - name: upstream-release-metadata
    type: s3
    source:
      access_key_id: AKIAJEAGY2FWB7DEGFXQ
      secret_access_key: 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
      bucket: ert-concourse-products
      region_name: us-west-1
      private: true
      versioned_file: upstream-release-metadata/push-apps-manager-release/metadata.yml

jobs:
  - name: claim-environment
    serial: true
    plan:
      - get: p-runtime
      - get: upstream-release-metadata
        trigger: true
      - put: environment
        timeout: 1m
        params:
          acquire: true
      - task: update-krafa
        file: p-runtime/ci/jobs/update-krafa.yml
        config:
          params:
            CLAIM_REASON: salmon/push-apps-manager-release
            KRAFA_BASE_URL: http://krafa.cfapps.io
            KRAFA_USERNAME: releng
            KRAFA_PASSWORD: bet90onions

  - name: destroy-environment
    plan:
      - aggregate:
        - get: p-runtime
          trigger: true
          passed: [claim-environment]
        - get: environment
          trigger: true
          passed: [claim-environment]
        - get: upstream-release-metadata
          trigger: true
          passed: [claim-environment]
      - task: destroy
        tags: [aws]
        file: p-runtime/ci/jobs/destroy-environment.yml

  - name: deploy-ops-manager
    plan:
      - aggregate:
        - get: p-runtime
          trigger: true
          passed: [destroy-environment]
        - get: environment
          trigger: true
          passed: [destroy-environment]
        - get: upstream-release-metadata
          trigger: true
          passed: [destroy-environment]
      - aggregate:
        - get: ops-manager
          resource: ops-manager-stable
        - task: prepare
          tags: [aws]
          file: p-runtime/ci/jobs/prepare-environment.yml
      - task: deploy
        tags: [aws]
        file: p-runtime/ci/jobs/deploy-opsman.yml

  - name: configure-microbosh
    plan:
      - aggregate:
        - get: p-runtime
          trigger: true
          passed: [deploy-ops-manager]
        - get: environment
          trigger: true
          passed: [deploy-ops-manager]
        - get: upstream-release-metadata
          trigger: true
          passed: [deploy-ops-manager]
      - task: configure
        tags: [aws]
        file: p-runtime/ci/jobs/configure-microbosh.yml
        config:
          params:
            OPSMAN_VERSION: 1.6

  - name: deploy-microbosh
    plan:
      - aggregate:
        - get: p-runtime
          trigger: true
          passed: [configure-microbosh]
        - get: environment
          trigger: true
          passed: [configure-microbosh]
        - get: upstream-release-metadata
          trigger: true
          passed: [configure-microbosh]
      - task: deploy
        tags: [aws]
        file: p-runtime/ci/jobs/deploy-microbosh.yml
        config:
          params:
            OPSMAN_VERSION: 1.6
        ensure:
          task: get-install-log
          tags: [aws]
          file: p-runtime/ci/jobs/get-install-log.yml
          config:
            params:
              OPSMAN_VERSION: 1.6

  - name: build-runtime
    plan:
      - get: version
        params:
          bump: patch
          pre: build
      - put: version
        params:
          file: version/number
      - aggregate:
        - get: p-runtime
          trigger: true
          passed: [claim-environment]
        - get: upstream-release-metadata
          trigger: true
          passed: [claim-environment]
      - task: build-product
        file: p-runtime/ci/jobs/build-pivotal-with-upstream-metadata.yml
        config:
          params:
            EXTERNAL_RELEASE: upstream-release-metadata/metadata.yml
      - put: ert-product
        params:
          from: build-product/ert.pivotal

  - name: upload-pivotal
    plan:
      - aggregate:
        - get: p-runtime
          trigger: true
          passed: [build-runtime, deploy-microbosh]
        - get: environment
          trigger: true
          passed: [deploy-microbosh]
        - get: upstream-release-metadata
          trigger: true
          passed: [deploy-microbosh,build-runtime]
        - get: ert-product
          trigger: true
          passed: [build-runtime]
      - task: upload-pivotal
        tags: [aws]
        file: p-runtime/ci/jobs/upload-pivotal.yml
        config:
          params:
            OPSMAN_VERSION: 1.6

  - name: configure-ert
    plan:
      - aggregate:
        - get: p-runtime
          trigger: true
          passed: [upload-pivotal]
        - get: environment
          trigger: true
          passed: [upload-pivotal]
      - task: configure-ert
        tags: [aws]
        file: p-runtime/ci/jobs/configure-ert.yml
        config:
          params:
            ERT_VERSION: 1.6
            OPSMAN_VERSION: 1.6
      - task: configure-experimental-features
        tags: [aws]
        file: p-runtime/ci/jobs/configure-experimental-features.yml
        config:
          params:
            ERT_VERSION: 1.6
            OPSMAN_VERSION: 1.6

  - name: import-stemcell
    plan:
      - aggregate:
        - get: p-runtime
          trigger: true
          passed: [configure-ert]
        - get: environment
          trigger: true
          passed: [configure-ert]
      - task: import-stemcell
        tags: [aws]
        file: p-runtime/ci/jobs/auto-download-import-stemcell.yml
        config:
          params:
            OPSMAN_VERSION: 1.6
            PRODUCT_NAME: cf
            IAAS: aws

  - name: deploy-ert
    plan:
      - aggregate:
        - get: p-runtime
          trigger: true
          passed: [import-stemcell]
        - get: environment
          trigger: true
          passed: [import-stemcell]
      - task: deploy-ert
        tags: [aws]
        file: p-runtime/ci/jobs/deploy-ert.yml
        config:
          params:
            OPSMAN_VERSION: 1.6
        ensure:
          task: get-install-log
          tags: [aws]
          file: p-runtime/ci/jobs/get-install-log.yml
          config:
            params:
              OPSMAN_VERSION: 1.6

  - name: run-cats
    plan:
      - aggregate:
        - get: p-runtime
          trigger: true
          passed: [deploy-ert]
        - get: environment
          trigger: true
          passed: [deploy-ert]
      - task: run-cats
        tags: [aws]
        file: p-runtime/ci/jobs/run-cats.yml
        config:
          params:
            OPSMAN_VERSION: "1.6"
        on_failure:
          put: cats-logs
          params:
            from: cats-log.tgz

  - name: cats-logs
    type: s3
    source:
      access_key_id: AKIAJEAGY2FWB7DEGFXQ
      secret_access_key: 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
      bucket: ert-concourse-products
      region_name: us-west-1
      private: true
      versioned_file: cf-acceptance-tests-logs/cats-log.tgz

  - name: destroy-environment-final
    plan:
      - aggregate:
        - get: p-runtime
          passed: [run-cats]
        - get: environment
          passed: [run-cats]
      - task: destroy
        tags: [aws]
        file: p-runtime/ci/jobs/destroy-environment.yml

  - name: release-environment
    plan:
      - aggregate:
        - get: p-runtime
          passed: [destroy-environment-final]
        - get: environment
          trigger: true
          passed: [destroy-environment-final]
      - put: environment
        params:
          release: environment

groups:
  - name: salmon/push-apps-manager-release
    jobs:
    - claim-environment
    - destroy-environment
    - deploy-ops-manager
    - configure-microbosh
    - deploy-microbosh
    - build-runtime
    - upload-pivotal
    - configure-ert
    - import-stemcell
    - deploy-ert
    - run-cats
    - destroy-environment-final
    - release-environment
