---
name: application_security_groups
label: Application Security Groups
description: |
  Application Security Groups
markdown: |
  To configure this pane, see the
  [Configure Application Security Groups](https://docs.pivotal.io/pivotalcf/2-7/customizing/configure-pas.html#app-security)
  section of the _Configuring PAS_ topic in the PCF documentation.

property_inputs:
  - reference: .properties.security_acknowledgement
    label: |
      Type "X" to acknowledge this requirement.
