---
name: application_security_groups
label: App Security Groups
description: App Security Groups
markdown: |
  For help configuring these fields, see the
  [Configure App Security Groups](https://docs.pivotal.io/pivotalcf/2-10/customizing/configure-pas.html#app-security)
  section of the _Configuring Application Service_ topic in the product documentation.

property_inputs:
  - reference: .properties.security_acknowledgement
    label: Type "X" to acknowledge this requirement.
