---
name: apps_manager_config
label: Apps Manager
description: Configure Apps Manager

property_inputs:
  - reference: .properties.push_apps_manager_enable_invitations
    label: Enable Invitations

  - reference: .properties.push_apps_manager_display_plan_prices
    label: Display Marketplace Service Plan Prices

  - reference: .properties.push_apps_manager_currency_lookup
    label: Supported currencies as JSON
    description: |
      Define the currency codes and associated symbols (defaults to { "usd": "$", "eur": "€" })

  - reference: .properties.push_apps_manager_product_name
    label: Product Name
    description: |
      Replace "Apps Manager" in the header with a custom product name
      (defaults to "Apps Manager" if blank)

  - reference: .properties.push_apps_manager_marketplace_name
    label: Marketplace Name
    description: Replaces "Marketplace" on the Apps Manager Marketplace Pages.

  - reference: .properties.push_apps_manager_nav_links
    label: Customize Sidebar Links
    description: |
      You may configure up to 10 links in the Apps Manager sidebar.
    property_inputs:
      - reference: name
        label: Link text

      - reference: href
        label: URL

  - reference: .properties.push_apps_manager_memory
    label: Apps Manager Memory Usage (MB)
    description: |
      Memory limit with which to deploy the Apps Manager app. Leave blank
      to use the default value.

  - reference: .properties.push_apps_manager_invitations_memory
    label: Invitations Memory Usage (MB)
    description: |
      Memory limit with which to deploy the Invitations app. Leave blank
      to use the default value.

  - reference: .properties.push_apps_manager_poll_interval
    label: Apps Manager Polling Interval
    description: |
      Apps manager polling interval in seconds. As a workaround to reduce
      load on the Cloud Controller API, increase the polling interval or
      set to 0 to stop polling. Values between 0 and 30 will default to 30 seconds.

  - reference: .properties.push_apps_manager_app_poll_interval
    label: App Details Polling Interval
    description: |
      App details polling interval in seconds. As a workaround to reduce load
      on the Cloud Controller API, and if adjusting the apps manager polling
      interval is not sufficient, increase the app details polling interval
      or set to 0 to stop polling. Values between 0 and 10 will default to 10 seconds.

  - reference: .properties.push_apps_manager_foundations
    label: Multi-Foundation Configuration (BETA)
    description: |
      JSON string containing foundations to which this Apps Manager should be connected.