---
name: apps_manager_config
label: Apps Manager
description: Apps Manager
markdown: |
  To configure this pane, see the
  [(Optional) Configure Custom Branding and Apps Manager](https://docs.pivotal.io/pivotalcf/2-7/customizing/configure-pas.html#customize-apps-man)
  section of the _Configuring PAS_ topic in the PCF documentation.

property_inputs:
  - reference: .properties.push_apps_manager_enable_invitations
    label: Enable invitations

  - reference: .properties.push_apps_manager_display_plan_prices
    label: Display Marketplace service plan prices

  - reference: .properties.push_apps_manager_currency_lookup
    label: Supported currencies as JSON
    description: |
      Define currency codes and associated symbols. Defaults to { "usd": "$", "eur": "€" }.

  - reference: .properties.push_apps_manager_product_name
    label: Product name
    description: |
      Enter a custom product name. Defaults to "Apps Manager".

  - reference: .properties.push_apps_manager_marketplace_name
    label: Marketplace name
    description: Enter a custom Marketplace name.

  - reference: .properties.push_apps_manager_nav_links
    label: Customize sidebar links
    description: Configure up to 10 links in the Apps Manager sidebar.
    property_inputs:
      - reference: name
        label: Link text

      - reference: href
        label: URL

  - reference: .properties.push_apps_manager_memory
    label: Apps Manager memory usage (in MB)
    description: |
      The memory limit with which to deploy the Apps Manager app.
      Leave blank to use the default value.

  - reference: .properties.push_apps_manager_invitations_memory
    label: Invitations memory usage (in MB)
    description: |
      The memory limit with which to deploy the Invitations app.
      Leave blank to use the default value.

  - reference: .properties.push_apps_manager_poll_interval
    label: Apps Manager polling interval (in seconds)
    description: |
      The Apps Manager polling interval. Values between 0 and 30
      default to 30 seconds.

  - reference: .properties.push_apps_manager_app_poll_interval
    label: App details polling interval (in seconds)
    description: |
      App details polling interval in seconds. Values between 0
      and 10 default to 10 seconds.

  - reference: .properties.push_apps_manager_foundations
    label: Multi-foundation configuration (beta)
    description: |
      A JSON string containing all the foundations Apps Manager
      manages.
