---
name: apps_manager_config
label: Apps Manager
description: Apps Manager
markdown: |
  For help configuring these fields, see the
  [Configure Custom Branding and Apps Manager](https://docs.pivotal.io/pivotalcf/2-7/customizing/configure-pas.html#customize-apps-man)
  section of the _Configuring PAS_ topic in the PCF documentation.

property_inputs:
  - reference: .properties.push_apps_manager_enable_invitations
    label: Enable invitations

  - reference: .properties.push_apps_manager_display_plan_prices
    label: Display Marketplace service plan prices

  - reference: .properties.push_apps_manager_currency_lookup
    label: Supported currencies as JSON
    description: |
      Define currency codes and associated symbols.
      Defaults to { "usd": "$", "eur": "€" }.

  - reference: .properties.push_apps_manager_product_name
    label: Product name
    description: |
      Enter a custom product name. Defaults to "Apps Manager".

  - reference: .properties.push_apps_manager_marketplace_name
    label: Marketplace name
    description: Enter a custom Marketplace name.

  - reference: .properties.push_apps_manager_nav_links
    label: Customize sidebar links
    description: Configure up to 10 links in the Apps Manager sidebar.
    property_inputs:
      - reference: name
        label: Link text

      - reference: href
        label: URL

  - reference: .properties.push_apps_manager_memory
    label: Apps Manager memory usage
    description: |
      The memory limit for the Apps Manager app.
      Enter value in MB. Leave blank to use the default value
      of 128 MB.

  - reference: .properties.push_apps_manager_invitations_memory
    label: Invitations memory usage
    description: |
      The memory limit for the Invitations app. Enter value in MB.
      Leave blank to use the default value of 256 MB.

  - reference: .properties.push_apps_manager_poll_interval
    label: Apps Manager polling interval
    description: |
      The Apps Manager polling interval. Enter value in seconds.
      Leave blank to use the default value of 30 seconds.

  - reference: .properties.push_apps_manager_app_poll_interval
    label: App details polling interval
    description: |
      App details polling interval. Enter value in seconds.
      Leave blank to use the default value of 10 seconds.

  - reference: .properties.push_apps_manager_foundations
    label: Multi-foundation configuration (beta)
    description: |
      A JSON string containing all the foundations Apps Manager
      manages.
