---
form:
  name: generic_white_label_config
  label: Custom Branding
  description: |
    Customize colors, images, and text for Apps Manager and the Cloud Foundry
    login portal.

  property_inputs:
    - reference: .properties.push_apps_manager_company_name
      label: Company Name
      description: Defaults to 'Pivotal'

    - reference: .properties.push_apps_manager_accent_color
      label: Accent Color
      description: Enter a hexadecimal color code like '#71ffda'

    - reference: .properties.push_apps_manager_logo
      label: Main Logo (PNGs only)
      description: |
        Enter a base64-encoded PNG image string, but leave out the mime-type
        (data:image/png;base64,) string. Only enter the base64 encoded data.

    - reference: .properties.push_apps_manager_square_logo
      label: Square Logo/Favicon (PNGs only)
      description: |
        Enter a base64-encoded PNG image string, but leave out the mime-type
        (data:image/png;base64,) string. Only enter the base64 encoded data.

    - reference: .properties.push_apps_manager_footer_text
      label: Footer Text
      description: Defaults to 'Pivotal Software Inc. All rights reserved.'

    - reference: .properties.push_apps_manager_footer_links
      label: Footer Links
      description: |
        You may configure up to three links in the Apps Manager footer.
      property_inputs:
        - reference: name
          label: Link text

        - reference: href
          label: URL

    - reference: .properties.push_apps_manager_global_wrapper_bg_color
      label: Classification Header/Footer Background Color
      description: Enter a hexadecimal color code like '#71ffda'

    - reference: .properties.push_apps_manager_global_wrapper_text_color
      label: Classification Header/Footer Text Color
      description: Enter a hexadecimal color code like '#71ffda'

    - reference: .properties.push_apps_manager_global_wrapper_header_content
      label: Classification Header Content
      description: Plain text or HTML Markup

    - reference: .properties.push_apps_manager_global_wrapper_footer_content
      label: Classification Footer Content
      description: Plain text or HTML Markup
