---
name: mysql_config
label: Internal MySQL
description: Internal MySQL
markdown: |
  To configure this pane, see the
  [(Optional) Configure Internal MySQL](https://docs.pivotal.io/pivotalcf/2-7/customizing/configure-pas.html#internal-mysql)
  section of the _Configuring PAS_ topic in the PCF documentation.

property_inputs:
  - reference: .mysql_monitor.poll_frequency
    label: Replication canary time period (in seconds)
    description: |
      How frequently the canary checks for replication
      failure.

  - reference: .mysql_monitor.write_read_delay
    label: Replication canary read delay (in seconds)
    description: |
      How long the canary waits to verify data is replicating
      across each MySQL node.

  - reference: .mysql_monitor.recipient_email
    label: Email address
    description: |
      The email to which MySQL sends alerts when the
      cluster experiences a replication issue or a node
      is not allowed to auto-rejoin the cluster.

  - reference: .mysql.cli_history
    label: Allow command history
    description: |
      Allows the creation of command line history files on
      MySQL nodes.

  - reference: .mysql.remote_admin_access
    label: Allow remote admin access
    description: |
      Admin and roadmin can connect from any remote host.

  - reference: .mysql.cluster_probe_timeout
    label: Cluster probe timeout (in seconds)
    description: |
      The maximum amount of time that a new node searches
      for existing cluster nodes. The default value is 10
      seconds.

  - reference: .mysql.max_connections
    label: Maximum connections
    description: |
      The maximum number of connections allowed to the database.

  - reference: .properties.mysql_activity_logging
    label: Server activity logging
    selector_property_inputs:
      - reference: .properties.mysql_activity_logging.disable
        label: Disable server activity logging

      - reference: .properties.mysql_activity_logging.enable
        label: Enable server activity logging
        property_inputs:
          - reference: .properties.mysql_activity_logging.enable.audit_logging_events
            label: Event types

  - reference: .mysql_proxy.startup_delay
    label: Load balancer healthy threshold (in seconds)
    description: |
      Specifies the amount of time to wait until reporting the
      MySQL Proxy instance has started.

  - reference: .mysql_proxy.shutdown_delay
    label: Load balancer unhealthy threshold (in seconds)
    description: |
      Specifies the amount of time that the MySQL Proxy continues
      to accept connections before shutting down.

  - reference: .mysql.prevent_node_auto_rejoin
    label: Prevent node auto re-join
    description: |
      Enables MySQL Interruptor to prevent nodes with inconsistent
      data from writing to the MySQL database.
