---
name: smtp_config
label: Email Notifications
description: Email Notifications
markdown: |
  For help configuring these fields, see the
  [Configure Email Notifications](https://docs.pivotal.io/pivotalcf/2-9/customizing/configure-pas.html#smtp)
  section of the _Configuring PAS_ topic in the Pivotal Platform documentation.

property_inputs:
  - reference: .properties.smtp_from
    label: From email
    description: The email address from which emails are sent.

  - reference: .properties.smtp_address
    label: SMTP server address
    description: The SMTP address of the server that sends emails.

  - reference: .properties.smtp_port
    label: SMTP server port
    description: The port of the SMTP server that sends emails.

  - reference: .properties.smtp_credentials
    label: SMTP server credentials
    description: The credentials for the SMTP server that sends emails.

  - reference: .properties.smtp_enable_starttls_auto
    label: SMTP enable automatic STARTTLS
    description: |
      Automatically creates a secure TLS connection
      when sending emails.

  - reference: .properties.smtp_auth_mechanism
    label: SMTP authentication mechanism

  - reference: .properties.smtp_crammd5_secret
    label: SMTP CRAMMD5 secret
